// ============================================================================
// chain_flow_dsl_tests_module.h
// Generated by ChainTree S-Expression DSL v2.8
// DO NOT EDIT
// ============================================================================

#ifndef CHAIN_FLOW_DSL_TESTS_MODULE_H
#define CHAIN_FLOW_DSL_TESTS_MODULE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

// Size configuration
#define MODULE_IS_64BIT 0
#define CHAIN_FLOW_DSL_TESTS_IS_64BIT 0

// Type aliases (based on 64-bit flag)
typedef int32_t ct_int_t;
typedef uint32_t ct_uint_t;
typedef float ct_float_t;
#define CT_TYPES_DEFINED 1

#include "s_engine_types.h"

#include "chain_flow_dsl_tests_pools.h"

// ============================================================================
// FUNCTION NAME TABLES (shared by all trees)
// ============================================================================

// Oneshot (@) function names
static const char* const chain_flow_dsl_tests_oneshot_names[] = {
    "TEST_29_SET_STATE",
    "CFL_DISABLE_CHILDREN",
    "CFL_ENABLE_CHILDREN",
    "TEST_30_SET_STATE",
    "CFL_LOG",
    "CFL_ENABLE_CHILD",
    "CFL_EXCEPTION",
    "TEST_31_SET_STATE",
    "TEST_31_SET_MOTOR",
    "TEST_32_TOGGLE_LED",
    "TEST_32_ENABLE_BUZZER",
    "TEST_32_SET_LED",
    "TEST_32_NOTIFY_SYSTEM",
    "CFL_INTERNAL_EVENT",
    "TEST_32_DISABLE_ALL_OUTPUTS",
    "TEST_32_SAVE_STATE",
};
#define CHAIN_FLOW_DSL_TESTS_ONESHOT_NAMES_COUNT 16

// Boolean (?) function names
static const char* const chain_flow_dsl_tests_boolean_names[] = {
    "TEST_29_READ_STATE",
    "CFL_READ_BIT",
    "CFL_S_BIT_OR",
    "CFL_S_BIT_AND",
    "TEST_30_CHECK_STATE",
};
#define CHAIN_FLOW_DSL_TESTS_BOOLEAN_NAMES_COUNT 5

// Main (!) function names
static const char* const chain_flow_dsl_tests_main_names[] = {
    "CFL_DISABLE_CHILDREN",
    "TEST_29_SET_STATE",
    "CFL_ENABLE_CHILDREN",
    "TEST_29_DF_CONTROL",
    "CFL_TICK_DELAY",
    "CFL_STATE_MACHINE",
    "CFL_STATE_ACTIONS",
    "TEST_30_SET_STATE",
    "TEST_31_SET_STATE",
    "TEST_32_PROCESS_SCHEDULED_TASKS",
    "TEST_32_DEBOUNCE",
    "TEST_32_CHECK_THRESHOLD",
    "TEST_32_GENERATE_INTERNAL_EVENTS",
    "TEST_32_RUN_BACKGROUND_TASKS",
    "CFL_DISPATCH",
    "CFL_EVENT_DISPATCH",
};
#define CHAIN_FLOW_DSL_TESTS_MAIN_NAMES_COUNT 16

// Data strings
static const char* const chain_flow_dsl_tests_strings[] = {
    "node_state",
    "state 1 active",
    "state 1 terminate",
    "state 2 active",
    "state 2 terminate",
    "state 3 active",
    "state 3 terminate",
    "UNKNOWN_STATE test_30_state_machine",
    "Moving forward",
    "Moving backward",
    "Turning left",
    "Turning right",
    "Stopping",
    "Idle",
    "SHOULD NOT HAPPEN",
    "Timer expired",
    "Button pressed",
    "Sensor reading",
    "ALARM TRIGGERED",
    "ALARM",
    "ALARM SETTING",
    "Shutdown requested",
    "Idle - SHOULD NOT HAPPEN",
};
#define CHAIN_FLOW_DSL_TESTS_STRINGS_COUNT 23

// ============================================================================
// TREE: s_expression_test_1
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_1_params[] = {
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 0 },  // [0]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // branch_1  // [1]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [2]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 0 },  // [3]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // branch_1  // [4]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [5]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [6]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [7]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [8]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 0 },  // [9]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // branch_1  // [10]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [11]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [12]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [14]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [15]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 0 },  // [16]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // branch_1  // [17]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [18]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_1_PARAM_COUNT 19

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_1_nodes[] = {
    { .type = 0x01, .child_count = 4, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 0, .param_offset = 0, .param_count = 3, .reserved = 0 }, // [1]
    { .type = 0x40, .child_count = 0, .node_index = 2, .first_child = 0xFFFF, .next_sibling = 0x0003, .fn_index = 1, .param_offset = 3, .param_count = 0, .reserved = 0 }, // [2]
    { .type = 0x03, .child_count = 3, .node_index = 3, .first_child = 0x0004, .next_sibling = 0x001F, .fn_index = 0, .param_offset = 3, .param_count = 0, .reserved = 0 }, // [3]
    { .type = 0x80, .child_count = 0, .node_index = 4, .first_child = 0xFFFF, .next_sibling = 0x0005, .fn_index = 0, .param_offset = 3, .param_count = 2, .reserved = 0 }, // [4]
    { .type = 0x03, .child_count = 3, .node_index = 5, .first_child = 0x0006, .next_sibling = 0x0012, .fn_index = 0, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [5]
    { .type = 0x07, .child_count = 2, .node_index = 6, .first_child = 0x0007, .next_sibling = 0x000D, .fn_index = 0, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [6]
    { .type = 0x06, .child_count = 2, .node_index = 7, .first_child = 0x0008, .next_sibling = 0x000A, .fn_index = 0, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [7]
    { .type = 0x80, .child_count = 0, .node_index = 8, .first_child = 0xFFFF, .next_sibling = 0x0009, .fn_index = 1, .param_offset = 5, .param_count = 1, .reserved = 0 }, // [8]
    { .type = 0x80, .child_count = 0, .node_index = 9, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 6, .param_count = 1, .reserved = 0 }, // [9]
    { .type = 0x06, .child_count = 2, .node_index = 10, .first_child = 0x000B, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 7, .param_count = 0, .reserved = 0 }, // [10]
    { .type = 0x80, .child_count = 0, .node_index = 11, .first_child = 0xFFFF, .next_sibling = 0x000C, .fn_index = 1, .param_offset = 7, .param_count = 1, .reserved = 0 }, // [11]
    { .type = 0x80, .child_count = 0, .node_index = 12, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 8, .param_count = 1, .reserved = 0 }, // [12]
    { .type = 0x09, .child_count = 0, .node_index = 13, .first_child = 0xFFFF, .next_sibling = 0x000E, .fn_index = 0, .param_offset = 9, .param_count = 0, .reserved = 0 }, // [13]
    { .type = 0x01, .child_count = 3, .node_index = 14, .first_child = 0x000F, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 9, .param_count = 0, .reserved = 0 }, // [14]
    { .type = 0xC0, .child_count = 0, .node_index = 15, .first_child = 0xFFFF, .next_sibling = 0x0010, .fn_index = 0, .param_offset = 9, .param_count = 0, .reserved = 0 }, // [15]
    { .type = 0xC0, .child_count = 0, .node_index = 16, .first_child = 0xFFFF, .next_sibling = 0x0011, .fn_index = 1, .param_offset = 9, .param_count = 3, .reserved = 0 }, // [16]
    { .type = 0x09, .child_count = 0, .node_index = 17, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [17]
    { .type = 0x03, .child_count = 3, .node_index = 18, .first_child = 0x0013, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [18]
    { .type = 0x07, .child_count = 2, .node_index = 19, .first_child = 0x0014, .next_sibling = 0x001A, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [19]
    { .type = 0x06, .child_count = 2, .node_index = 20, .first_child = 0x0015, .next_sibling = 0x0017, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [20]
    { .type = 0x80, .child_count = 0, .node_index = 21, .first_child = 0xFFFF, .next_sibling = 0x0016, .fn_index = 1, .param_offset = 12, .param_count = 1, .reserved = 0 }, // [21]
    { .type = 0x80, .child_count = 0, .node_index = 22, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 13, .param_count = 1, .reserved = 0 }, // [22]
    { .type = 0x06, .child_count = 2, .node_index = 23, .first_child = 0x0018, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 14, .param_count = 0, .reserved = 0 }, // [23]
    { .type = 0x80, .child_count = 0, .node_index = 24, .first_child = 0xFFFF, .next_sibling = 0x0019, .fn_index = 1, .param_offset = 14, .param_count = 1, .reserved = 0 }, // [24]
    { .type = 0x80, .child_count = 0, .node_index = 25, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 15, .param_count = 1, .reserved = 0 }, // [25]
    { .type = 0x01, .child_count = 3, .node_index = 26, .first_child = 0x001B, .next_sibling = 0x001E, .fn_index = 0, .param_offset = 16, .param_count = 0, .reserved = 0 }, // [26]
    { .type = 0xC0, .child_count = 0, .node_index = 27, .first_child = 0xFFFF, .next_sibling = 0x001C, .fn_index = 2, .param_offset = 16, .param_count = 0, .reserved = 0 }, // [27]
    { .type = 0xC0, .child_count = 0, .node_index = 28, .first_child = 0xFFFF, .next_sibling = 0x001D, .fn_index = 1, .param_offset = 16, .param_count = 3, .reserved = 0 }, // [28]
    { .type = 0x09, .child_count = 0, .node_index = 29, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 19, .param_count = 0, .reserved = 0 }, // [29]
    { .type = 0x09, .child_count = 0, .node_index = 30, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 19, .param_count = 0, .reserved = 0 }, // [30]
    { .type = 0x09, .child_count = 0, .node_index = 31, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 19, .param_count = 0, .reserved = 0 }, // [31]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_1_NODE_COUNT 32

// ============================================================================
// TREE: s_expression_test_2
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_2_params[] = {
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 12 },  // callable, offset to close: +12  // [0]
    { .type = S_EXPR_PARAM_PRED, .reserved = {0}, .func_idx = 2 },  // [1]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [2]
    { .type = S_EXPR_PARAM_PRED, .reserved = {0}, .func_idx = 3 },  // [3]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 0U },  // [4]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 1U },  // [5]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [6]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [7]
    { .type = S_EXPR_PARAM_PRED, .reserved = {0}, .func_idx = 3 },  // [8]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 2U },  // [9]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 3U },  // [10]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [11]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 12 },  // offset to open: -12  // [12]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 2 },  // [13]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 1 },  // [14]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_2_PARAM_COUNT 15

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_2_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 1, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [1]
    { .type = 0xC0, .child_count = 0, .node_index = 2, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 3, .param_offset = 0, .param_count = 15, .reserved = 0 }, // [2]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_2_NODE_COUNT 3

// ============================================================================
// TREE: s_expression_test_3
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_3_params[] = {
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [1]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [2]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [3]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 1 },  // [4]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 0U },  // [5]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [6]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [7]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [8]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 2 },  // [9]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [10]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [11]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 3 },  // [12]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 1U },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [14]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [15]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [16]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 4 },  // [17]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state  // [18]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [19]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 5 },  // [20]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 2U },  // [21]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 3U },  // [22]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [23]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 6 },  // [24]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 7 },  // [25]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_3_PARAM_COUNT 26

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_3_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 3, .param_offset = 0, .param_count = 2, .reserved = 2 }, // [1]
    { .type = 0x04, .child_count = 4, .node_index = 2, .first_child = 0x0003, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 2, .param_count = 0, .reserved = 0 }, // [2]
    { .type = 0x0B, .child_count = 2, .node_index = 3, .first_child = 0x0004, .next_sibling = 0x000D, .fn_index = 0, .param_offset = 2, .param_count = 0, .reserved = 0 }, // [3]
    { .type = 0x80, .child_count = 0, .node_index = 4, .first_child = 0xFFFF, .next_sibling = 0x0005, .fn_index = 4, .param_offset = 2, .param_count = 2, .reserved = 0 }, // [4]
    { .type = 0x01, .child_count = 7, .node_index = 5, .first_child = 0x0006, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 4, .param_count = 0, .reserved = 0 }, // [5]
    { .type = 0x40, .child_count = 0, .node_index = 6, .first_child = 0xFFFF, .next_sibling = 0x0007, .fn_index = 4, .param_offset = 4, .param_count = 1, .reserved = 0 }, // [6]
    { .type = 0x40, .child_count = 0, .node_index = 7, .first_child = 0xFFFF, .next_sibling = 0x0008, .fn_index = 1, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [7]
    { .type = 0x40, .child_count = 0, .node_index = 8, .first_child = 0xFFFF, .next_sibling = 0x0009, .fn_index = 5, .param_offset = 5, .param_count = 1, .reserved = 0 }, // [8]
    { .type = 0xC0, .child_count = 0, .node_index = 9, .first_child = 0xFFFF, .next_sibling = 0x000A, .fn_index = 4, .param_offset = 6, .param_count = 1, .reserved = 0 }, // [9]
    { .type = 0x40, .child_count = 0, .node_index = 10, .first_child = 0xFFFF, .next_sibling = 0x000B, .fn_index = 3, .param_offset = 7, .param_count = 2, .reserved = 0 }, // [10]
    { .type = 0x40, .child_count = 0, .node_index = 11, .first_child = 0xFFFF, .next_sibling = 0x000C, .fn_index = 4, .param_offset = 9, .param_count = 1, .reserved = 0 }, // [11]
    { .type = 0x09, .child_count = 0, .node_index = 12, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 8, .param_offset = 10, .param_count = 0, .reserved = 0 }, // [12]
    { .type = 0x0B, .child_count = 2, .node_index = 13, .first_child = 0x000E, .next_sibling = 0x0017, .fn_index = 0, .param_offset = 10, .param_count = 0, .reserved = 0 }, // [13]
    { .type = 0x80, .child_count = 0, .node_index = 14, .first_child = 0xFFFF, .next_sibling = 0x000F, .fn_index = 4, .param_offset = 10, .param_count = 2, .reserved = 0 }, // [14]
    { .type = 0x01, .child_count = 7, .node_index = 15, .first_child = 0x0010, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [15]
    { .type = 0x40, .child_count = 0, .node_index = 16, .first_child = 0xFFFF, .next_sibling = 0x0011, .fn_index = 4, .param_offset = 12, .param_count = 1, .reserved = 0 }, // [16]
    { .type = 0x40, .child_count = 0, .node_index = 17, .first_child = 0xFFFF, .next_sibling = 0x0012, .fn_index = 1, .param_offset = 13, .param_count = 0, .reserved = 0 }, // [17]
    { .type = 0x40, .child_count = 0, .node_index = 18, .first_child = 0xFFFF, .next_sibling = 0x0013, .fn_index = 5, .param_offset = 13, .param_count = 1, .reserved = 0 }, // [18]
    { .type = 0xC0, .child_count = 0, .node_index = 19, .first_child = 0xFFFF, .next_sibling = 0x0014, .fn_index = 4, .param_offset = 14, .param_count = 1, .reserved = 0 }, // [19]
    { .type = 0x40, .child_count = 0, .node_index = 20, .first_child = 0xFFFF, .next_sibling = 0x0015, .fn_index = 3, .param_offset = 15, .param_count = 2, .reserved = 0 }, // [20]
    { .type = 0x40, .child_count = 0, .node_index = 21, .first_child = 0xFFFF, .next_sibling = 0x0016, .fn_index = 4, .param_offset = 17, .param_count = 1, .reserved = 0 }, // [21]
    { .type = 0x09, .child_count = 0, .node_index = 22, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 8, .param_offset = 18, .param_count = 0, .reserved = 0 }, // [22]
    { .type = 0x0B, .child_count = 2, .node_index = 23, .first_child = 0x0018, .next_sibling = 0x0021, .fn_index = 0, .param_offset = 18, .param_count = 0, .reserved = 0 }, // [23]
    { .type = 0x80, .child_count = 0, .node_index = 24, .first_child = 0xFFFF, .next_sibling = 0x0019, .fn_index = 4, .param_offset = 18, .param_count = 2, .reserved = 0 }, // [24]
    { .type = 0x01, .child_count = 7, .node_index = 25, .first_child = 0x001A, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 20, .param_count = 0, .reserved = 0 }, // [25]
    { .type = 0x40, .child_count = 0, .node_index = 26, .first_child = 0xFFFF, .next_sibling = 0x001B, .fn_index = 4, .param_offset = 20, .param_count = 1, .reserved = 0 }, // [26]
    { .type = 0x40, .child_count = 0, .node_index = 27, .first_child = 0xFFFF, .next_sibling = 0x001C, .fn_index = 1, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [27]
    { .type = 0x40, .child_count = 0, .node_index = 28, .first_child = 0xFFFF, .next_sibling = 0x001D, .fn_index = 5, .param_offset = 21, .param_count = 1, .reserved = 0 }, // [28]
    { .type = 0x40, .child_count = 0, .node_index = 29, .first_child = 0xFFFF, .next_sibling = 0x001E, .fn_index = 5, .param_offset = 22, .param_count = 1, .reserved = 0 }, // [29]
    { .type = 0xC0, .child_count = 0, .node_index = 30, .first_child = 0xFFFF, .next_sibling = 0x001F, .fn_index = 4, .param_offset = 23, .param_count = 1, .reserved = 0 }, // [30]
    { .type = 0x40, .child_count = 0, .node_index = 31, .first_child = 0xFFFF, .next_sibling = 0x0020, .fn_index = 4, .param_offset = 24, .param_count = 1, .reserved = 0 }, // [31]
    { .type = 0x09, .child_count = 0, .node_index = 32, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 5, .param_offset = 25, .param_count = 0, .reserved = 0 }, // [32]
    { .type = 0x0B, .child_count = 1, .node_index = 33, .first_child = 0x0022, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 25, .param_count = 0, .reserved = 1 }, // [33]
    { .type = 0x40, .child_count = 0, .node_index = 34, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 6, .param_offset = 25, .param_count = 1, .reserved = 0 }, // [34]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_3_NODE_COUNT 35

// ============================================================================
// TREE: s_expression_test_4
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_4_params[] = {
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state_b  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [1]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state_b  // [2]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 19 },  // callable, offset to close: +19  // [3]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [4]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [5]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 1 },  // [6]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [7]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [8]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 5 },  // [9]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 0U },  // [10]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [11]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [12]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [14]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [15]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [16]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 7 },  // [17]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state_b  // [18]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [19]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [20]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [21]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 19 },  // offset to open: -19  // [22]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 19 },  // callable, offset to close: +19  // [23]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [24]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [25]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 1 },  // [26]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [27]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [28]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 5 },  // [29]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 1U },  // [30]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [31]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [32]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [33]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [34]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [35]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [36]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 7 },  // [37]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // test_30_state_machine_state_b  // [38]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [39]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [40]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [41]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 19 },  // offset to open: -19  // [42]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 18 },  // callable, offset to close: +18  // [43]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [44]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [45]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 1 },  // [46]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [47]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [48]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 5 },  // [49]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 2U },  // [50]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [51]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [52]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 5 },  // [53]
    { .type = S_EXPR_PARAM_UINT, .reserved = {0}, .u = 3U },  // [54]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [55]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [56]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [57]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [58]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [59]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [60]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 18 },  // offset to open: -18  // [61]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_4_PARAM_COUNT 62

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_4_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 3, .param_offset = 0, .param_count = 2, .reserved = 2 }, // [1]
    { .type = 0xC0, .child_count = 0, .node_index = 2, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 5, .param_offset = 2, .param_count = 60, .reserved = 0 }, // [2]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_4_NODE_COUNT 3

// ============================================================================
// TREE: s_expression_test_5
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_5_params[] = {
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [1]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [2]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [3]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 8 },  // [4]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [5]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [6]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [7]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [8]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [9]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [10]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [11]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [12]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 9 },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [14]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -100 },  // [15]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [16]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -100 },  // [17]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [18]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [19]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [20]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [21]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 10 },  // [22]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [23]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -50 },  // [24]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [25]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [26]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 25 },  // [27]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [28]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 4 },  // [29]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 4 },  // [30]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 11 },  // [31]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [32]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [33]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [34]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -50 },  // [35]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 25 },  // [36]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [37]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [38]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [39]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 12 },  // [40]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [41]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [42]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [43]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [44]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 13 },  // [45]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 14 },  // [46]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_5_PARAM_COUNT 47

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_5_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 7, .param_offset = 0, .param_count = 2, .reserved = 2 }, // [1]
    { .type = 0x05, .child_count = 6, .node_index = 2, .first_child = 0x0003, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 2, .param_count = 1, .reserved = 0 }, // [2]
    { .type = 0x0C, .child_count = 1, .node_index = 3, .first_child = 0x0004, .next_sibling = 0x000B, .fn_index = 0, .param_offset = 3, .param_count = 1, .reserved = 0 }, // [3]
    { .type = 0x01, .child_count = 6, .node_index = 4, .first_child = 0x0005, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 4, .param_count = 0, .reserved = 0 }, // [4]
    { .type = 0x40, .child_count = 0, .node_index = 5, .first_child = 0xFFFF, .next_sibling = 0x0006, .fn_index = 4, .param_offset = 4, .param_count = 1, .reserved = 0 }, // [5]
    { .type = 0x40, .child_count = 0, .node_index = 6, .first_child = 0xFFFF, .next_sibling = 0x0007, .fn_index = 8, .param_offset = 5, .param_count = 2, .reserved = 0 }, // [6]
    { .type = 0x40, .child_count = 0, .node_index = 7, .first_child = 0xFFFF, .next_sibling = 0x0008, .fn_index = 8, .param_offset = 7, .param_count = 2, .reserved = 0 }, // [7]
    { .type = 0xC0, .child_count = 0, .node_index = 8, .first_child = 0xFFFF, .next_sibling = 0x0009, .fn_index = 4, .param_offset = 9, .param_count = 1, .reserved = 0 }, // [8]
    { .type = 0xC0, .child_count = 0, .node_index = 9, .first_child = 0xFFFF, .next_sibling = 0x000A, .fn_index = 8, .param_offset = 10, .param_count = 2, .reserved = 0 }, // [9]
    { .type = 0x09, .child_count = 0, .node_index = 10, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [10]
    { .type = 0x0C, .child_count = 1, .node_index = 11, .first_child = 0x000C, .next_sibling = 0x0013, .fn_index = 0, .param_offset = 12, .param_count = 1, .reserved = 0 }, // [11]
    { .type = 0x01, .child_count = 6, .node_index = 12, .first_child = 0x000D, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 13, .param_count = 0, .reserved = 0 }, // [12]
    { .type = 0x40, .child_count = 0, .node_index = 13, .first_child = 0xFFFF, .next_sibling = 0x000E, .fn_index = 4, .param_offset = 13, .param_count = 1, .reserved = 0 }, // [13]
    { .type = 0x40, .child_count = 0, .node_index = 14, .first_child = 0xFFFF, .next_sibling = 0x000F, .fn_index = 8, .param_offset = 14, .param_count = 2, .reserved = 0 }, // [14]
    { .type = 0x40, .child_count = 0, .node_index = 15, .first_child = 0xFFFF, .next_sibling = 0x0010, .fn_index = 8, .param_offset = 16, .param_count = 2, .reserved = 0 }, // [15]
    { .type = 0xC0, .child_count = 0, .node_index = 16, .first_child = 0xFFFF, .next_sibling = 0x0011, .fn_index = 4, .param_offset = 18, .param_count = 1, .reserved = 0 }, // [16]
    { .type = 0xC0, .child_count = 0, .node_index = 17, .first_child = 0xFFFF, .next_sibling = 0x0012, .fn_index = 8, .param_offset = 19, .param_count = 2, .reserved = 0 }, // [17]
    { .type = 0x09, .child_count = 0, .node_index = 18, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [18]
    { .type = 0x0C, .child_count = 1, .node_index = 19, .first_child = 0x0014, .next_sibling = 0x001B, .fn_index = 0, .param_offset = 21, .param_count = 1, .reserved = 0 }, // [19]
    { .type = 0x01, .child_count = 6, .node_index = 20, .first_child = 0x0015, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 22, .param_count = 0, .reserved = 0 }, // [20]
    { .type = 0x40, .child_count = 0, .node_index = 21, .first_child = 0xFFFF, .next_sibling = 0x0016, .fn_index = 4, .param_offset = 22, .param_count = 1, .reserved = 0 }, // [21]
    { .type = 0x40, .child_count = 0, .node_index = 22, .first_child = 0xFFFF, .next_sibling = 0x0017, .fn_index = 8, .param_offset = 23, .param_count = 2, .reserved = 0 }, // [22]
    { .type = 0x40, .child_count = 0, .node_index = 23, .first_child = 0xFFFF, .next_sibling = 0x0018, .fn_index = 8, .param_offset = 25, .param_count = 2, .reserved = 0 }, // [23]
    { .type = 0xC0, .child_count = 0, .node_index = 24, .first_child = 0xFFFF, .next_sibling = 0x0019, .fn_index = 4, .param_offset = 27, .param_count = 1, .reserved = 0 }, // [24]
    { .type = 0xC0, .child_count = 0, .node_index = 25, .first_child = 0xFFFF, .next_sibling = 0x001A, .fn_index = 8, .param_offset = 28, .param_count = 2, .reserved = 0 }, // [25]
    { .type = 0x09, .child_count = 0, .node_index = 26, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 30, .param_count = 0, .reserved = 0 }, // [26]
    { .type = 0x0C, .child_count = 1, .node_index = 27, .first_child = 0x001C, .next_sibling = 0x0023, .fn_index = 0, .param_offset = 30, .param_count = 1, .reserved = 0 }, // [27]
    { .type = 0x01, .child_count = 6, .node_index = 28, .first_child = 0x001D, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 31, .param_count = 0, .reserved = 0 }, // [28]
    { .type = 0x40, .child_count = 0, .node_index = 29, .first_child = 0xFFFF, .next_sibling = 0x001E, .fn_index = 4, .param_offset = 31, .param_count = 1, .reserved = 0 }, // [29]
    { .type = 0x40, .child_count = 0, .node_index = 30, .first_child = 0xFFFF, .next_sibling = 0x001F, .fn_index = 8, .param_offset = 32, .param_count = 2, .reserved = 0 }, // [30]
    { .type = 0x40, .child_count = 0, .node_index = 31, .first_child = 0xFFFF, .next_sibling = 0x0020, .fn_index = 8, .param_offset = 34, .param_count = 2, .reserved = 0 }, // [31]
    { .type = 0xC0, .child_count = 0, .node_index = 32, .first_child = 0xFFFF, .next_sibling = 0x0021, .fn_index = 4, .param_offset = 36, .param_count = 1, .reserved = 0 }, // [32]
    { .type = 0xC0, .child_count = 0, .node_index = 33, .first_child = 0xFFFF, .next_sibling = 0x0022, .fn_index = 8, .param_offset = 37, .param_count = 2, .reserved = 0 }, // [33]
    { .type = 0x09, .child_count = 0, .node_index = 34, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 39, .param_count = 0, .reserved = 0 }, // [34]
    { .type = 0x0C, .child_count = 1, .node_index = 35, .first_child = 0x0024, .next_sibling = 0x0029, .fn_index = 0, .param_offset = 39, .param_count = 1, .reserved = 0 }, // [35]
    { .type = 0x01, .child_count = 4, .node_index = 36, .first_child = 0x0025, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 40, .param_count = 0, .reserved = 0 }, // [36]
    { .type = 0x40, .child_count = 0, .node_index = 37, .first_child = 0xFFFF, .next_sibling = 0x0026, .fn_index = 4, .param_offset = 40, .param_count = 1, .reserved = 0 }, // [37]
    { .type = 0x40, .child_count = 0, .node_index = 38, .first_child = 0xFFFF, .next_sibling = 0x0027, .fn_index = 8, .param_offset = 41, .param_count = 2, .reserved = 0 }, // [38]
    { .type = 0x40, .child_count = 0, .node_index = 39, .first_child = 0xFFFF, .next_sibling = 0x0028, .fn_index = 8, .param_offset = 43, .param_count = 2, .reserved = 0 }, // [39]
    { .type = 0x09, .child_count = 0, .node_index = 40, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 5, .param_offset = 45, .param_count = 0, .reserved = 0 }, // [40]
    { .type = 0x0C, .child_count = 1, .node_index = 41, .first_child = 0x002A, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 45, .param_count = 0, .reserved = 1 }, // [41]
    { .type = 0x01, .child_count = 3, .node_index = 42, .first_child = 0x002B, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 45, .param_count = 0, .reserved = 0 }, // [42]
    { .type = 0x40, .child_count = 0, .node_index = 43, .first_child = 0xFFFF, .next_sibling = 0x002C, .fn_index = 4, .param_offset = 45, .param_count = 1, .reserved = 0 }, // [43]
    { .type = 0x40, .child_count = 0, .node_index = 44, .first_child = 0xFFFF, .next_sibling = 0x002D, .fn_index = 4, .param_offset = 46, .param_count = 1, .reserved = 0 }, // [44]
    { .type = 0x09, .child_count = 0, .node_index = 45, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 2, .param_offset = 47, .param_count = 0, .reserved = 0 }, // [45]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_5_NODE_COUNT 46

// ============================================================================
// TREE: s_expression_test_6
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_6_params[] = {
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60929 },  // [0]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 15 },  // [1]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60930 },  // [2]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 16 },  // [3]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // timer_count  // [4]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 10 },  // [5]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [6]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60931 },  // [7]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 17 },  // [8]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // sensor_value  // [9]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [10]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60932 },  // [11]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 18 },  // [12]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [14]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 19 },  // [15]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60933 },  // [16]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [17]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 20 },  // [18]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60933 },  // [19]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 21 },  // [20]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // event_id  // [21]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_6_PARAM_COUNT 22

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_6_nodes[] = {
    { .type = 0x01, .child_count = 1, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x05, .child_count = 6, .node_index = 1, .first_child = 0x0002, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 4 }, // [1]
    { .type = 0x0C, .child_count = 1, .node_index = 2, .first_child = 0x0003, .next_sibling = 0x0007, .fn_index = 0, .param_offset = 0, .param_count = 1, .reserved = 0 }, // [2]
    { .type = 0x01, .child_count = 3, .node_index = 3, .first_child = 0x0004, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 1, .param_count = 0, .reserved = 0 }, // [3]
    { .type = 0x40, .child_count = 0, .node_index = 4, .first_child = 0xFFFF, .next_sibling = 0x0005, .fn_index = 4, .param_offset = 1, .param_count = 1, .reserved = 0 }, // [4]
    { .type = 0xC0, .child_count = 0, .node_index = 5, .first_child = 0xFFFF, .next_sibling = 0x0006, .fn_index = 9, .param_offset = 2, .param_count = 0, .reserved = 0 }, // [5]
    { .type = 0x09, .child_count = 0, .node_index = 6, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 2, .param_count = 0, .reserved = 0 }, // [6]
    { .type = 0x0C, .child_count = 1, .node_index = 7, .first_child = 0x0008, .next_sibling = 0x000D, .fn_index = 0, .param_offset = 2, .param_count = 1, .reserved = 0 }, // [7]
    { .type = 0x01, .child_count = 4, .node_index = 8, .first_child = 0x0009, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 3, .param_count = 0, .reserved = 0 }, // [8]
    { .type = 0x40, .child_count = 0, .node_index = 9, .first_child = 0xFFFF, .next_sibling = 0x000A, .fn_index = 4, .param_offset = 3, .param_count = 1, .reserved = 0 }, // [9]
    { .type = 0xC0, .child_count = 0, .node_index = 10, .first_child = 0xFFFF, .next_sibling = 0x000B, .fn_index = 10, .param_offset = 4, .param_count = 2, .reserved = 0 }, // [10]
    { .type = 0x40, .child_count = 0, .node_index = 11, .first_child = 0xFFFF, .next_sibling = 0x000C, .fn_index = 9, .param_offset = 6, .param_count = 1, .reserved = 0 }, // [11]
    { .type = 0x09, .child_count = 0, .node_index = 12, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 7, .param_count = 0, .reserved = 0 }, // [12]
    { .type = 0x0C, .child_count = 1, .node_index = 13, .first_child = 0x000E, .next_sibling = 0x0012, .fn_index = 0, .param_offset = 7, .param_count = 1, .reserved = 0 }, // [13]
    { .type = 0x01, .child_count = 3, .node_index = 14, .first_child = 0x000F, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 8, .param_count = 0, .reserved = 0 }, // [14]
    { .type = 0x40, .child_count = 0, .node_index = 15, .first_child = 0xFFFF, .next_sibling = 0x0010, .fn_index = 4, .param_offset = 8, .param_count = 1, .reserved = 0 }, // [15]
    { .type = 0xC0, .child_count = 0, .node_index = 16, .first_child = 0xFFFF, .next_sibling = 0x0011, .fn_index = 11, .param_offset = 9, .param_count = 2, .reserved = 0 }, // [16]
    { .type = 0x09, .child_count = 0, .node_index = 17, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 11, .param_count = 0, .reserved = 0 }, // [17]
    { .type = 0x0C, .child_count = 1, .node_index = 18, .first_child = 0x0013, .next_sibling = 0x001B, .fn_index = 0, .param_offset = 11, .param_count = 1, .reserved = 0 }, // [18]
    { .type = 0x01, .child_count = 7, .node_index = 19, .first_child = 0x0014, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 12, .param_count = 0, .reserved = 0 }, // [19]
    { .type = 0x40, .child_count = 0, .node_index = 20, .first_child = 0xFFFF, .next_sibling = 0x0015, .fn_index = 4, .param_offset = 12, .param_count = 1, .reserved = 0 }, // [20]
    { .type = 0x40, .child_count = 0, .node_index = 21, .first_child = 0xFFFF, .next_sibling = 0x0016, .fn_index = 10, .param_offset = 13, .param_count = 0, .reserved = 0 }, // [21]
    { .type = 0x40, .child_count = 0, .node_index = 22, .first_child = 0xFFFF, .next_sibling = 0x0017, .fn_index = 11, .param_offset = 13, .param_count = 2, .reserved = 0 }, // [22]
    { .type = 0x40, .child_count = 0, .node_index = 23, .first_child = 0xFFFF, .next_sibling = 0x0018, .fn_index = 12, .param_offset = 15, .param_count = 1, .reserved = 0 }, // [23]
    { .type = 0x40, .child_count = 0, .node_index = 24, .first_child = 0xFFFF, .next_sibling = 0x0019, .fn_index = 13, .param_offset = 16, .param_count = 2, .reserved = 0 }, // [24]
    { .type = 0x40, .child_count = 0, .node_index = 25, .first_child = 0xFFFF, .next_sibling = 0x001A, .fn_index = 4, .param_offset = 18, .param_count = 1, .reserved = 0 }, // [25]
    { .type = 0x09, .child_count = 0, .node_index = 26, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 19, .param_count = 0, .reserved = 0 }, // [26]
    { .type = 0x0C, .child_count = 1, .node_index = 27, .first_child = 0x001C, .next_sibling = 0x0021, .fn_index = 0, .param_offset = 19, .param_count = 1, .reserved = 0 }, // [27]
    { .type = 0x01, .child_count = 4, .node_index = 28, .first_child = 0x001D, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 20, .param_count = 0, .reserved = 0 }, // [28]
    { .type = 0x40, .child_count = 0, .node_index = 29, .first_child = 0xFFFF, .next_sibling = 0x001E, .fn_index = 4, .param_offset = 20, .param_count = 1, .reserved = 0 }, // [29]
    { .type = 0x40, .child_count = 0, .node_index = 30, .first_child = 0xFFFF, .next_sibling = 0x001F, .fn_index = 14, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [30]
    { .type = 0x40, .child_count = 0, .node_index = 31, .first_child = 0xFFFF, .next_sibling = 0x0020, .fn_index = 15, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [31]
    { .type = 0x09, .child_count = 0, .node_index = 32, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 5, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [32]
    { .type = 0x0C, .child_count = 1, .node_index = 33, .first_child = 0x0022, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 21, .param_count = 0, .reserved = 1 }, // [33]
    { .type = 0x01, .child_count = 3, .node_index = 34, .first_child = 0x0023, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 21, .param_count = 0, .reserved = 0 }, // [34]
    { .type = 0xC0, .child_count = 0, .node_index = 35, .first_child = 0xFFFF, .next_sibling = 0x0024, .fn_index = 12, .param_offset = 21, .param_count = 1, .reserved = 0 }, // [35]
    { .type = 0xC0, .child_count = 0, .node_index = 36, .first_child = 0xFFFF, .next_sibling = 0x0025, .fn_index = 13, .param_offset = 22, .param_count = 0, .reserved = 0 }, // [36]
    { .type = 0x09, .child_count = 0, .node_index = 37, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 22, .param_count = 0, .reserved = 0 }, // [37]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_6_NODE_COUNT 38

// ============================================================================
// TREE: s_expression_test_7
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_7_params[] = {
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [1]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [2]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 29 },  // offset to close: +29  // [3]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [4]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 26 },  // callable, offset to close: +26  // [5]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [6]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [7]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [8]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 8 },  // [9]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [10]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [11]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [12]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [13]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [14]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [15]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [16]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [17]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [18]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 100 },  // [19]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [20]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [21]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [22]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [23]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [24]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [25]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 8 },  // [26]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [27]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [28]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [29]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [30]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 26 },  // offset to open: -26  // [31]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 29 },  // offset to open: -29  // [32]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 29 },  // offset to close: +29  // [33]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [34]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 26 },  // callable, offset to close: +26  // [35]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [36]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [37]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [38]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 9 },  // [39]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [40]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [41]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [42]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [43]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -100 },  // [44]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [45]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [46]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [47]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [48]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -100 },  // [49]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [50]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [51]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [52]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [53]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [54]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [55]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 8 },  // [56]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [57]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [58]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [59]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [60]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 26 },  // offset to open: -26  // [61]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 29 },  // offset to open: -29  // [62]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 29 },  // offset to close: +29  // [63]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [64]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 26 },  // callable, offset to close: +26  // [65]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [66]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [67]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [68]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 10 },  // [69]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [70]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [71]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [72]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [73]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -50 },  // [74]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [75]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [76]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [77]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [78]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [79]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [80]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [81]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [82]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 25 },  // [83]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [84]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [85]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 8 },  // [86]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [87]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 4 },  // [88]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [89]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [90]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 26 },  // offset to open: -26  // [91]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 29 },  // offset to open: -29  // [92]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 29 },  // offset to close: +29  // [93]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 4 },  // [94]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 26 },  // callable, offset to close: +26  // [95]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [96]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [97]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [98]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 11 },  // [99]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [100]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [101]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [102]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [103]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [104]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [105]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [106]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [107]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [108]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = -50 },  // [109]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [110]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [111]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 4 },  // [112]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 25 },  // [113]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [114]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [115]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 8 },  // [116]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // robot_command  // [117]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [118]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [119]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 8 },  // [120]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 26 },  // offset to open: -26  // [121]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 29 },  // offset to open: -29  // [122]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 20 },  // offset to close: +20  // [123]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [124]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 17 },  // callable, offset to close: +17  // [125]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [126]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [127]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [128]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 12 },  // [129]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [130]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [131]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [132]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [133]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [134]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [135]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [136]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 8 },  // [137]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [138]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [139]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [140]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [141]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 17 },  // offset to open: -17  // [142]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 20 },  // offset to open: -20  // [143]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 10 },  // offset to close: +10  // [144]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [145]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 7 },  // callable, offset to close: +7  // [146]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [147]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [148]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [149]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 22 },  // [150]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [151]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [152]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 7 },  // offset to open: -7  // [153]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 10 },  // offset to open: -10  // [154]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_7_PARAM_COUNT 155

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_7_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x40, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0x0002, .fn_index = 7, .param_offset = 0, .param_count = 2, .reserved = 2 }, // [1]
    { .type = 0xC0, .child_count = 0, .node_index = 2, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 14, .param_offset = 2, .param_count = 153, .reserved = 0 }, // [2]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_7_NODE_COUNT 3

// ============================================================================
// TREE: s_expression_test_8
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_8_params[] = {
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 13 },  // offset to close: +13  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60929 },  // [1]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 10 },  // callable, offset to close: +10  // [2]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [3]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [4]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [5]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 15 },  // [6]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [7]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [8]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 9 },  // [9]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [10]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [11]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 10 },  // offset to open: -10  // [12]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 13 },  // offset to open: -13  // [13]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 19 },  // offset to close: +19  // [14]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60930 },  // [15]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 16 },  // callable, offset to close: +16  // [16]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [17]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [18]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [19]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 16 },  // [20]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [21]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [22]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 10 },  // [23]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // timer_count  // [24]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 10 },  // [25]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [26]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [27]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 9 },  // [28]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [29]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [30]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [31]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 16 },  // offset to open: -16  // [32]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 19 },  // offset to open: -19  // [33]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 15 },  // offset to close: +15  // [34]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60931 },  // [35]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 12 },  // callable, offset to close: +12  // [36]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [37]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [38]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [39]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 17 },  // [40]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [41]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [42]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 11 },  // [43]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // sensor_value  // [44]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 50 },  // [45]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [46]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [47]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 12 },  // offset to open: -12  // [48]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 15 },  // offset to open: -15  // [49]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 31 },  // offset to close: +31  // [50]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60932 },  // [51]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 28 },  // callable, offset to close: +28  // [52]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [53]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [54]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [55]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 18 },  // [56]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [57]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [58]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 10 },  // [59]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [60]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [61]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 11 },  // [62]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [63]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [64]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [65]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [66]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 12 },  // [67]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 19 },  // [68]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [69]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 4 },  // callable, offset to close: +4  // [70]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 13 },  // [71]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60933 },  // [72]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [73]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 4 },  // offset to open: -4  // [74]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [75]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [76]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 20 },  // [77]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [78]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [79]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 28 },  // offset to open: -28  // [80]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 31 },  // offset to open: -31  // [81]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 16 },  // offset to close: +16  // [82]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 60933 },  // [83]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 13 },  // callable, offset to close: +13  // [84]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [85]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [86]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 4 },  // [87]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 21 },  // [88]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [89]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [90]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 14 },  // [91]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [92]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [93]
    { .type = S_EXPR_PARAM_ONESHOT, .reserved = {0}, .func_idx = 15 },  // [94]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [95]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 5 },  // [96]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 13 },  // offset to open: -13  // [97]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 16 },  // offset to open: -16  // [98]
    { .type = S_EXPR_PARAM_OPEN, .reserved = {0}, .brace_idx = 13 },  // offset to close: +13  // [99]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [100]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 10 },  // callable, offset to close: +10  // [101]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 6 },  // [102]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 3 },  // callable, offset to close: +3  // [103]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 12 },  // [104]
    { .type = S_EXPR_PARAM_SLOT, .reserved = {0}, .slot = { .pool_id = 0, .slot_index = 0 } },  // event_id  // [105]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 3 },  // offset to open: -3  // [106]
    { .type = S_EXPR_PARAM_OPEN_CALL, .reserved = {0}, .brace_idx = 2 },  // callable, offset to close: +2  // [107]
    { .type = S_EXPR_PARAM_MAIN, .reserved = {0}, .func_idx = 13 },  // [108]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 2 },  // offset to open: -2  // [109]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [110]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 10 },  // offset to open: -10  // [111]
    { .type = S_EXPR_PARAM_CLOSE, .reserved = {0}, .brace_idx = 13 },  // offset to open: -13  // [112]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_8_PARAM_COUNT 113

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_8_nodes[] = {
    { .type = 0x01, .child_count = 1, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0xC0, .child_count = 0, .node_index = 1, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 15, .param_offset = 0, .param_count = 113, .reserved = 0 }, // [1]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_8_NODE_COUNT 2

// ============================================================================
// TREE DEFINITIONS
// ============================================================================

static const s_expr_tree_def_t chain_flow_dsl_tests_trees[] = {
    {
        .name = "s_expression_test_1",
        .nodes = chain_flow_dsl_tests_s_expression_test_1_nodes,
        .node_count = 32,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_1_params,
        .param_count = 19,
    },
    {
        .name = "s_expression_test_2",
        .nodes = chain_flow_dsl_tests_s_expression_test_2_nodes,
        .node_count = 3,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_2_params,
        .param_count = 15,
    },
    {
        .name = "s_expression_test_3",
        .nodes = chain_flow_dsl_tests_s_expression_test_3_nodes,
        .node_count = 35,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_3_params,
        .param_count = 26,
    },
    {
        .name = "s_expression_test_4",
        .nodes = chain_flow_dsl_tests_s_expression_test_4_nodes,
        .node_count = 3,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_4_params,
        .param_count = 62,
    },
    {
        .name = "s_expression_test_5",
        .nodes = chain_flow_dsl_tests_s_expression_test_5_nodes,
        .node_count = 46,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_5_params,
        .param_count = 47,
    },
    {
        .name = "s_expression_test_6",
        .nodes = chain_flow_dsl_tests_s_expression_test_6_nodes,
        .node_count = 38,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_6_params,
        .param_count = 22,
    },
    {
        .name = "s_expression_test_7",
        .nodes = chain_flow_dsl_tests_s_expression_test_7_nodes,
        .node_count = 3,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_7_params,
        .param_count = 155,
    },
    {
        .name = "s_expression_test_8",
        .nodes = chain_flow_dsl_tests_s_expression_test_8_nodes,
        .node_count = 2,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_8_params,
        .param_count = 113,
    },
};
#define CHAIN_FLOW_DSL_TESTS_TREE_COUNT 8

// ============================================================================
// MODULE DEFINITION
// ============================================================================

static const s_expr_module_def_t chain_flow_dsl_tests_module = {
    .name = "chain_flow_dsl_tests",
    .trees = chain_flow_dsl_tests_trees,
    .tree_count = 8,
    .is_64bit = false,

    .oneshot_names = chain_flow_dsl_tests_oneshot_names,
    .boolean_names = chain_flow_dsl_tests_boolean_names,
    .main_names = chain_flow_dsl_tests_main_names,
    .strings = chain_flow_dsl_tests_strings,

    .oneshot_count = 16,
    .boolean_count = 5,
    .main_count = 16,
    .string_count = 23,

    .max_node_count = 46,
    .max_m_call_count = 30,
};

#ifdef __cplusplus
}
#endif

#endif // CHAIN_FLOW_DSL_TESTS_MODULE_H
