/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_FUNCTIONS_H
#define TEST_HEADER_FUNCTIONS_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "chaintree_support.h"

/* Main function enum */
typedef enum {
    MAIN_FUNC_CFL_NULL = 0,
    MAIN_FUNC_CFL_COLUMN_MAIN = 1,
    MAIN_FUNC_CFL_DISABLE = 2,
    MAIN_FUNC_CFL_GATE_NODE_MAIN = 3,
    MAIN_FUNC_CFL_HALT = 4,
    MAIN_FUNC_CFL_RESET = 5,
    MAIN_FUNC_CFL_TERMINATE = 6,
    MAIN_FUNC_CFL_TERMINATE_SYSTEM = 7,
    MAIN_FUNC_CFL_VERIFY = 8,
    MAIN_FUNC_CFL_WAIT = 9,
    MAIN_FUNC_CFL_WAIT_TIME = 10,
    MAIN_FUNC_COUNT = 11
} MAIN_FUNC_t;

/* One-shot function enum */
typedef enum {
    ONE_SHOT_FUNC_CFL_NULL = 0,
    ONE_SHOT_FUNC_ACTIVATE_VALVE = 1,
    ONE_SHOT_FUNC_CFL_COLUMN_INIT = 2,
    ONE_SHOT_FUNC_CFL_COLUMN_TERM = 3,
    ONE_SHOT_FUNC_CFL_GATE_NODE_INIT = 4,
    ONE_SHOT_FUNC_CFL_GATE_NODE_TERM = 5,
    ONE_SHOT_FUNC_CFL_LOG_MESSAGE = 6,
    ONE_SHOT_FUNC_CFL_SEND_NAMED_EVENT = 7,
    ONE_SHOT_FUNC_CFL_VERIFY_INIT = 8,
    ONE_SHOT_FUNC_CFL_VERIFY_TERM = 9,
    ONE_SHOT_FUNC_CFL_WAIT_INIT = 10,
    ONE_SHOT_FUNC_CFL_WAIT_TERM = 11,
    ONE_SHOT_FUNC_CFL_WAIT_TIME_INIT = 12,
    ONE_SHOT_FUNC_COUNT = 13
} ONE_SHOT_FUNC_t;

/* Boolean function enum */
typedef enum {
    BOOL_FUNC_CFL_NULL = 0,
    BOOL_FUNC_CFL_BOOL_FALSE = 1,
    BOOL_FUNC_CFL_COLUMN_NULL = 2,
    BOOL_FUNC_CFL_GATE_NODE_NULL = 3,
    BOOL_FUNC_CFL_VERIFY_TIME_OUT = 4,
    BOOL_FUNC_CFL_WAIT_FOR_EVENT = 5,
    BOOL_FUNC_COUNT = 6
} BOOL_FUNC_t;

/* Function pointer arrays */
extern const main_function_t ct_vycdt4q2_main_functions[11];
extern const one_shot_function_t ct_vycdt4q2_one_shot_functions[13];
extern const boolean_function_t ct_vycdt4q2_boolean_functions[6];

/* Main function usage count (indexed by function enum) */
extern const uint16_t ct_vycdt4q2_main_function_usage_count[11];

/* Function name arrays (for debugging) */
extern const char *ct_vycdt4q2_main_function_names[11];
extern const char *ct_vycdt4q2_one_shot_function_names[13];
extern const char *ct_vycdt4q2_boolean_function_names[6];

#endif /* TEST_HEADER_FUNCTIONS_H */