#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/* =========================================================================
 * 1. ENUMERATIONS & CONSTANTS
 * ========================================================================= */

// Logic Merge Rules for Bitspaces
typedef enum {
    MERGE_OR = 0,       // Parent = Child A | Child B
    MERGE_AND,          // Parent = Child A & Child B
    MERGE_PRIORITY      // Parent = Max(Child A, Child B)
} merge_op_t;

// JSON Data Types for Config
typedef enum { 
    JSON_TYPE_STRING_HASH, 
    JSON_TYPE_INT32, 
    JSON_TYPE_UINT32,
    JSON_TYPE_FLOAT32, 
    JSON_TYPE_NULL, 
    JSON_TYPE_BOOL, 
    JSON_TYPE_ARRAY, 
    JSON_TYPE_OBJECT 
} json_type_t;

/* =========================================================================
 * 2. ROM DATA STRUCTURES (The "Blueprint")
 * These structs map to the static arrays generated by Lua.
 * ========================================================================= */

// A. Logic Rules
typedef struct {
    merge_op_t op;
} bitspace_rule_t;

// B. Node Topology & Memory Layout
typedef struct {
    uint32_t hash;           // FNV-1a Hash of the path ("Plant.Line1")
    
    // Topology (Indices into the layout array)
    int16_t  parent_idx;       // -1 if Root
    int16_t  first_child_idx;  // -1 if Leaf
    int16_t  next_sibling_idx; // -1 if Last Child
    
    // Memory Offsets
    // Points to a slice in the massive static offsets array.
    // Index [0] = Offset for Bitspace 0, [1] for Bitspace 1, etc.
    const int32_t* offsets; 
} node_layout_t;

// C. Configuration Records
typedef struct {
    uint32_t hash;
    uint32_t rec_idx;
} json_path_index_t;

typedef struct {
    json_type_t type;
    union {
        uint32_t hash32;
        int32_t  i32_value;
        float    f32_value;
        uint8_t  bool_value;
        uint32_t container_count;
    } value;
} json_record_t;

// D. THE DESCRIPTOR (The Public Handle)
// This struct bundles all the static data for a specific Schema.
typedef struct {
    const char* schema_name;
    
    // Bitspace Definitions
    uint32_t               bitspace_count; 
    const uint32_t* arena_sizes;    // Array[bitspace_count]
    const bitspace_rule_t* rules;          // Array[bitspace_count]
    
    // Node Topology
    const node_layout_t* layouts;
    uint32_t             layout_count;
    
    // Config Data
    const json_record_t* cfg_recs;
    const json_path_index_t* cfg_index;
    uint32_t                 cfg_index_len;
} chain_desc_t;

/* =========================================================================
 * 3. RAM DATA STRUCTURES (The Runtime Instance)
 * This holds the actual state (bits) for one instance of a tree.
 * ========================================================================= */

// Opaque handle for the user's system allocator
typedef void* sys_handle_t;

typedef struct {
    sys_handle_t        sys_h;  // User allocator context
    const chain_desc_t* desc;   // Pointer to the ROM Blueprint
    
    // Dynamic array of pointers.
    // arenas[0] -> Points to STATE memory block
    // arenas[1] -> Points to ALARM memory block
    uint8_t** arenas; 
} chain_tree_t;

/* =========================================================================
 * 4. PUBLIC API
 * ========================================================================= */

// --- Lifecycle ---

// Initialize a tree instance. Allocates memory based on desc->arena_sizes.
void chain_tree_init(chain_tree_t* tree, const chain_desc_t* desc, sys_handle_t sys_h);

// Frees all allocated memory.
void chain_tree_destroy(chain_tree_t* tree);


// --- Runtime Access ---

// Get a pointer to the raw byte(s) for a specific node and bank.
// Returns NULL if path doesn't exist or node doesn't use that bank.
uint8_t* chain_get_bits(chain_tree_t* tree, int bank_id, const char* fmt, ...);

// Set or Clear a specific bit and TRIGGER the Logic Engine.
// This will update the bit and recursively update parents based on merge rules.
void chain_set_bit(chain_tree_t* tree, int bank_id, int bit_idx, bool val, const char* fmt, ...);


// --- External Dependencies (User Provided) ---

// You must implement these in your application code.
extern void* alloc(sys_handle_t h, size_t sz);
extern void  free(sys_handle_t h);