// ============================================================================
// s_expr_dsl_test_debug.h
// DEBUG INFORMATION - Auto-generated by s_expr_dsl.lua v5.2
// Module: s_expr_dsl_test
// ============================================================================

#ifndef S_EXPR_DSL_TEST_DEBUG_H
#define S_EXPR_DSL_TEST_DEBUG_H

#include <stdint.h>
#include <stdio.h>

// ============================================================================
// TREE DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    node_count;
    uint16_t    pointer_count;
    uint16_t    param_count;
} s_expr_dsl_test_tree_debug_t;

static const s_expr_dsl_test_tree_debug_t s_expr_dsl_test_tree_debug[] = {
    { 0xEBA1F08A, "test_result_codes_1", 1, 0, 0 },
    { 0xEAA1EEF7, "test_result_codes_2", 1, 0, 0 },
    { 0xE9A1ED64, "test_result_codes_3", 1, 0, 0 },
    { 0xE8A1EBD1, "test_result_codes_4", 1, 0, 0 },
    { 0xE7A1EA3E, "test_result_codes_5", 1, 0, 0 },
    { 0xE6A1E8AB, "test_result_codes_6", 1, 0, 0 },
    { 0xE5A1E718, "test_result_codes_7", 1, 0, 0 },
    { 0xE4A1E585, "test_result_codes_8", 1, 0, 0 },
    { 0xE3A1E3F2, "test_result_codes_9", 1, 0, 0 },
    { 0xAE7550EB, "test_pipeline_and_delays", 13, 4, 0 },
    { 0x6764DEAF, "test_conditionals", 31, 0, 0 },
    { 0x3B4B5C29, "test_state_machine", 20, 2, 0 },
    { 0x1CF26AC8, "test_field_dispatch_idle", 15, 0, 0 },
    { 0x95E46F4E, "test_field_dispatch_start", 16, 0, 0 },
    { 0x5A638916, "test_field_dispatch_stop", 16, 0, 0 },
    { 0x1AB48355, "test_event_dispatch", 12, 0, 0 },
    { 0x14CCAF62, "test_basic_lists", 8, 0, 0 },
    { 0x48646D7F, "test_dictionary_basic", 13, 0, 0 },
    { 0xD995097B, "test_dictionary_with_actions", 21, 0, 0 },
    { 0xAFECDD8E, "test_array_basic", 8, 0, 0 },
    { 0xA310BFED, "test_tuple_basic", 8, 0, 0 },
};
#define S_EXPR_DSL_TEST_TREE_DEBUG_COUNT 21

// ============================================================================
// FUNCTION DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    index;
} s_expr_dsl_test_func_debug_t;

// Oneshot functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_oneshot_debug[] = {
    { 0xCEBBEFA4, "SE_LOG", 0 },
    { 0xE5FF0069, "SET_STATE", 1 },
    { 0xEF5AD4AB, "SE_SET_HASH", 2 },
};
#define S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT 3

// Main functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_main_debug[] = {
    { 0xB4243714, "SE_RETURN_CONTINUE", 0 },
    { 0xDFE64C74, "SE_RETURN_TERMINATE", 1 },
    { 0x70EAA030, "SE_RETURN_RESET", 2 },
    { 0x02C11A13, "SE_RETURN_DISABLE", 3 },
    { 0x056FB9EA, "SE_RETURN_HALT", 4 },
    { 0xEAE5524E, "SE_RETURN_SKIP_CONTINUE", 5 },
    { 0x891F0675, "SE_RETURN_FUNCTION_HALT", 6 },
    { 0xF6027E85, "SE_RETURN_FUNCTION_RESET", 7 },
    { 0x0A5B8A85, "SE_RETURN_FUNCTION_TERMINATE", 8 },
    { 0x4D6E2B18, "SE_PIPELINE", 9 },
    { 0x0C3460EB, "SE_TICK_DELAY", 10 },
    { 0xA60CE767, "SE_TIME_DELAY", 11 },
    { 0xAD4917EC, "SE_WAIT_EVENT", 12 },
    { 0x080C2B37, "SE_NOP", 13 },
    { 0x1E860193, "SE_IF_THEN_ELSE", 14 },
    { 0x8374277F, "SE_TRIGGER_ON_CHANGE", 15 },
    { 0x5EEDA8E9, "SE_STATE_MACHINE", 16 },
    { 0x25308B8F, "SE_STATE_ACTIONS", 17 },
    { 0xA1C11B35, "SE_FIELD_DISPATCH", 18 },
    { 0xF3EDFC75, "SE_EVENT_DISPATCH", 19 },
    { 0xE6B90959, "PROCESS_INT_LIST", 20 },
    { 0x274D6E56, "MULTI_LIST_FUNC", 21 },
    { 0xC32CF90C, "NESTED_LISTS", 22 },
    { 0xDE8E6F0D, "SE_HASH_DISPATCH", 23 },
    { 0x876B8A33, "SE_NAMED_STATE_MACHINE", 24 },
    { 0x88810CB1, "ARRAY_ACCESS", 25 },
    { 0x267C4925, "FIELD_ARRAY", 26 },
    { 0xB366B1FF, "MATRIX_2D", 27 },
    { 0xDE2C8DF7, "PROCESS_TUPLE", 28 },
    { 0xDB0DE5BE, "TUPLE_TABLE", 29 },
    { 0x715D092E, "COMPLEX_TUPLE", 30 },
};
#define S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT 31

// Predicate functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_pred_debug[] = {
    { 0x27B2B70D, "CHECK_CONDITION", 0 },
    { 0xA303CD62, "ANOTHER_CONDITION", 1 },
    { 0xC04E8337, "MONITOR_STATE", 2 },
    { 0x520E2FF0, "BUTTON_PRESSED", 3 },
    { 0x6FAC375E, "SENSOR_ACTIVE", 4 },
};
#define S_EXPR_DSL_TEST_PRED_DEBUG_COUNT 5

// ============================================================================
// RECORD DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    offset;
    uint16_t    size;
} s_expr_dsl_test_field_debug_t;

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    size;
    uint16_t    field_count;
    const s_expr_dsl_test_field_debug_t* fields;
} s_expr_dsl_test_record_debug_t;

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_all_primitives_fields_debug[] = {
    { 0x01A0FC23, "field_int8", 0, 1 },
    { 0xB37E343A, "field_int16", 2, 2 },
    { 0x37838134, "field_int32", 4, 4 },
    { 0xB38F7D5B, "field_int64", 8, 8 },
    { 0xC4B89BD0, "field_uint8", 16, 1 },
    { 0xA6B34DB7, "field_uint16", 18, 2 },
    { 0x12B874E9, "field_uint32", 20, 4 },
    { 0xA6C019AA, "field_uint64", 24, 8 },
    { 0xB3C89512, "field_float", 32, 4 },
    { 0x87D47455, "field_double", 40, 8 },
    { 0xBB833678, "field_bool", 48, 1 },
    { 0x2EEAEB94, "field_char", 49, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_string_container_fields_debug[] = {
    { 0x8D39BDE6, "name", 0, 32 },
    { 0x346F3B69, "description", 32, 64 },
    { 0x83D03615, "length", 96, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_vector3d_fields_debug[] = {
    { 0xFD0C5087, "x", 0, 4 },
    { 0xFC0C4EF4, "y", 4, 4 },
    { 0xFF0C53AD, "z", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pid_gains_fields_debug[] = {
    { 0x573D1A6E, "kp", 0, 4 },
    { 0x403CF639, "ki", 4, 4 },
    { 0x4B3D078A, "kd", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_motor_state_fields_debug[] = {
    { 0x934F4E0A, "position", 0, 12 },
    { 0x32741C32, "velocity", 12, 12 },
    { 0x473F6463, "torque", 24, 4 },
    { 0x02F3B39E, "enabled", 28, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_system_state_fields_debug[] = {
    { 0xCAF08472, "motor", 0, 32 },
    { 0x6940FD22, "pid", 32, 12 },
    { 0x967B9630, "system_time", 44, 4 },
    { 0x14FC1187, "error_code", 48, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_list_node_fields_debug[] = {
    { 0xD872E2A5, "data", 0, 4 },
    { 0x5CB68DE8, "next", 4, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pointer_container_fields_debug[] = {
    { 0x37386AE0, "id", 0, 4 },
    { 0xE51D0E20, "node_ptr", 4, 4 },
    { 0x6658B7F3, "vector_ptr", 8, 4 },
    { 0xCF99CA30, "char_ptr", 12, 4 },
    { 0x39B1DDF4, "count", 16, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_test_blackboard_fields_debug[] = {
    { 0x783132F6, "state", 0, 4 },
    { 0xF328E8BF, "hash_state", 4, 4 },
    { 0x93594AB2, "command", 8, 4 },
    { 0xA08B063D, "event_id", 12, 4 },
    { 0x9CACDE23, "counter", 16, 4 },
    { 0xE9F2A935, "temperature", 20, 4 },
    { 0x02F3B39E, "enabled", 24, 1 },
    { 0x24F208E4, "message", 25, 48 },
    { 0xCAF08472, "motor", 76, 32 },
    { 0x9278AFF7, "gains", 108, 12 },
    { 0x72F57E48, "data_ptr", 120, 4 },
    { 0x9C677A2C, "flags", 124, 4 },
};

static const s_expr_dsl_test_record_debug_t s_expr_dsl_test_record_debug[] = {
    { 0xBF9832AB, "all_primitives", 56, 12, s_expr_dsl_test_all_primitives_fields_debug },
    { 0x92908A58, "string_container", 98, 3, s_expr_dsl_test_string_container_fields_debug },
    { 0xD299CEC5, "vector3d", 12, 3, s_expr_dsl_test_vector3d_fields_debug },
    { 0x76017CA9, "pid_gains", 12, 3, s_expr_dsl_test_pid_gains_fields_debug },
    { 0x7EFCE2D8, "motor_state", 32, 4, s_expr_dsl_test_motor_state_fields_debug },
    { 0x941691FA, "system_state", 52, 4, s_expr_dsl_test_system_state_fields_debug },
    { 0x79C6FBD6, "list_node", 8, 2, s_expr_dsl_test_list_node_fields_debug },
    { 0x52CABAEA, "pointer_container", 20, 5, s_expr_dsl_test_pointer_container_fields_debug },
    { 0xBD657307, "test_blackboard", 128, 12, s_expr_dsl_test_test_blackboard_fields_debug },
};
#define S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT 9

// ============================================================================
// DEBUG LOOKUP FUNCTIONS
// ============================================================================

static inline const char* s_expr_dsl_test_find_tree_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_TREE_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_tree_debug[i].hash == hash) {
            return s_expr_dsl_test_tree_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_main_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_main_debug[i].hash == hash) {
            return s_expr_dsl_test_main_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_oneshot_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_oneshot_debug[i].hash == hash) {
            return s_expr_dsl_test_oneshot_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_pred_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_PRED_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_pred_debug[i].hash == hash) {
            return s_expr_dsl_test_pred_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_record_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_record_debug[i].hash == hash) {
            return s_expr_dsl_test_record_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline void s_expr_dsl_test_print_trees(void) {
    printf("s_expr_dsl_test Trees (%d):\n", S_EXPR_DSL_TEST_TREE_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_TREE_DEBUG_COUNT; i++) {
        const s_expr_dsl_test_tree_debug_t* t = &s_expr_dsl_test_tree_debug[i];
        printf("  [%2d] 0x%08X %-32s nodes=%d ptrs=%d params=%d\n",
               i, t->hash, t->name, t->node_count, t->pointer_count, t->param_count);
    }
}

static inline void s_expr_dsl_test_print_functions(void) {
    printf("s_expr_dsl_test Main Functions (%d):\n", S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_main_debug[i].hash, s_expr_dsl_test_main_debug[i].name);
    }
    printf("s_expr_dsl_test Oneshot Functions (%d):\n", S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_oneshot_debug[i].hash, s_expr_dsl_test_oneshot_debug[i].name);
    }
    printf("s_expr_dsl_test Predicate Functions (%d):\n", S_EXPR_DSL_TEST_PRED_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_PRED_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_pred_debug[i].hash, s_expr_dsl_test_pred_debug[i].name);
    }
}

static inline void s_expr_dsl_test_print_records(void) {
    printf("s_expr_dsl_test Records (%d):\n", S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT; i++) {
        const s_expr_dsl_test_record_debug_t* r = &s_expr_dsl_test_record_debug[i];
        printf("  [%2d] 0x%08X %-24s size=%d fields=%d\n",
               i, r->hash, r->name, r->size, r->field_count);
        for (int j = 0; j < r->field_count; j++) {
            const s_expr_dsl_test_field_debug_t* f = &r->fields[j];
            printf("       [%2d] 0x%08X %-20s offset=%d size=%d\n",
                   j, f->hash, f->name, f->offset, f->size);
        }
    }
}

static inline void s_expr_dsl_test_print_debug_all(void) {
    printf("\n========== S_EXPR_DSL_TEST DEBUG INFO ==========\n\n");
    s_expr_dsl_test_print_trees();
    printf("\n");
    s_expr_dsl_test_print_functions();
    printf("\n");
    s_expr_dsl_test_print_records();
    printf("\n");
}

#endif // S_EXPR_DSL_TEST_DEBUG_H
