// ============================================================================
// s_expr_dsl_test_debug.h
// DEBUG INFORMATION - Auto-generated by s_expr_dsl.lua v5.2
// Module: s_expr_dsl_test
// ============================================================================

#ifndef S_EXPR_DSL_TEST_DEBUG_H
#define S_EXPR_DSL_TEST_DEBUG_H

#include <stdint.h>
#include <stdio.h>

// ============================================================================
// TREE DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    node_count;
    uint16_t    pointer_count;
    uint16_t    param_count;
} s_expr_dsl_test_tree_debug_t;

static const s_expr_dsl_test_tree_debug_t s_expr_dsl_test_tree_debug[] = {
    { 0xEBA1F08A, "test_result_codes_1", 1, 0, 0 },
    { 0xEAA1EEF7, "test_result_codes_2", 1, 0, 0 },
    { 0xE9A1ED64, "test_result_codes_3", 1, 0, 0 },
    { 0xE8A1EBD1, "test_result_codes_4", 1, 0, 0 },
    { 0xE7A1EA3E, "test_result_codes_5", 1, 0, 0 },
    { 0xE6A1E8AB, "test_result_codes_6", 1, 0, 0 },
    { 0xE5A1E718, "test_result_codes_7", 1, 0, 0 },
    { 0xE4A1E585, "test_result_codes_8", 1, 0, 0 },
    { 0xE3A1E3F2, "test_result_codes_9", 1, 0, 0 },
    { 0xAE7550EB, "test_pipeline_and_delays", 13, 4, 0 },
    { 0x6764DEAF, "test_conditionals", 31, 0, 0 },
    { 0x3B4B5C29, "test_state_machine", 20, 2, 0 },
    { 0x1CF26AC8, "test_field_dispatch_idle", 15, 0, 0 },
    { 0x95E46F4E, "test_field_dispatch_start", 16, 0, 0 },
    { 0x5A638916, "test_field_dispatch_stop", 16, 0, 0 },
    { 0x1AB48355, "test_event_dispatch", 12, 0, 0 },
    { 0x14CCAF62, "test_basic_lists", 8, 0, 0 },
    { 0x48646D7F, "test_dictionary_basic", 13, 0, 0 },
    { 0xD995097B, "test_dictionary_with_actions", 21, 0, 0 },
    { 0xAFECDD8E, "test_array_basic", 8, 0, 0 },
    { 0xA310BFED, "test_tuple_basic", 8, 0, 0 },
    { 0xB7C0ED13, "test_named_state_machine", 28, 2, 0 },
    { 0xC0516A38, "test_dict_event_dispatch", 21, 0, 0 },
    { 0x581C8A41, "test_complex_structures", 4, 0, 0 },
    { 0xF91097B7, "test_alist_style", 4, 0, 0 },
    { 0x017D22AC, "test_plist_style", 2, 0, 0 },
    { 0x28DCF95F, "test_trigger_on_change", 39, 0, 0 },
    { 0xEDA681FF, "test_sequence", 23, 2, 0 },
    { 0x6FEF2BF1, "test_sequence_tracking", 16, 2, 0 },
    { 0xA0D861EA, "test_fork", 18, 2, 0 },
    { 0x30643172, "test_fork_tracking", 18, 2, 0 },
    { 0x1E53C533, "test_fork_fatal", 15, 2, 0 },
    { 0x35552C8F, "test_fork_join", 17, 2, 0 },
    { 0xA003E4C1, "test_fork_join_tracking", 18, 2, 0 },
    { 0x69C66CCA, "test_fork_join_fatal", 14, 2, 0 },
    { 0x6932C2D0, "test_fork_join_vs_fork", 12, 1, 0 },
    { 0x1775D484, "test_chain_flow", 17, 0, 0 },
    { 0xF5B367AC, "test_chain_flow_reset", 17, 0, 0 },
    { 0x58505DA8, "test_chain_flow_terminate", 17, 0, 0 },
    { 0xA0B087E6, "test_chain_flow_halt", 17, 0, 0 },
    { 0xAC94CB7F, "test_chain_flow_disable", 17, 0, 0 },
    { 0xEDD1DF53, "test_chain_flow_multitick", 16, 1, 0 },
    { 0xC97E09F4, "test_for_loop", 9, 0, 0 },
    { 0x199AEA24, "test_for_loop_delay", 12, 1, 0 },
    { 0x7E7457D5, "test_for_loop_slot", 10, 0, 0 },
    { 0x3FBDE81F, "test_for_loop_zero", 9, 0, 0 },
    { 0x8116A116, "test_for_loop_multi", 13, 0, 0 },
    { 0x1BE5287A, "test_while_loop", 12, 0, 0 },
    { 0xA1D984BE, "test_while_loop_false", 11, 0, 0 },
    { 0x87E9FD3E, "test_while_loop_delay", 15, 1, 0 },
    { 0x6D614BB8, "test_while_loop_multi", 18, 0, 0 },
    { 0x700C04B2, "test_while_loop_break", 18, 0, 0 },
};
#define S_EXPR_DSL_TEST_TREE_DEBUG_COUNT 52

// ============================================================================
// FUNCTION DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    index;
} s_expr_dsl_test_func_debug_t;

// Oneshot functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_oneshot_debug[] = {
    { 0xCEBBEFA4, "SE_LOG", 0 },
    { 0xE5FF0069, "SET_STATE", 1 },
    { 0xEF5AD4AB, "SE_SET_HASH", 2 },
    { 0x13068D30, "ON_BIT0_RISE", 3 },
    { 0xF8140330, "ON_BIT0_FALL", 4 },
    { 0xFE5ADA37, "ON_BITS_12_RISE", 5 },
    { 0x7B832107, "ON_BITS_12_FALL", 6 },
    { 0x6B533EF3, "ON_BITS_34_RISE", 7 },
    { 0x29423823, "ON_BITS_34_FALL", 8 },
    { 0x15953A35, "ON_BIT5_CLEAR", 9 },
    { 0xAC23F0C8, "ON_BIT5_SET", 10 },
    { 0x1D13DA13, "RESET_SEQUENCE_TRACKER", 11 },
    { 0x85D14963, "TRACK_STEP", 12 },
    { 0x557C66BB, "VERIFY_SEQUENCE_ORDER", 13 },
    { 0xB1E77AAE, "SET_FIELD_INT", 14 },
    { 0x12C4B13E, "INCREMENT_COUNTER_ONESHOT", 15 },
};
#define S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT 16

// Main functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_main_debug[] = {
    { 0xB4243714, "SE_RETURN_CONTINUE", 0 },
    { 0xDFE64C74, "SE_RETURN_TERMINATE", 1 },
    { 0x70EAA030, "SE_RETURN_RESET", 2 },
    { 0x02C11A13, "SE_RETURN_DISABLE", 3 },
    { 0x056FB9EA, "SE_RETURN_HALT", 4 },
    { 0xEAE5524E, "SE_RETURN_SKIP_CONTINUE", 5 },
    { 0x891F0675, "SE_RETURN_FUNCTION_HALT", 6 },
    { 0xF6027E85, "SE_RETURN_FUNCTION_RESET", 7 },
    { 0x0A5B8A85, "SE_RETURN_FUNCTION_TERMINATE", 8 },
    { 0x4D6E2B18, "SE_PIPELINE", 9 },
    { 0x0C3460EB, "SE_TICK_DELAY", 10 },
    { 0xA60CE767, "SE_TIME_DELAY", 11 },
    { 0xAD4917EC, "SE_WAIT_EVENT", 12 },
    { 0x080C2B37, "SE_NOP", 13 },
    { 0x1E860193, "SE_IF_THEN_ELSE", 14 },
    { 0x8374277F, "SE_TRIGGER_ON_CHANGE", 15 },
    { 0x5EEDA8E9, "SE_STATE_MACHINE", 16 },
    { 0x25308B8F, "SE_STATE_ACTIONS", 17 },
    { 0xA1C11B35, "SE_FIELD_DISPATCH", 18 },
    { 0xF3EDFC75, "SE_EVENT_DISPATCH", 19 },
    { 0xE6B90959, "PROCESS_INT_LIST", 20 },
    { 0x274D6E56, "MULTI_LIST_FUNC", 21 },
    { 0xC32CF90C, "NESTED_LISTS", 22 },
    { 0xDE8E6F0D, "SE_HASH_DISPATCH", 23 },
    { 0x876B8A33, "SE_NAMED_STATE_MACHINE", 24 },
    { 0x88810CB1, "ARRAY_ACCESS", 25 },
    { 0x267C4925, "FIELD_ARRAY", 26 },
    { 0xB366B1FF, "MATRIX_2D", 27 },
    { 0xDE2C8DF7, "PROCESS_TUPLE", 28 },
    { 0xDB0DE5BE, "TUPLE_TABLE", 29 },
    { 0x715D092E, "COMPLEX_TUPLE", 30 },
    { 0x5E99A787, "SE_NAMED_EVENT_DISPATCH", 31 },
    { 0x29E86A85, "INCREMENT_COUNTER", 32 },
    { 0x2D0F9AEB, "TOGGLE_ENABLED", 33 },
    { 0x86807A58, "READ_SENSOR", 34 },
    { 0x2C30B0AC, "LOAD_CONFIG", 35 },
    { 0x55C4D336, "PROCESS_ALIST", 36 },
    { 0xD36A3C79, "PROCESS_PLIST", 37 },
    { 0xEC3EE7BF, "SE_SEQUENCE", 38 },
    { 0x0A24332A, "SE_FORK", 39 },
    { 0xE404E1CF, "SE_FORK_JOIN", 40 },
    { 0xFFC1FAA4, "SE_CHAIN_FLOW", 41 },
    { 0xA11A2225, "SE_FOR", 42 },
    { 0xA08B6DD3, "SE_WHILE", 43 },
};
#define S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT 44

// Predicate functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_pred_debug[] = {
    { 0x27B2B70D, "CHECK_CONDITION", 0 },
    { 0xA303CD62, "ANOTHER_CONDITION", 1 },
    { 0xC04E8337, "MONITOR_STATE", 2 },
    { 0x520E2FF0, "BUTTON_PRESSED", 3 },
    { 0x6FAC375E, "SENSOR_ACTIVE", 4 },
    { 0x2D749139, "TEST_BIT", 5 },
    { 0x7C0DF5F3, "SE_PRED_AND", 6 },
    { 0x0CF6212F, "SE_PRED_OR", 7 },
    { 0x217DEB8F, "SE_PRED_NOT", 8 },
    { 0x306B0C71, "LESS_THAN_THREE_PRED", 9 },
    { 0x77C35775, "SE_FALSE", 10 },
    { 0x0C125BC2, "SE_TRUE", 11 },
    { 0xBB057075, "SE_GREATER_EQUAL_INT", 12 },
};
#define S_EXPR_DSL_TEST_PRED_DEBUG_COUNT 13

// ============================================================================
// RECORD DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    offset;
    uint16_t    size;
} s_expr_dsl_test_field_debug_t;

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    size;
    uint16_t    field_count;
    const s_expr_dsl_test_field_debug_t* fields;
} s_expr_dsl_test_record_debug_t;

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_all_primitives_fields_debug[] = {
    { 0x01A0FC23, "field_int8", 0, 1 },
    { 0xB37E343A, "field_int16", 2, 2 },
    { 0x37838134, "field_int32", 4, 4 },
    { 0xB38F7D5B, "field_int64", 8, 8 },
    { 0xC4B89BD0, "field_uint8", 16, 1 },
    { 0xA6B34DB7, "field_uint16", 18, 2 },
    { 0x12B874E9, "field_uint32", 20, 4 },
    { 0xA6C019AA, "field_uint64", 24, 8 },
    { 0xB3C89512, "field_float", 32, 4 },
    { 0x87D47455, "field_double", 40, 8 },
    { 0xBB833678, "field_bool", 48, 1 },
    { 0x2EEAEB94, "field_char", 49, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_string_container_fields_debug[] = {
    { 0x8D39BDE6, "name", 0, 32 },
    { 0x346F3B69, "description", 32, 64 },
    { 0x83D03615, "length", 96, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_vector3d_fields_debug[] = {
    { 0xFD0C5087, "x", 0, 4 },
    { 0xFC0C4EF4, "y", 4, 4 },
    { 0xFF0C53AD, "z", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pid_gains_fields_debug[] = {
    { 0x573D1A6E, "kp", 0, 4 },
    { 0x403CF639, "ki", 4, 4 },
    { 0x4B3D078A, "kd", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_motor_state_fields_debug[] = {
    { 0x934F4E0A, "position", 0, 12 },
    { 0x32741C32, "velocity", 12, 12 },
    { 0x473F6463, "torque", 24, 4 },
    { 0x02F3B39E, "enabled", 28, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_system_state_fields_debug[] = {
    { 0xCAF08472, "motor", 0, 32 },
    { 0x6940FD22, "pid", 32, 12 },
    { 0x967B9630, "system_time", 44, 4 },
    { 0x14FC1187, "error_code", 48, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_list_node_fields_debug[] = {
    { 0xD872E2A5, "data", 0, 4 },
    { 0x5CB68DE8, "next", 4, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pointer_container_fields_debug[] = {
    { 0x37386AE0, "id", 0, 4 },
    { 0xE51D0E20, "node_ptr", 4, 4 },
    { 0x6658B7F3, "vector_ptr", 8, 4 },
    { 0xCF99CA30, "char_ptr", 12, 4 },
    { 0x39B1DDF4, "count", 16, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_test_blackboard_fields_debug[] = {
    { 0x783132F6, "state", 0, 4 },
    { 0xF328E8BF, "hash_state", 4, 4 },
    { 0x93594AB2, "command", 8, 4 },
    { 0xA08B063D, "event_id", 12, 4 },
    { 0x9CACDE23, "counter", 16, 4 },
    { 0xE9F2A935, "temperature", 20, 4 },
    { 0x02F3B39E, "enabled", 24, 1 },
    { 0x24F208E4, "message", 25, 48 },
    { 0xCAF08472, "motor", 76, 32 },
    { 0x9278AFF7, "gains", 108, 12 },
    { 0x72F57E48, "data_ptr", 120, 4 },
    { 0x9C677A2C, "flags", 124, 4 },
};

static const s_expr_dsl_test_record_debug_t s_expr_dsl_test_record_debug[] = {
    { 0xBF9832AB, "all_primitives", 56, 12, s_expr_dsl_test_all_primitives_fields_debug },
    { 0x92908A58, "string_container", 98, 3, s_expr_dsl_test_string_container_fields_debug },
    { 0xD299CEC5, "vector3d", 12, 3, s_expr_dsl_test_vector3d_fields_debug },
    { 0x76017CA9, "pid_gains", 12, 3, s_expr_dsl_test_pid_gains_fields_debug },
    { 0x7EFCE2D8, "motor_state", 32, 4, s_expr_dsl_test_motor_state_fields_debug },
    { 0x941691FA, "system_state", 52, 4, s_expr_dsl_test_system_state_fields_debug },
    { 0x79C6FBD6, "list_node", 8, 2, s_expr_dsl_test_list_node_fields_debug },
    { 0x52CABAEA, "pointer_container", 20, 5, s_expr_dsl_test_pointer_container_fields_debug },
    { 0xBD657307, "test_blackboard", 128, 12, s_expr_dsl_test_test_blackboard_fields_debug },
};
#define S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT 9

// ============================================================================
// DEBUG LOOKUP FUNCTIONS
// ============================================================================

static inline const char* s_expr_dsl_test_find_tree_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_TREE_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_tree_debug[i].hash == hash) return s_expr_dsl_test_tree_debug[i].name;
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_main_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_main_debug[i].hash == hash) return s_expr_dsl_test_main_debug[i].name;
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_oneshot_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_oneshot_debug[i].hash == hash) return s_expr_dsl_test_oneshot_debug[i].name;
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_pred_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_PRED_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_pred_debug[i].hash == hash) return s_expr_dsl_test_pred_debug[i].name;
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_record_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_record_debug[i].hash == hash) return s_expr_dsl_test_record_debug[i].name;
    }
    return "UNKNOWN";
}

#endif // S_EXPR_DSL_TEST_DEBUG_H
