/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_KB_INFO_H
#define CHAINTREE_HANDLE_KB_INFO_H

#include "chaintree_support.h"

#define CT_TYOH8EKC_KB_COUNT 20


extern const chaintree_kb_info_t ct_tyoh8ekc_kb_table[20];

#endif /* CHAINTREE_HANDLE_KB_INFO_H */