// sensor_msgs.h
// Generated by avro_dsl.lua - DO NOT EDIT
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "avro_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FILE METADATA ============
#define SENSOR_MSGS_RECORD_COUNT  5
#define SENSOR_MSGS_SCHEMA_FILE   "sensor_msgs.h"

// ============ ENUMS ============
typedef enum {
    SENSOR_TYPE_TEMP = 0,
    SENSOR_TYPE_PRESSURE = 1,
    SENSOR_TYPE_HUMIDITY = 2,
    SENSOR_TYPE_FLOW = 3
} sensor_type_t;

typedef enum {
    SENSOR_STATE_IDLE = 0,
    SENSOR_STATE_SAMPLING = 1,
    SENSOR_STATE_ERROR = 2,
    SENSOR_STATE_CALIBRATING = 3
} sensor_state_t;

// ============ FIXED ARRAYS ============
typedef uint8_t mac_addr_t[6];
typedef uint8_t uuid_t[16];

// ============ FIXED STRINGS ============
typedef char label_t[16];
typedef char unit_t[8];

// ============ STRUCTS ============
typedef struct {
    uint16_t device_id;
    uint16_t seq;
    uint32_t timestamp;
} packet_header_t;

typedef struct {
    uint16_t sample_rate;
    float threshold_lo;
    float threshold_hi;
    bool enabled;
} sensor_config_t;

// ============ RECORDS ============
typedef struct {
    packet_header_t header;
    float celsius;
    sensor_state_t state;
} temp_reading_t;

typedef struct {
    packet_header_t header;
    uint32_t pascals;
    sensor_state_t state;
} pressure_reading_t;

typedef struct {
    packet_header_t header;
    float percent;
    sensor_state_t state;
} humidity_reading_t;

typedef struct {
    packet_header_t header;
    uint8_t count;
    float temps[8];
    uint32_t pressures[8];
} sensor_batch_t;

typedef struct {
    mac_addr_t mac;
    label_t name;
    uint32_t firmware_ver;
    sensor_config_t config;
} device_info_t;

// ============ ENCODE/DECODE ============
static inline size_t temp_reading_encode(const temp_reading_t* src, uint8_t* buf) {
    memcpy(buf, src, sizeof(temp_reading_t));
    return sizeof(temp_reading_t);
}

static inline void temp_reading_decode(const uint8_t* buf, temp_reading_t* dst) {
    memcpy(dst, buf, sizeof(temp_reading_t));
}

static inline size_t pressure_reading_encode(const pressure_reading_t* src, uint8_t* buf) {
    memcpy(buf, src, sizeof(pressure_reading_t));
    return sizeof(pressure_reading_t);
}

static inline void pressure_reading_decode(const uint8_t* buf, pressure_reading_t* dst) {
    memcpy(dst, buf, sizeof(pressure_reading_t));
}

static inline size_t humidity_reading_encode(const humidity_reading_t* src, uint8_t* buf) {
    memcpy(buf, src, sizeof(humidity_reading_t));
    return sizeof(humidity_reading_t);
}

static inline void humidity_reading_decode(const uint8_t* buf, humidity_reading_t* dst) {
    memcpy(dst, buf, sizeof(humidity_reading_t));
}

static inline size_t sensor_batch_encode(const sensor_batch_t* src, uint8_t* buf) {
    memcpy(buf, src, sizeof(sensor_batch_t));
    return sizeof(sensor_batch_t);
}

static inline void sensor_batch_decode(const uint8_t* buf, sensor_batch_t* dst) {
    memcpy(dst, buf, sizeof(sensor_batch_t));
}

static inline size_t device_info_encode(const device_info_t* src, uint8_t* buf) {
    memcpy(buf, src, sizeof(device_info_t));
    return sizeof(device_info_t);
}

static inline void device_info_decode(const uint8_t* buf, device_info_t* dst) {
    memcpy(dst, buf, sizeof(device_info_t));
}

// ============ WIRE PACKETS ============
// Per-record packet types with schema info and source node

typedef struct {
    const char* schema_file;   // schema .h file name
    uint16_t    source_node;   // originating node ID
    uint8_t     index;         // record type index
    uint16_t    length;        // payload size
    temp_reading_t data;           // payload
} temp_reading_packet_t;

typedef struct {
    const char* schema_file;   // schema .h file name
    uint16_t    source_node;   // originating node ID
    uint8_t     index;         // record type index
    uint16_t    length;        // payload size
    pressure_reading_t data;           // payload
} pressure_reading_packet_t;

typedef struct {
    const char* schema_file;   // schema .h file name
    uint16_t    source_node;   // originating node ID
    uint8_t     index;         // record type index
    uint16_t    length;        // payload size
    humidity_reading_t data;           // payload
} humidity_reading_packet_t;

typedef struct {
    const char* schema_file;   // schema .h file name
    uint16_t    source_node;   // originating node ID
    uint8_t     index;         // record type index
    uint16_t    length;        // payload size
    sensor_batch_t data;           // payload
} sensor_batch_packet_t;

typedef struct {
    const char* schema_file;   // schema .h file name
    uint16_t    source_node;   // originating node ID
    uint8_t     index;         // record type index
    uint16_t    length;        // payload size
    device_info_t data;           // payload
} device_info_packet_t;

// Packet encode helpers
static inline void temp_reading_packet_encode(
        temp_reading_packet_t* pkt,
        const temp_reading_t* src,
        uint16_t source_node)
{
    pkt->schema_file = SENSOR_MSGS_SCHEMA_FILE;
    pkt->source_node = source_node;
    pkt->index = 0;
    pkt->length = sizeof(temp_reading_t);
    pkt->data = *src;
}

static inline void pressure_reading_packet_encode(
        pressure_reading_packet_t* pkt,
        const pressure_reading_t* src,
        uint16_t source_node)
{
    pkt->schema_file = SENSOR_MSGS_SCHEMA_FILE;
    pkt->source_node = source_node;
    pkt->index = 1;
    pkt->length = sizeof(pressure_reading_t);
    pkt->data = *src;
}

static inline void humidity_reading_packet_encode(
        humidity_reading_packet_t* pkt,
        const humidity_reading_t* src,
        uint16_t source_node)
{
    pkt->schema_file = SENSOR_MSGS_SCHEMA_FILE;
    pkt->source_node = source_node;
    pkt->index = 2;
    pkt->length = sizeof(humidity_reading_t);
    pkt->data = *src;
}

static inline void sensor_batch_packet_encode(
        sensor_batch_packet_t* pkt,
        const sensor_batch_t* src,
        uint16_t source_node)
{
    pkt->schema_file = SENSOR_MSGS_SCHEMA_FILE;
    pkt->source_node = source_node;
    pkt->index = 3;
    pkt->length = sizeof(sensor_batch_t);
    pkt->data = *src;
}

static inline void device_info_packet_encode(
        device_info_packet_t* pkt,
        const device_info_t* src,
        uint16_t source_node)
{
    pkt->schema_file = SENSOR_MSGS_SCHEMA_FILE;
    pkt->source_node = source_node;
    pkt->index = 4;
    pkt->length = sizeof(device_info_t);
    pkt->data = *src;
}


#ifdef __cplusplus
}
#endif
