#!/usr/bin/env luajit
-- avro_dsl.lua
-- LuaJIT DSL for generating C header files from Avro-like schema definitions

local M = {}

-- Current state
local current_file = nil
local current_container = nil  -- struct, record, or enum being defined

-- Type mappings
local type_sizes = {
    int8    = 1,  uint8   = 1,
    int16   = 2,  uint16  = 2,
    int32   = 4,  uint32  = 4,
    int64   = 8,  uint64  = 8,
    float   = 4,  double  = 8,
    bool    = 1,
}

local type_cnames = {
    int8    = "int8_t",   uint8   = "uint8_t",
    int16   = "int16_t",  uint16  = "uint16_t",
    int32   = "int32_t",  uint32  = "uint32_t",
    int64   = "int64_t",  uint64  = "uint64_t",
    float   = "float",    double  = "double",
    bool    = "bool",
}

--------------------------------------------------------------------------------
-- DSL COMMANDS
--------------------------------------------------------------------------------

function M.FILE(name)
    current_file = {
        name = name,
        includes = {},
        enums = {},
        fixed = {},
        strings = {},
        structs = {},
        records = {},
    }
end

function M.INCLUDE(header)
    table.insert(current_file.includes, header)
end

function M.ENUM(name)
    current_container = {
        kind = "enum",
        name = name,
        values = {},
    }
end

function M.VALUE(name, val)
    table.insert(current_container.values, { name = name, val = val })
end

function M.END_ENUM()
    table.insert(current_file.enums, current_container)
    current_container = nil
end

function M.FIXED(name, size)
    table.insert(current_file.fixed, { name = name, size = size })
end

function M.STRING(name, length)
    table.insert(current_file.strings, { name = name, length = length })
end

function M.STRUCT(name)
    current_container = {
        kind = "struct",
        name = name,
        fields = {},
    }
end

function M.RECORD(name)
    current_container = {
        kind = "record",
        name = name,
        index = #current_file.records,  -- position-based index
        fields = {},
    }
end

function M.FIELD(name, ftype, array_size)
    table.insert(current_container.fields, {
        name = name,
        type = ftype,
        array_size = array_size,
    })
end

function M.END_STRUCT()
    table.insert(current_file.structs, current_container)
    current_container = nil
end

function M.END_RECORD()
    table.insert(current_file.records, current_container)
    current_container = nil
end

--------------------------------------------------------------------------------
-- CODE GENERATION
--------------------------------------------------------------------------------

local function upper_name(name)
    return name:upper()
end

local function resolve_ctype(ftype)
    if type_cnames[ftype] then
        return type_cnames[ftype]
    end
    -- Check if it's a defined type (enum, fixed, string, struct)
    for _, e in ipairs(current_file.enums) do
        if e.name == ftype then return ftype .. "_t" end
    end
    for _, f in ipairs(current_file.fixed) do
        if f.name == ftype then return ftype .. "_t" end
    end
    for _, s in ipairs(current_file.strings) do
        if s.name == ftype then return ftype .. "_t" end
    end
    for _, st in ipairs(current_file.structs) do
        if st.name == ftype then return ftype .. "_t" end
    end
    for _, r in ipairs(current_file.records) do
        if r.name == ftype then return ftype .. "_t" end
    end
    -- Assume user-defined type
    return ftype .. "_t"
end

local function emit_header(out)
    out:write("// " .. current_file.name .. ".h\n")
    out:write("// Generated by avro_dsl.lua - DO NOT EDIT\n")
    out:write("#pragma once\n\n")
    
    for _, inc in ipairs(current_file.includes) do
        out:write(string.format("#include <%s>\n", inc))
    end
    if #current_file.includes > 0 then
        out:write("\n")
    end
end

local function emit_file_metadata(out)
    local name_upper = upper_name(current_file.name)
    out:write("// ============ FILE METADATA ============\n")
    out:write(string.format("#define %s_RECORD_COUNT  %d\n\n", name_upper, #current_file.records))
end

local function emit_enums(out)
    if #current_file.enums == 0 then return end
    out:write("// ============ ENUMS ============\n")
    for _, e in ipairs(current_file.enums) do
        out:write(string.format("typedef enum {\n"))
        for i, v in ipairs(e.values) do
            local comma = (i < #e.values) and "," or ""
            out:write(string.format("    %s_%s = %d%s\n", upper_name(e.name), v.name, v.val, comma))
        end
        out:write(string.format("} %s_t;\n\n", e.name))
    end
end

local function emit_fixed(out)
    if #current_file.fixed == 0 then return end
    out:write("// ============ FIXED ARRAYS ============\n")
    for _, f in ipairs(current_file.fixed) do
        out:write(string.format("typedef uint8_t %s_t[%d];\n", f.name, f.size))
    end
    out:write("\n")
end

local function emit_strings(out)
    if #current_file.strings == 0 then return end
    out:write("// ============ FIXED STRINGS ============\n")
    for _, s in ipairs(current_file.strings) do
        out:write(string.format("typedef char %s_t[%d];\n", s.name, s.length))
    end
    out:write("\n")
end

local function emit_struct_def(out, st)
    out:write(string.format("typedef struct {\n"))
    for _, f in ipairs(st.fields) do
        local ctype = resolve_ctype(f.type)
        if f.array_size then
            out:write(string.format("    %s %s[%d];\n", ctype, f.name, f.array_size))
        else
            out:write(string.format("    %s %s;\n", ctype, f.name))
        end
    end
    out:write(string.format("} %s_t;\n\n", st.name))
end

local function emit_structs(out)
    if #current_file.structs == 0 then return end
    out:write("// ============ STRUCTS ============\n")
    for _, st in ipairs(current_file.structs) do
        emit_struct_def(out, st)
    end
end

local function emit_records(out)
    if #current_file.records == 0 then return end
    out:write("// ============ RECORDS ============\n")
    for _, r in ipairs(current_file.records) do
        emit_struct_def(out, r)
    end
end

local function emit_codecs(out)
    if #current_file.records == 0 then return end
    out:write("// ============ ENCODE/DECODE ============\n")
    for _, r in ipairs(current_file.records) do
        local tname = r.name .. "_t"
        -- Encode
        out:write(string.format("static inline size_t %s_encode(const %s* src, uint8_t* buf) {\n", r.name, tname))
        out:write(string.format("    memcpy(buf, src, sizeof(%s));\n", tname))
        out:write(string.format("    return sizeof(%s);\n", tname))
        out:write("}\n\n")
        -- Decode
        out:write(string.format("static inline void %s_decode(const uint8_t* buf, %s* dst) {\n", r.name, tname))
        out:write(string.format("    memcpy(dst, buf, sizeof(%s));\n", tname))
        out:write("}\n\n")
    end
end

local function emit_wire_packets(out)
    if #current_file.records == 0 then return end
    
    out:write("// ============ WIRE PACKETS ============\n")
    out:write("// Per-record packet types with exact payload size\n\n")
    
    for _, r in ipairs(current_file.records) do
        out:write(string.format("typedef struct {\n"))
        out:write("    uint8_t  index;\n")
        out:write("    uint16_t length;\n")
        out:write(string.format("    %s_t data;\n", r.name))
        out:write(string.format("} %s_packet_t;\n\n", r.name))
    end
    
    -- Generate encode helper per record
    out:write("// Packet encode helpers\n")
    for i, r in ipairs(current_file.records) do
        local idx = i - 1  -- 0-based
        out:write(string.format("static inline void %s_packet_encode(%s_packet_t* pkt, const %s_t* src) {\n",
            r.name, r.name, r.name))
        out:write(string.format("    pkt->index = %d;\n", idx))
        out:write(string.format("    pkt->length = sizeof(%s_t);\n", r.name))
        out:write("    pkt->data = *src;\n")
        out:write("}\n\n")
    end
end

local function emit_descriptors(out)
    if #current_file.records == 0 then return end
    
    out:write("// ============ RECORD DESCRIPTORS ============\n")
    out:write("typedef struct {\n")
    out:write("    uint8_t     index;\n")
    out:write("    uint16_t    size;\n")
    out:write("    const char* name;\n")
    out:write("} avro_record_desc_t;\n\n")
    
    out:write(string.format("static const avro_record_desc_t %s_records[] = {\n", current_file.name))
    for i, r in ipairs(current_file.records) do
        local idx = i - 1
        out:write(string.format('    { %d, sizeof(%s_t), "%s" },\n', idx, r.name, r.name))
    end
    out:write("};\n")
end

function M.GENERATE(output_path)
    output_path = output_path or (current_file.name .. ".h")
    local out = io.open(output_path, "w")
    if not out then
        error("Cannot open output file: " .. output_path)
    end
    
    emit_header(out)
    emit_file_metadata(out)
    emit_enums(out)
    emit_fixed(out)
    emit_strings(out)
    emit_structs(out)
    emit_records(out)
    --emit_codecs(out)
    emit_wire_packets(out)
    emit_descriptors(out)
    
    out:close()
    print("Generated: " .. output_path)
end

--------------------------------------------------------------------------------
-- MODULE EXPORT
--------------------------------------------------------------------------------

-- Export all DSL commands to global namespace for convenience
function M.export_globals()
    _G.FILE       = M.FILE
    _G.INCLUDE    = M.INCLUDE
    _G.ENUM       = M.ENUM
    _G.VALUE      = M.VALUE
    _G.END_ENUM   = M.END_ENUM
    _G.FIXED      = M.FIXED
    _G.STRING     = M.STRING
    _G.STRUCT     = M.STRUCT
    _G.RECORD     = M.RECORD
    _G.FIELD      = M.FIELD
    _G.END_STRUCT = M.END_STRUCT
    _G.END_RECORD = M.END_RECORD
    _G.GENERATE   = M.GENERATE
end

return M