/* Auto-generated by ChainTree Pipeline */
#include "test_header_events.h"

/* Event names indexed by event index */
const char *ct_4vn9ga8l_event_strings[19] = {
    "CFL_INIT_EVENT",
    "CFL_TERMINATE_EVENT",
    "CFL_START_TESTS",
    "CFL_TERMINATE_TESTS",
    "CFL_TIMER_EVENT",
    "CFL_SECOND_EVENT",
    "CFL_MINUTE_EVENT",
    "CFL_HOUR_EVENT",
    "CFL_DAY_EVENT",
    "CFL_WEEK_EVENT",
    "CFL_MONTH_EVENT",
    "CFL_YEAR_EVENT",
    "WAIT_FOR_EVENT",
    "PUBLISH_EVENT",
    "TEST_EVENT_1",
    "TEST_EVENT_2",
    "TEST_EVENT_3",
    "SYNC_EVENT",
    "TEST_EVENT",
};
