/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_NODE_DATA_H
#define TEST_HEADER_NODE_DATA_H

#include "chaintree_support.h"

/* Node data arrays (defined in .c file) */
extern const json_record_t ct_58fk1o71_node_data_records[5560];
extern const char ct_58fk1o71_node_data_strings[5655];
extern const record_control_t ct_58fk1o71_node_data_controls[860];

#endif /* TEST_HEADER_NODE_DATA_H */
