/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_NODES_H
#define TEST_HEADER_NODES_H

#include "chaintree_support.h"

#define CT_BAULID0X_NODE_COUNT 1484

extern const chaintree_node_t ct_baulid0x_nodes[CT_BAULID0X_NODE_COUNT];

#endif /* TEST_HEADER_NODES_H */