/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_NODES_H
#define TEST_HEADER_NODES_H

#include "chaintree_support.h"

#define CT_E0KVY28A_NODE_COUNT 1480

extern const chaintree_node_t ct_e0kvy28a_nodes[CT_E0KVY28A_NODE_COUNT];

#endif /* TEST_HEADER_NODES_H */