/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_LINKS_H
#define TEST_HEADER_LINKS_H

#include <stdint.h>

#define CT_HJR5GH90_LINK_TABLE_SIZE 361

extern const uint16_t ct_hjr5gh90_link_table[CT_HJR5GH90_LINK_TABLE_SIZE];

#endif /* TEST_HEADER_LINKS_H */