/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_BITMASKS_H
#define TEST_HEADER_BITMASKS_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* No bitmasks defined */
#define CT_RIT1ZO87_BITMASK_COUNT 0

/* Empty array */
extern const char *ct_rit1zo87_bitmask_names[1];

#endif /* TEST_HEADER_BITMASKS_H */