/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_KB_INFO_H
#define TEST_HEADER_KB_INFO_H

#include "chaintree_support.h"

#define CT_71UW6IPW_KB_COUNT 20


extern const chaintree_kb_info_t ct_71uw6ipw_kb_table[20];

#endif /* TEST_HEADER_KB_INFO_H */