/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_LINKS_H
#define TEST_HEADER_LINKS_H

#include <stdint.h>

#define CT_MIHP1U4T_LINK_TABLE_SIZE 1307

extern const uint16_t ct_mihp1u4t_link_table[CT_MIHP1U4T_LINK_TABLE_SIZE];

#endif /* TEST_HEADER_LINKS_H */