/* Auto-generated by ChainTree Pipeline */

#include "test_header.h"

/* Const handle instance in flash memory */
const chaintree_handle_t g_test_header = {
    .unique_id = "ct_3uq9haus",
    
    /* Node data */
    .nodes = ct_3uq9haus_nodes,
    .node_count = 1420,
    
    /* Function arrays */
    .main_functions = ct_3uq9haus_main_functions,
    .main_function_count = 41,
    .one_shot_functions = ct_3uq9haus_one_shot_functions,
    .one_shot_function_count = 107,
    .boolean_functions = ct_3uq9haus_boolean_functions,
    .boolean_function_count = 35,
    
    /* Function names */
    .main_function_names = ct_3uq9haus_main_function_names,
    .one_shot_function_names = ct_3uq9haus_one_shot_function_names,
    .boolean_function_names = ct_3uq9haus_boolean_function_names,
    
    /* Main function usage counts */
    .main_function_usage_count = ct_3uq9haus_main_function_usage_count,
    
    /* Link table */
    .link_table = ct_3uq9haus_link_table,
    .link_table_size = 1364,
    
    /* Event strings */
    .event_strings = (const char **)ct_3uq9haus_event_strings,
    .event_count = 44,
    
    /* Bitmask names */
    .bitmask_names = (const char **)ct_3uq9haus_bitmask_names,
    .bitmask_count = 3,
    
    /* Knowledge base info */
    .kb_table = ct_3uq9haus_kb_table,
    .kb_count = 28,
    
    /* Node data (JSON records) */
    .node_data_records = ct_3uq9haus_node_data_records,
    .node_data_records_count = 6616,
    .node_data_strings = ct_3uq9haus_node_data_strings,
    .node_data_strings_size = 7046,
    .node_data_controls = ct_3uq9haus_node_data_controls,
    .node_data_controls_count = 986
};
