/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_NODES_H
#define TEST_HEADER_NODES_H

#include "chaintree_support.h"

#define CT_4CZ3ANTP_NODE_COUNT 1400

extern const chaintree_node_t ct_4cz3antp_nodes[CT_4CZ3ANTP_NODE_COUNT];

#endif /* TEST_HEADER_NODES_H */