/* Auto-generated by ChainTree Pipeline */
#ifndef TEST_HEADER_LINKS_H
#define TEST_HEADER_LINKS_H

#include <stdint.h>

#define CT_6DH5BEH1_LINK_TABLE_SIZE 625

extern const uint16_t ct_6dh5beh1_link_table[CT_6DH5BEH1_LINK_TABLE_SIZE];

#endif /* TEST_HEADER_LINKS_H */