-- comm_ffi.lua
-- LuaJIT FFI binding for libcomm. Hand-written (NOT generated by
-- avro_dsl) because comm.h is the public API of a manually-authored C
-- library. Mirrors libcomm/comm.h exactly; bump both in lockstep when
-- adding fields.

local ffi = require("ffi")

ffi.cdef[[
typedef int32_t  comm_result_t;
typedef uint32_t comm_handle_t;
typedef uint16_t comm_cmd_t;
typedef uint8_t  comm_node_state_t;

typedef struct {
    comm_handle_t handle;
    comm_cmd_t    cmd;
    uint8_t       mcu;
    uint8_t       ack_status;
    uint16_t      seq;
    uint16_t      payload_len;
    uint32_t      elapsed_ms;
    uint8_t       payload[128];
} comm_event_t;

typedef void (*comm_logger_fn)(int level, const char* msg);

comm_result_t     comm_init           (const uint8_t *blob, size_t len);
void              comm_shutdown       (void);
comm_result_t     comm_attach_internal(uint8_t dongle_idx, uint8_t bus_id,
                                       uint8_t addr, void *physics_handle);

comm_handle_t     comm_submit          (uint8_t mcu, comm_cmd_t cmd,
                                        const uint8_t *payload, uint16_t payload_len,
                                        comm_result_t *err);
comm_handle_t     comm_submit_broadcast(uint8_t bus_id, comm_cmd_t cmd, uint8_t responder,
                                        const uint8_t *payload, uint16_t payload_len,
                                        comm_result_t *err);
comm_result_t     comm_status          (comm_handle_t h);
comm_result_t     comm_claim           (comm_handle_t h, comm_event_t *out);
comm_result_t     comm_cancel          (comm_handle_t h);
int               comm_poll            (comm_event_t *out, int max);

comm_node_state_t comm_node_state        (uint8_t mcu);
uint32_t          comm_node_physics_model(uint8_t mcu);
uint8_t           comm_node_miss_count   (uint8_t mcu);
uint32_t          comm_node_last_seen_ms (uint8_t mcu);

void              comm_set_logger       (comm_logger_fn fn, int level);
uint32_t          comm_now_ms           (void);
]]

local C = ffi.load("./libcomm.so")

local M = { C = C }

-- ============ ENUMS ============

M.RESULT = {
    OK                  =   0,
    ERR_INIT            =  -1,
    ERR_BUS             =  -2,
    ERR_BAD_MANIFEST    =  -3,
    ERR_DONGLE_MISSING  =  -4,
    ERR_DONGLE_UNEXPECTED = -5,
    ERR_BAD_HANDLE      =  -6,
    ERR_NO_DATA         =  -7,
    ERR_TIMEOUT         =  -8,
    ERR_NAK             =  -9,
    ERR_FAULT           = -10,
    ERR_OVERFLOW        = -11,
    ERR_BAD_ARG         = -12,
}

M.NODE = {
    UNKNOWN = 0,
    PENDING = 1,
    LIVE    = 2,
    FAULTED = 3,
}

-- Link-control class (0x00xx). Higher classes (uplink/downlink/immediate)
-- are deferred to a phase-2 catalogue.
M.CMD = {
    NULL          = 0x0000,
    PING          = 0x0001,
    ACK_BARE      = 0x0002,
    NAK           = 0x0003,
    DRAIN         = 0x0004,
    JOIN_REQ      = 0x0005,
    JOIN_ACK      = 0x0006,
    JOIN_CONFIRM  = 0x0007,
    TIME_SYNC     = 0x0008,
    HALT          = 0x0009,
    RESUME        = 0x000A,
    GO            = 0x000B,
    ESTOP         = 0x000C,
    DONGLE_HELLO  = 0x000D,
    DONGLE_IDENT  = 0x000E,
}

M.HANDLES_MAX     = 32
M.PAYLOAD_MAX     = 128
M.HANDLE_INVALID  = 0
M.ACK_FLAG_URGENT = 0x80

M.event_t = ffi.typeof("comm_event_t")

return M
