/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_KB_INFO_H
#define CHAINTREE_HANDLE_KB_INFO_H

#include "chaintree_support.h"

#define CT_RJRP566L_KB_COUNT 17


extern const chaintree_kb_info_t ct_rjrp566l_kb_table[17];

#endif /* CHAINTREE_HANDLE_KB_INFO_H */