/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODES_H
#define CHAINTREE_HANDLE_NODES_H

#include "chaintree_support.h"

#define CT_TYOH8EKC_NODE_COUNT 1265

extern const chaintree_node_t ct_tyoh8ekc_nodes[CT_TYOH8EKC_NODE_COUNT];

#endif /* CHAINTREE_HANDLE_NODES_H */