/* Auto-generated by ChainTree Pipeline (LuaJIT) */

#include "incr.h"

const chaintree_handle_t g_incr = {
    .unique_id = "ct_bi827k3r",

    .nodes = ct_bi827k3r_nodes,
    .node_count = 85,

    .main_functions = ct_bi827k3r_main_functions,
    .main_function_count = 12,
    .one_shot_functions = ct_bi827k3r_one_shot_functions,
    .one_shot_function_count = 19,
    .boolean_functions = ct_bi827k3r_boolean_functions,
    .boolean_function_count = 6,

    .main_function_names = ct_bi827k3r_main_function_names,
    .one_shot_function_names = ct_bi827k3r_one_shot_function_names,
    .boolean_function_names = ct_bi827k3r_boolean_function_names,

    .main_function_usage_count = ct_bi827k3r_main_function_usage_count,

    .link_table = ct_bi827k3r_link_table,
    .link_table_size = 78,

    .event_strings = (const char **)ct_bi827k3r_event_strings,
    .event_count = 22,

    .bitmask_names = (const char **)ct_bi827k3r_bitmask_names,
    .bitmask_count = 0,

    .kb_table = ct_bi827k3r_kb_table,
    .kb_count = 3,

    .node_data_records = ct_bi827k3r_node_data_records,
    .node_data_records_count = 386,
    .node_data_strings = ct_bi827k3r_node_data_strings,
    .node_data_strings_size = 1369,
    .node_data_controls = ct_bi827k3r_node_data_controls,
    .node_data_controls_count = 54
};
