// ============================================================================
// s_expr_dsl_test_debug.h
// DEBUG INFORMATION - Auto-generated by s_expr_dsl.lua
// Module: s_expr_dsl_test
// ============================================================================

#ifndef S_EXPR_DSL_TEST_DEBUG_H
#define S_EXPR_DSL_TEST_DEBUG_H

#include <stdint.h>
#include <stdio.h>

// ============================================================================
// TREE DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    node_count;
    uint16_t    pointer_count;
    uint16_t    param_count;
} s_expr_dsl_test_tree_debug_t;

static const s_expr_dsl_test_tree_debug_t s_expr_dsl_test_tree_debug[] = {
    { 0x0F2D298C, "test_all_call_types", 6, 1, 0 },
    { 0x0C2D6F09, "test_all_param_types", 1, 0, 0 },
    { 0x282398FA, "test_result_codes", 9, 0, 0 },
    { 0x2B0C43E2, "test_composable_predicates", 32, 0, 0 },
    { 0xAE7550EB, "test_pipeline_and_delays", 8, 4, 0 },
    { 0x6764DEAF, "test_conditionals", 20, 0, 0 },
    { 0x3B4B5C29, "test_state_machine", 14, 2, 0 },
    { 0xD29ED858, "test_dispatch", 16, 0, 0 },
    { 0x6FD1BB3D, "test_predicate_helpers", 8, 0, 0 },
    { 0xA21839F7, "test_nested_fields", 6, 0, 0 },
    { 0xD1E84F15, "test_pointer_slots", 5, 4, 0 },
    { 0x0153499F, "test_complex_nesting", 11, 1, 0 },
};
#define S_EXPR_DSL_TEST_TREE_DEBUG_COUNT 12

// ============================================================================
// FUNCTION DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    index;
} s_expr_dsl_test_func_debug_t;

// Oneshot functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_oneshot_debug[] = {
    { 0xE562935D, "INIT_SYSTEM", 0 },
    { 0xCEBBEFA4, "SE_LOG", 1 },
    { 0x73602B5F, "UPDATE_COUNTER", 2 },
    { 0xE5FF0069, "SET_STATE", 3 },
    { 0x77B626F3, "SET_VECTOR", 4 },
    { 0x91FBEC26, "SET_FLOAT", 5 },
    { 0xFB0AC161, "SET_PID", 6 },
    { 0x7795933C, "SET_UINT", 7 },
    { 0x29418A6A, "LEVEL_3A", 8 },
};
#define S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT 9

// Main functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_main_debug[] = {
    { 0xAC7037D0, "PROCESS_STATE", 0 },
    { 0xC2EB67FF, "WAIT_FOR_EVENT", 1 },
    { 0xC82DEDD4, "TEST_PARAMS", 2 },
    { 0xB4243714, "SE_RETURN_CONTINUE", 3 },
    { 0xDFE64C74, "SE_RETURN_TERMINATE", 4 },
    { 0x70EAA030, "SE_RETURN_RESET", 5 },
    { 0x02C11A13, "SE_RETURN_DISABLE", 6 },
    { 0x056FB9EA, "SE_RETURN_HALT", 7 },
    { 0xEAE5524E, "SE_RETURN_SKIP_CONTINUE", 8 },
    { 0x891F0675, "SE_RETURN_FUNCTION_HALT", 9 },
    { 0xF6027E85, "SE_RETURN_FUNCTION_RESET", 10 },
    { 0x0A5B8A85, "SE_RETURN_FUNCTION_TERMINATE", 11 },
    { 0x4D6E2B18, "SE_PIPELINE", 12 },
    { 0x0C3460EB, "SE_TICK_DELAY", 13 },
    { 0xA60CE767, "SE_TIME_DELAY", 14 },
    { 0xAD4917EC, "SE_WAIT_EVENT", 15 },
    { 0x080C2B37, "SE_NOP", 16 },
    { 0x1E860193, "SE_IF_THEN_ELSE", 17 },
    { 0x8374277F, "SE_TRIGGER_ON_CHANGE", 18 },
    { 0x5EEDA8E9, "SE_STATE_MACHINE", 19 },
    { 0x25308B8F, "SE_STATE_ACTIONS", 20 },
    { 0xA1C11B35, "SE_FIELD_DISPATCH", 21 },
    { 0xF3EDFC75, "SE_EVENT_DISPATCH", 22 },
    { 0x63282C1D, "PROTOTHREAD_1", 23 },
    { 0x60282764, "PROTOTHREAD_2", 24 },
    { 0x612828F7, "PROTOTHREAD_3", 25 },
    { 0x008A6FCB, "OUTER_FUNC", 26 },
    { 0x742768B3, "NESTED_PROTOTHREAD", 27 },
    { 0xB00AF995, "LEVEL_1", 28 },
    { 0x053F1327, "LEVEL_2A", 29 },
    { 0x284188D7, "LEVEL_3B", 30 },
    { 0xAB0AF1B6, "LEVEL_4", 31 },
    { 0x063F14BA, "LEVEL_2B", 32 },
};
#define S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT 33

// Predicate functions
static const s_expr_dsl_test_func_debug_t s_expr_dsl_test_pred_debug[] = {
    { 0x7261C319, "CHECK_ENABLED", 0 },
    { 0x7C0DF5F3, "SE_PRED_AND", 1 },
    { 0x6906CB0E, "PRED_A", 2 },
    { 0x6806C97B, "PRED_B", 3 },
    { 0x0CF6212F, "SE_PRED_OR", 4 },
    { 0x6706C7E8, "PRED_C", 5 },
    { 0x6E06D2ED, "PRED_D", 6 },
    { 0x217DEB8F, "SE_PRED_NOT", 7 },
    { 0x6D06D15A, "PRED_E", 8 },
    { 0x11B4ADAF, "SENSOR_A_READY", 9 },
    { 0x7EECE99E, "SENSOR_B_READY", 10 },
    { 0x03994BA2, "TIMEOUT_EXPIRED", 11 },
    { 0xFB18B281, "RETRY_AVAILABLE", 12 },
    { 0x894065CB, "FLAG_1", 13 },
    { 0x8A40675E, "FLAG_2", 14 },
    { 0x8B4068F1, "FLAG_3", 15 },
    { 0x8C406A84, "FLAG_4", 16 },
    { 0x1F7DE869, "SE_PRED_NOR", 17 },
    { 0x6C06CFC7, "PRED_F", 18 },
    { 0x6B06CE34, "PRED_G", 19 },
    { 0x067DC775, "SE_PRED_NAND", 20 },
    { 0x6206C009, "PRED_H", 21 },
    { 0x6106BE76, "PRED_I", 22 },
    { 0xB713B6A3, "SE_PRED_XOR", 23 },
    { 0x6006BCE3, "PRED_J", 24 },
    { 0x5F06BB50, "PRED_K", 25 },
    { 0x27B2B70D, "CHECK_CONDITION", 26 },
    { 0xA303CD62, "ANOTHER_CONDITION", 27 },
    { 0xC04E8337, "MONITOR_STATE", 28 },
    { 0x520E2FF0, "BUTTON_PRESSED", 29 },
    { 0x6FAC375E, "SENSOR_ACTIVE", 30 },
    { 0x0C125BC2, "SE_TRUE", 31 },
    { 0x77C35775, "SE_FALSE", 32 },
    { 0x80659F81, "SE_CHECK_EVENT", 33 },
    { 0x8B787418, "CUSTOM_PRED", 34 },
    { 0xB437BB0B, "DEEP_PRED_1", 35 },
    { 0xB537BC9E, "DEEP_PRED_2", 36 },
    { 0xB637BE31, "DEEP_PRED_3", 37 },
};
#define S_EXPR_DSL_TEST_PRED_DEBUG_COUNT 38

// ============================================================================
// RECORD DEBUG INFO
// ============================================================================

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    offset;
    uint16_t    size;
} s_expr_dsl_test_field_debug_t;

typedef struct {
    uint32_t    hash;
    const char* name;
    uint16_t    size;
    uint16_t    field_count;
    const s_expr_dsl_test_field_debug_t* fields;
} s_expr_dsl_test_record_debug_t;

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_all_primitives_fields_debug[] = {
    { 0x01A0FC23, "field_int8", 0, 1 },
    { 0xB37E343A, "field_int16", 2, 2 },
    { 0x37838134, "field_int32", 4, 4 },
    { 0xB38F7D5B, "field_int64", 8, 8 },
    { 0xC4B89BD0, "field_uint8", 16, 1 },
    { 0xA6B34DB7, "field_uint16", 18, 2 },
    { 0x12B874E9, "field_uint32", 20, 4 },
    { 0xA6C019AA, "field_uint64", 24, 8 },
    { 0xB3C89512, "field_float", 32, 4 },
    { 0x87D47455, "field_double", 40, 8 },
    { 0xBB833678, "field_bool", 48, 1 },
    { 0x2EEAEB94, "field_char", 49, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_string_container_fields_debug[] = {
    { 0x8D39BDE6, "name", 0, 32 },
    { 0x346F3B69, "description", 32, 64 },
    { 0x83D03615, "length", 96, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_vector3d_fields_debug[] = {
    { 0xFD0C5087, "x", 0, 4 },
    { 0xFC0C4EF4, "y", 4, 4 },
    { 0xFF0C53AD, "z", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pid_gains_fields_debug[] = {
    { 0x573D1A6E, "kp", 0, 4 },
    { 0x403CF639, "ki", 4, 4 },
    { 0x4B3D078A, "kd", 8, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_motor_state_fields_debug[] = {
    { 0x934F4E0A, "position", 0, 12 },
    { 0x32741C32, "velocity", 12, 12 },
    { 0x473F6463, "torque", 24, 4 },
    { 0x02F3B39E, "enabled", 28, 1 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_system_state_fields_debug[] = {
    { 0xCAF08472, "motor", 0, 32 },
    { 0x6940FD22, "pid", 32, 12 },
    { 0x967B9630, "system_time", 44, 4 },
    { 0x14FC1187, "error_code", 48, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_list_node_fields_debug[] = {
    { 0xD872E2A5, "data", 0, 4 },
    { 0x5CB68DE8, "next", 4, 4 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_pointer_container_fields_debug[] = {
    { 0x37386AE0, "id", 0, 4 },
    { 0xE51D0E20, "node_ptr", 4, 4 },
    { 0x6658B7F3, "vector_ptr", 8, 4 },
    { 0xCF99CA30, "char_ptr", 12, 4 },
    { 0x39B1DDF4, "count", 16, 2 },
};

static const s_expr_dsl_test_field_debug_t s_expr_dsl_test_test_blackboard_fields_debug[] = {
    { 0x783132F6, "state", 0, 4 },
    { 0x93594AB2, "command", 4, 4 },
    { 0xA08B063D, "event_id", 8, 4 },
    { 0x9CACDE23, "counter", 12, 4 },
    { 0xE9F2A935, "temperature", 16, 4 },
    { 0x02F3B39E, "enabled", 20, 1 },
    { 0x24F208E4, "message", 21, 48 },
    { 0xCAF08472, "motor", 72, 32 },
    { 0x9278AFF7, "gains", 104, 12 },
    { 0x72F57E48, "data_ptr", 116, 4 },
    { 0x9C677A2C, "flags", 120, 4 },
};

static const s_expr_dsl_test_record_debug_t s_expr_dsl_test_record_debug[] = {
    { 0xBF9832AB, "all_primitives", 56, 12, s_expr_dsl_test_all_primitives_fields_debug },
    { 0x92908A58, "string_container", 98, 3, s_expr_dsl_test_string_container_fields_debug },
    { 0xD299CEC5, "vector3d", 12, 3, s_expr_dsl_test_vector3d_fields_debug },
    { 0x76017CA9, "pid_gains", 12, 3, s_expr_dsl_test_pid_gains_fields_debug },
    { 0x7EFCE2D8, "motor_state", 32, 4, s_expr_dsl_test_motor_state_fields_debug },
    { 0x941691FA, "system_state", 52, 4, s_expr_dsl_test_system_state_fields_debug },
    { 0x79C6FBD6, "list_node", 8, 2, s_expr_dsl_test_list_node_fields_debug },
    { 0x52CABAEA, "pointer_container", 20, 5, s_expr_dsl_test_pointer_container_fields_debug },
    { 0xBD657307, "test_blackboard", 124, 11, s_expr_dsl_test_test_blackboard_fields_debug },
};
#define S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT 9

// ============================================================================
// DEBUG LOOKUP FUNCTIONS
// ============================================================================

static inline const char* s_expr_dsl_test_find_tree_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_TREE_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_tree_debug[i].hash == hash) {
            return s_expr_dsl_test_tree_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_main_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_main_debug[i].hash == hash) {
            return s_expr_dsl_test_main_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_oneshot_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_oneshot_debug[i].hash == hash) {
            return s_expr_dsl_test_oneshot_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_pred_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_PRED_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_pred_debug[i].hash == hash) {
            return s_expr_dsl_test_pred_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline const char* s_expr_dsl_test_find_record_name(uint32_t hash) {
    for (int i = 0; i < S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT; i++) {
        if (s_expr_dsl_test_record_debug[i].hash == hash) {
            return s_expr_dsl_test_record_debug[i].name;
        }
    }
    return "UNKNOWN";
}

static inline void s_expr_dsl_test_print_trees(void) {
    printf("s_expr_dsl_test Trees (%d):\n", S_EXPR_DSL_TEST_TREE_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_TREE_DEBUG_COUNT; i++) {
        const s_expr_dsl_test_tree_debug_t* t = &s_expr_dsl_test_tree_debug[i];
        printf("  [%2d] 0x%08X %-32s nodes=%d ptrs=%d params=%d\n",
               i, t->hash, t->name, t->node_count, t->pointer_count, t->param_count);
    }
}

static inline void s_expr_dsl_test_print_functions(void) {
    printf("s_expr_dsl_test Main Functions (%d):\n", S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_MAIN_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_main_debug[i].hash, s_expr_dsl_test_main_debug[i].name);
    }
    printf("s_expr_dsl_test Oneshot Functions (%d):\n", S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_ONESHOT_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_oneshot_debug[i].hash, s_expr_dsl_test_oneshot_debug[i].name);
    }
    printf("s_expr_dsl_test Predicate Functions (%d):\n", S_EXPR_DSL_TEST_PRED_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_PRED_DEBUG_COUNT; i++) {
        printf("  [%2d] 0x%08X %s\n", i, s_expr_dsl_test_pred_debug[i].hash, s_expr_dsl_test_pred_debug[i].name);
    }
}

static inline void s_expr_dsl_test_print_records(void) {
    printf("s_expr_dsl_test Records (%d):\n", S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT);
    for (int i = 0; i < S_EXPR_DSL_TEST_RECORD_DEBUG_COUNT; i++) {
        const s_expr_dsl_test_record_debug_t* r = &s_expr_dsl_test_record_debug[i];
        printf("  [%2d] 0x%08X %-24s size=%d fields=%d\n",
               i, r->hash, r->name, r->size, r->field_count);
        for (int j = 0; j < r->field_count; j++) {
            const s_expr_dsl_test_field_debug_t* f = &r->fields[j];
            printf("       [%2d] 0x%08X %-20s offset=%d size=%d\n",
                   j, f->hash, f->name, f->offset, f->size);
        }
    }
}

static inline void s_expr_dsl_test_print_debug_all(void) {
    printf("\n========== S_EXPR_DSL_TEST DEBUG INFO ==========\n\n");
    s_expr_dsl_test_print_trees();
    printf("\n");
    s_expr_dsl_test_print_functions();
    printf("\n");
    s_expr_dsl_test_print_records();
    printf("\n");
}

#endif // S_EXPR_DSL_TEST_DEBUG_H
