/**
 * @file generated_irrigation_valves_data.h
 * @brief Static data tables for irrigation_valves
 *
 * Include this file in exactly ONE .c file in your project.
 *
 * Two node tables:
 *   - irrigation_valves_nodes_by_hash: sorted by hash for O(log n) lookup
 *   - irrigation_valves_nodes_tree: in DSL order for tree walking
 *
 * Auto-generated - DO NOT EDIT
 */

#ifndef IRRIGATION_VALVES_DATA_H
#define IRRIGATION_VALVES_DATA_H

#include "generated_irrigation_valves.h"

/* ============================================ */
/* Tree-Order Node Table (for walking)          */
/* ============================================ */

/* Nodes in DSL definition order - children are contiguous */
static const irrigation_valves_node_t irrigation_valves_nodes_tree[36] = {
    { 0xD4D5A144U, 3, -1, 4, 1, 0, 0 },  /* [0] VALVE_STATUS */
    { 0x7492D1CAU, 3, 0, 4, 2, 1, 0 },  /* [1] VALVE_STATUS.STATION_1_VALVE_STATUS */
    { 0x6B2D261AU, 0, 1, 0, 0, 2, 1 },  /* [2] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0x6CEE09A9U, 0, 1, 0, 0, 2, 1 },  /* [3] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0xBE5595E8U, 0, 1, 0, 0, 2, 1 },  /* [4] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0x91A2EC47U, 0, 1, 0, 0, 2, 1 },  /* [5] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS */
    { 0x4065F0D9U, 3, 0, 3, 7, 1, 0 },  /* [6] VALVE_STATUS.STATION_2_VALVE_STATUS */
    { 0xA3769025U, 0, 6, 0, 0, 2, 1 },  /* [7] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0xF5B488C6U, 0, 6, 0, 0, 2, 1 },  /* [8] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0xCE8CB14FU, 0, 6, 0, 0, 2, 1 },  /* [9] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0x9499C658U, 3, 0, 3, 11, 1, 0 },  /* [10] VALVE_STATUS.STATION_3_VALVE_STATUS */
    { 0xA98D269CU, 0, 10, 0, 0, 2, 1 },  /* [11] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0x4BB06657U, 0, 10, 0, 0, 2, 1 },  /* [12] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0x0976EEAEU, 0, 10, 0, 0, 2, 1 },  /* [13] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0xC3623077U, 3, 0, 3, 15, 1, 0 },  /* [14] VALVE_STATUS.STATION_4_VALVE_STATUS */
    { 0xA147788FU, 0, 14, 0, 0, 2, 1 },  /* [15] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0x2ACA4FB4U, 0, 14, 0, 0, 2, 1 },  /* [16] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0xDA7BDF65U, 0, 14, 0, 0, 2, 1 },  /* [17] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0x059ECDAFU, 2, -1, 4, 19, 0, 0 },  /* [18] VALVE_STATE */
    { 0xD8BFCC4EU, 2, 18, 4, 20, 1, 0 },  /* [19] VALVE_STATE.STATION_1_VALVE_STATE */
    { 0x940E98F9U, 1, 19, 0, 0, 2, 1 },  /* [20] VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0x90FFB51CU, 1, 19, 0, 0, 2, 1 },  /* [21] VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0x74EDA017U, 1, 19, 0, 0, 2, 1 },  /* [22] VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x9589A6E2U, 1, 19, 0, 0, 2, 1 },  /* [23] VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE */
    { 0x5AB7C397U, 2, 18, 3, 25, 1, 0 },  /* [24] VALVE_STATE.STATION_2_VALVE_STATE */
    { 0x4C2970D6U, 1, 24, 0, 0, 2, 1 },  /* [25] VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0x4231B5DFU, 1, 24, 0, 0, 2, 1 },  /* [26] VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0xBB4C9CA4U, 1, 24, 0, 0, 2, 1 },  /* [27] VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x76C9D89CU, 2, 18, 3, 29, 1, 0 },  /* [28] VALVE_STATE.STATION_3_VALVE_STATE */
    { 0x9CFDD593U, 1, 28, 0, 0, 2, 1 },  /* [29] VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0xC30961AAU, 1, 28, 0, 0, 2, 1 },  /* [30] VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0x9A4C46F5U, 1, 28, 0, 0, 2, 1 },  /* [31] VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x435DFC0DU, 2, 18, 3, 33, 1, 0 },  /* [32] VALVE_STATE.STATION_4_VALVE_STATE */
    { 0x63B3DE00U, 1, 32, 0, 0, 2, 1 },  /* [33] VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0xFE7C464DU, 1, 32, 0, 0, 2, 1 },  /* [34] VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0x30358FA2U, 1, 32, 0, 0, 2, 1 },  /* [35] VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE */
};

/* ============================================ */
/* Hash-Sorted Lookup Table                     */
/* ============================================ */

/* Hash lookup entry - maps hash to tree index */
typedef struct {
    uint32_t hash;
    uint16_t tree_index;  /* Index into irrigation_valves_nodes_tree */
} irrigation_valves_hash_entry_t;

/* Sorted by hash for binary search */
static const irrigation_valves_hash_entry_t irrigation_valves_nodes_by_hash[36] = {
    { 0x059ECDAFU, 18 },  /* VALVE_STATE */
    { 0x0976EEAEU, 13 },  /* VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0x2ACA4FB4U, 16 },  /* VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0x30358FA2U, 35 },  /* VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x4065F0D9U, 6 },  /* VALVE_STATUS.STATION_2_VALVE_STATUS */
    { 0x4231B5DFU, 26 },  /* VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0x435DFC0DU, 32 },  /* VALVE_STATE.STATION_4_VALVE_STATE */
    { 0x4BB06657U, 12 },  /* VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0x4C2970D6U, 25 },  /* VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0x5AB7C397U, 24 },  /* VALVE_STATE.STATION_2_VALVE_STATE */
    { 0x63B3DE00U, 33 },  /* VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0x6B2D261AU, 2 },  /* VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0x6CEE09A9U, 3 },  /* VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0x7492D1CAU, 1 },  /* VALVE_STATUS.STATION_1_VALVE_STATUS */
    { 0x74EDA017U, 22 },  /* VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x76C9D89CU, 28 },  /* VALVE_STATE.STATION_3_VALVE_STATE */
    { 0x90FFB51CU, 21 },  /* VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0x91A2EC47U, 5 },  /* VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS */
    { 0x940E98F9U, 20 },  /* VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0x9499C658U, 10 },  /* VALVE_STATUS.STATION_3_VALVE_STATUS */
    { 0x9589A6E2U, 23 },  /* VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE */
    { 0x9A4C46F5U, 31 },  /* VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0x9CFDD593U, 29 },  /* VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE */
    { 0xA147788FU, 15 },  /* VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0xA3769025U, 7 },  /* VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0xA98D269CU, 11 },  /* VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0xBB4C9CA4U, 27 },  /* VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE */
    { 0xBE5595E8U, 4 },  /* VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0xC30961AAU, 30 },  /* VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE */
    { 0xC3623077U, 14 },  /* VALVE_STATUS.STATION_4_VALVE_STATUS */
    { 0xCE8CB14FU, 9 },  /* VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0xD4D5A144U, 0 },  /* VALVE_STATUS */
    { 0xD8BFCC4EU, 19 },  /* VALVE_STATE.STATION_1_VALVE_STATE */
    { 0xDA7BDF65U, 17 },  /* VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0xF5B488C6U, 8 },  /* VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0xFE7C464DU, 34 },  /* VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE */
};

/* ============================================ */
/* Arena Offsets (tree order)                   */
/* ============================================ */

/* Arena offsets for ALARM_LATCHED buffer */
static const irrigation_valves_arena_info_t irrigation_valves_ALARM_LATCHED_arena[36] = {
    { 0, 1 },  /* [0] VALVE_STATUS */
    { 1, 1 },  /* [1] VALVE_STATUS.STATION_1_VALVE_STATUS */
    { 2, 1 },  /* [2] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 3, 1 },  /* [3] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 4, 1 },  /* [4] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 5, 1 },  /* [5] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS */
    { 6, 1 },  /* [6] VALVE_STATUS.STATION_2_VALVE_STATUS */
    { 7, 1 },  /* [7] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 8, 1 },  /* [8] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 9, 1 },  /* [9] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 10, 1 },  /* [10] VALVE_STATUS.STATION_3_VALVE_STATUS */
    { 11, 1 },  /* [11] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 12, 1 },  /* [12] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 13, 1 },  /* [13] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 14, 1 },  /* [14] VALVE_STATUS.STATION_4_VALVE_STATUS */
    { 15, 1 },  /* [15] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 16, 1 },  /* [16] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 17, 1 },  /* [17] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 18, 0 },  /* [18] VALVE_STATE */
    { 18, 0 },  /* [19] VALVE_STATE.STATION_1_VALVE_STATE */
    { 18, 0 },  /* [20] VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [21] VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [22] VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [23] VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE */
    { 18, 0 },  /* [24] VALVE_STATE.STATION_2_VALVE_STATE */
    { 18, 0 },  /* [25] VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [26] VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [27] VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [28] VALVE_STATE.STATION_3_VALVE_STATE */
    { 18, 0 },  /* [29] VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [30] VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [31] VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [32] VALVE_STATE.STATION_4_VALVE_STATE */
    { 18, 0 },  /* [33] VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [34] VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [35] VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE */
};

/* Arena offsets for ALARM_MASK buffer */
static const irrigation_valves_arena_info_t irrigation_valves_ALARM_MASK_arena[36] = {
    { 0, 1 },  /* [0] VALVE_STATUS */
    { 1, 1 },  /* [1] VALVE_STATUS.STATION_1_VALVE_STATUS */
    { 2, 1 },  /* [2] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 3, 1 },  /* [3] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 4, 1 },  /* [4] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 5, 1 },  /* [5] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS */
    { 6, 1 },  /* [6] VALVE_STATUS.STATION_2_VALVE_STATUS */
    { 7, 1 },  /* [7] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 8, 1 },  /* [8] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 9, 1 },  /* [9] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 10, 1 },  /* [10] VALVE_STATUS.STATION_3_VALVE_STATUS */
    { 11, 1 },  /* [11] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 12, 1 },  /* [12] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 13, 1 },  /* [13] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 14, 1 },  /* [14] VALVE_STATUS.STATION_4_VALVE_STATUS */
    { 15, 1 },  /* [15] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 16, 1 },  /* [16] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 17, 1 },  /* [17] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 18, 0 },  /* [18] VALVE_STATE */
    { 18, 0 },  /* [19] VALVE_STATE.STATION_1_VALVE_STATE */
    { 18, 0 },  /* [20] VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [21] VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [22] VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [23] VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE */
    { 18, 0 },  /* [24] VALVE_STATE.STATION_2_VALVE_STATE */
    { 18, 0 },  /* [25] VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [26] VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [27] VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [28] VALVE_STATE.STATION_3_VALVE_STATE */
    { 18, 0 },  /* [29] VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [30] VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [31] VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE */
    { 18, 0 },  /* [32] VALVE_STATE.STATION_4_VALVE_STATE */
    { 18, 0 },  /* [33] VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE */
    { 18, 0 },  /* [34] VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE */
    { 18, 0 },  /* [35] VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE */
};

/* Arena offsets for AND_LATCHED buffer */
static const irrigation_valves_arena_info_t irrigation_valves_AND_LATCHED_arena[36] = {
    { 0, 0 },  /* [0] VALVE_STATUS */
    { 0, 0 },  /* [1] VALVE_STATUS.STATION_1_VALVE_STATUS */
    { 0, 0 },  /* [2] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0, 0 },  /* [3] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0, 0 },  /* [4] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0, 0 },  /* [5] VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS */
    { 0, 0 },  /* [6] VALVE_STATUS.STATION_2_VALVE_STATUS */
    { 0, 0 },  /* [7] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0, 0 },  /* [8] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0, 0 },  /* [9] VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0, 0 },  /* [10] VALVE_STATUS.STATION_3_VALVE_STATUS */
    { 0, 0 },  /* [11] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0, 0 },  /* [12] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0, 0 },  /* [13] VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0, 0 },  /* [14] VALVE_STATUS.STATION_4_VALVE_STATUS */
    { 0, 0 },  /* [15] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS */
    { 0, 0 },  /* [16] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS */
    { 0, 0 },  /* [17] VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS */
    { 0, 1 },  /* [18] VALVE_STATE */
    { 1, 1 },  /* [19] VALVE_STATE.STATION_1_VALVE_STATE */
    { 2, 1 },  /* [20] VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE */
    { 3, 1 },  /* [21] VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE */
    { 4, 1 },  /* [22] VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE */
    { 5, 1 },  /* [23] VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE */
    { 6, 1 },  /* [24] VALVE_STATE.STATION_2_VALVE_STATE */
    { 7, 1 },  /* [25] VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE */
    { 8, 1 },  /* [26] VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE */
    { 9, 1 },  /* [27] VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE */
    { 10, 1 },  /* [28] VALVE_STATE.STATION_3_VALVE_STATE */
    { 11, 1 },  /* [29] VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE */
    { 12, 1 },  /* [30] VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE */
    { 13, 1 },  /* [31] VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE */
    { 14, 1 },  /* [32] VALVE_STATE.STATION_4_VALVE_STATE */
    { 15, 1 },  /* [33] VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE */
    { 16, 1 },  /* [34] VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE */
    { 17, 1 },  /* [35] VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE */
};

/* ============================================ */
/* Root Nodes                                   */
/* ============================================ */

#define IRRIGATION_VALVES_ROOT_COUNT 2
static const uint16_t irrigation_valves_roots[2] = { 0, 18 };

/* ============================================ */
/* Runtime Configuration (for cfl_hbit.h)       */
/* ============================================ */

/* Buffer type values - use enum from cfl_hbit.h if available */
#ifdef CFL_HBIT_H
  /* cfl_hbit.h included - use its enum */
#else
  /* Standalone - define values */
  #define CFL_HBIT_BUF_OR_LATCH 0
  #define CFL_HBIT_BUF_OR_MASK  1
  #define CFL_HBIT_BUF_AND      2
#endif

/* Buffer configurations (ROM) */
static const struct {
    uint8_t  type;
    uint16_t arena_size;
    const irrigation_valves_arena_info_t* arena_info;
} irrigation_valves_buffer_configs[3] = {
    { CFL_HBIT_BUF_OR_LATCH, IRRIGATION_VALVES_ARENA_ALARM_LATCHED_SIZE, irrigation_valves_ALARM_LATCHED_arena },  /* ALARM_LATCHED */
    { CFL_HBIT_BUF_OR_MASK, IRRIGATION_VALVES_ARENA_ALARM_MASK_SIZE, irrigation_valves_ALARM_MASK_arena },  /* ALARM_MASK */
    { CFL_HBIT_BUF_AND, IRRIGATION_VALVES_ARENA_AND_LATCHED_SIZE, irrigation_valves_AND_LATCHED_arena },  /* AND_LATCHED */
};

/* RAM size calculation:
 *   Pointer arrays: 4 * 3 * sizeof(void*)
 *   Buffer arenas: see below
 *   Dirty bits: 5 bytes
 * Note: Assumes 64-bit pointers. For 32-bit, size will be smaller. */
#define IRRIGATION_VALVES_RAM_SIZE 245

/* Complete configuration for cfl_hbit_create() */
/* Cast to (const cfl_hbit_config_t*) when calling */
static const struct {
    uint16_t node_count;
    uint16_t buffer_count;
    uint16_t root_count;
    uint16_t ram_size;
    const irrigation_valves_node_t* nodes;
    const irrigation_valves_hash_entry_t* nodes_by_hash;
    const uint16_t* roots;
    const void* buffer_configs;
} irrigation_valves_config = {
    36,  /* node_count */
    3,  /* buffer_count */
    2,  /* root_count */
    IRRIGATION_VALVES_RAM_SIZE,
    irrigation_valves_nodes_tree,
    irrigation_valves_nodes_by_hash,
    irrigation_valves_roots,
    irrigation_valves_buffer_configs,
};

#ifdef IRRIGATION_VALVES_INCLUDE_PATH_STRINGS

/* Path strings for debugging (tree order) */
static const char* irrigation_valves_node_paths[36] = {
    "VALVE_STATUS",  /* [0] */
    "VALVE_STATUS.STATION_1_VALVE_STATUS",  /* [1] */
    "VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_1_VALVE_STATUS",  /* [2] */
    "VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_2_VALVE_STATUS",  /* [3] */
    "VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_3_VALVE_STATUS",  /* [4] */
    "VALVE_STATUS.STATION_1_VALVE_STATUS.BANK_4_VALVE_STATUS",  /* [5] */
    "VALVE_STATUS.STATION_2_VALVE_STATUS",  /* [6] */
    "VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_1_VALVE_STATUS",  /* [7] */
    "VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_2_VALVE_STATUS",  /* [8] */
    "VALVE_STATUS.STATION_2_VALVE_STATUS.BANK_3_VALVE_STATUS",  /* [9] */
    "VALVE_STATUS.STATION_3_VALVE_STATUS",  /* [10] */
    "VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_1_VALVE_STATUS",  /* [11] */
    "VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_2_VALVE_STATUS",  /* [12] */
    "VALVE_STATUS.STATION_3_VALVE_STATUS.BANK_3_VALVE_STATUS",  /* [13] */
    "VALVE_STATUS.STATION_4_VALVE_STATUS",  /* [14] */
    "VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_1_VALVE_STATUS",  /* [15] */
    "VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_2_VALVE_STATUS",  /* [16] */
    "VALVE_STATUS.STATION_4_VALVE_STATUS.BANK_3_VALVE_STATUS",  /* [17] */
    "VALVE_STATE",  /* [18] */
    "VALVE_STATE.STATION_1_VALVE_STATE",  /* [19] */
    "VALVE_STATE.STATION_1_VALVE_STATE.BANK_1_VALVE_STATE",  /* [20] */
    "VALVE_STATE.STATION_1_VALVE_STATE.BANK_2_VALVE_STATE",  /* [21] */
    "VALVE_STATE.STATION_1_VALVE_STATE.BANK_3_VALVE_STATE",  /* [22] */
    "VALVE_STATE.STATION_1_VALVE_STATE.BANK_4_VALVE_STATE",  /* [23] */
    "VALVE_STATE.STATION_2_VALVE_STATE",  /* [24] */
    "VALVE_STATE.STATION_2_VALVE_STATE.BANK_1_VALVE_STATE",  /* [25] */
    "VALVE_STATE.STATION_2_VALVE_STATE.BANK_2_VALVE_STATE",  /* [26] */
    "VALVE_STATE.STATION_2_VALVE_STATE.BANK_3_VALVE_STATE",  /* [27] */
    "VALVE_STATE.STATION_3_VALVE_STATE",  /* [28] */
    "VALVE_STATE.STATION_3_VALVE_STATE.BANK_1_VALVE_STATE",  /* [29] */
    "VALVE_STATE.STATION_3_VALVE_STATE.BANK_2_VALVE_STATE",  /* [30] */
    "VALVE_STATE.STATION_3_VALVE_STATE.BANK_3_VALVE_STATE",  /* [31] */
    "VALVE_STATE.STATION_4_VALVE_STATE",  /* [32] */
    "VALVE_STATE.STATION_4_VALVE_STATE.BANK_1_VALVE_STATE",  /* [33] */
    "VALVE_STATE.STATION_4_VALVE_STATE.BANK_2_VALVE_STATE",  /* [34] */
    "VALVE_STATE.STATION_4_VALVE_STATE.BANK_3_VALVE_STATE",  /* [35] */
};

#endif /* IRRIGATION_VALVES_INCLUDE_PATH_STRINGS */

#endif /* IRRIGATION_VALVES_DATA_H */