// ============================================================================
// demo_test.h
// Generated S-expression module for demo_test
// DO NOT EDIT - Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef DEMO_TEST_H
#define DEMO_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "demo_test_records.h"

// Module: demo_test
#define DEMO_TEST_NAME_HASH 0x58015D1F
#define DEMO_TEST_TREE_COUNT 1
#define DEMO_TEST_RECORD_COUNT 1

// String table
static const char* const demo_test_strings[] = {
    "State machine test started",
    "State 0",
    "State 1",
    "State 2",
    "State 2 terminated"
};
#define DEMO_TEST_STRING_COUNT 5

// Function hashes
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_HASH 0xCEBBEFA4
#define CFL_DISABLE_CHILDREN_HASH 0x5839B05B
#define CFL_ENABLE_CHILD_HASH 0xD42E3453
#define SE_SEQUENCE_HASH 0xEC3EE7BF
#define SE_FIELD_DISPATCH_HASH 0xA1C11B35
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_RETURN_HALT_HASH 0x056FB9EA
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74

// Tree hashes
#define STATE_MACHINE_TEST_HASH 0x6824A885

// Record hashes
#define STATE_MACHINE_BLACKBOARD_HASH 0xC89D038C

// Field hashes
#define FIELD_STATE_HASH 0x783132F6

#ifdef __cplusplus
}
#endif

#endif // DEMO_TEST_H
