// ============================================================================
// s_expr_dsl_test.h
// Generated S-expression module for s_expr_dsl_test
// DO NOT EDIT - Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef S_EXPR_DSL_TEST_H
#define S_EXPR_DSL_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include "s_engine_types.h"
#include "s_expr_dsl_test_records.h"

// Module: s_expr_dsl_test
#define S_EXPR_DSL_TEST_NAME_HASH 0x7BB33CC5
#define S_EXPR_DSL_TEST_TREE_COUNT 1
#define S_EXPR_DSL_TEST_RECORD_COUNT 1

// String table
static const char* const s_expr_dsl_test_strings[] = {
    "State machine test started",
    "State 0",
    "State 1",
    "State 2",
    "State 2 terminated"
};
#define S_EXPR_DSL_TEST_STRING_COUNT 5

// Function hashes
#define SE_SET_FIELD_HASH 0xFFF84A15
#define SE_LOG_HASH 0xCEBBEFA4
#define CFL_DISABLE_CHILDREN_HASH 0x5839B05B
#define CFL_ENABLE_CHILD_HASH 0xD42E3453
#define SE_SEQUENCE_HASH 0xEC3EE7BF
#define SE_STATE_MACHINE_HASH 0x5EEDA8E9
#define SE_TICK_DELAY_HASH 0x0C3460EB
#define SE_RETURN_HALT_HASH 0x056FB9EA
#define SE_RETURN_TERMINATE_HASH 0xDFE64C74

// Tree hashes
#define STATE_MACHINE_TEST_HASH 0x6824A885

// Record hashes
#define STATE_MACHINE_BLACKBOARD_HASH 0xC89D038C

// Field hashes
#define FIELD_STATE_HASH 0x783132F6

#ifdef __cplusplus
}
#endif

#endif // S_EXPR_DSL_TEST_H
