/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef INCR_BUILD_H
#define INCR_BUILD_H

#include "chaintree_support.h"
#include "incr_build_nodes.h"
#include "incr_build_links.h"
#include "incr_build_events.h"
#include "incr_build_bitmasks.h"
#include "incr_build_kb_info.h"
#include "incr_build_node_data.h"
#include "incr_build_functions.h"

extern const chaintree_handle_t g_incr_build;

#endif /* INCR_BUILD_H */