// streaming_test_1.h
// Generated by avro_dsl.lua - DO NOT EDIT
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "avro_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============ FILE METADATA ============
#define STREAMING_TEST_1_RECORD_COUNT  1
#define STREAMING_TEST_1_SCHEMA_FILE   "streaming_test_1.h"

// ============ RECORDS ============
typedef struct {
    float x;
    float y;
    float z;
} accelerometer_reading_t;

// ============ WIRE PACKETS ============
// Per-record packet types with unified header (packed largest to smallest)

typedef struct {
    // --- Wire Header ---
    const char* schema_file;   // schema .h file name
    double      timestamp;     // message timestamp (set by transport)
    uint32_t    seq;           // sequence number (set by transport)
    uint16_t    source_node;   // originating node ID
    uint16_t    length;        // payload size
    uint8_t     index;         // record type index
    // --- Payload ---
    accelerometer_reading_t        data;          // payload
} accelerometer_reading_packet_t;

// Packet encode helpers - populate header and return pointer to data
// Note: seq and timestamp are zeroed; set by transport layer before sending
static inline accelerometer_reading_t* accelerometer_reading_packet_encode(
        accelerometer_reading_packet_t* pkt,
        uint16_t source_node)
{
    pkt->schema_file = STREAMING_TEST_1_SCHEMA_FILE;
    pkt->timestamp = 0.0;
    pkt->seq = 0;
    pkt->source_node = source_node;
    pkt->length = sizeof(accelerometer_reading_t);
    pkt->index = 0;
    return &pkt->data;
}

// Packet verify helpers - validate and return data pointer
// Note: seq and timestamp accessible via get_packet_header() if needed
static inline const accelerometer_reading_t* accelerometer_reading_packet_verify(
        const void* packet_buffer,
        uint16_t* source_node)
{
    const accelerometer_reading_packet_t* pkt = (const accelerometer_reading_packet_t*)packet_buffer;
    
    // Verify schema file
    if (strcmp(pkt->schema_file, STREAMING_TEST_1_SCHEMA_FILE) != 0) return NULL;
    
    // Verify packet type
    if (pkt->index != 0) return NULL;
    
    // Verify payload size
    if (pkt->length != sizeof(accelerometer_reading_t)) return NULL;
    
    // Extract source node
    if (source_node) *source_node = pkt->source_node;
    
    return &pkt->data;
}


#ifdef __cplusplus
}
#endif
