/**
 * json_record_reader.h
 * 
 * Core JSON record reader - cursor-based navigation of pre-compiled JSON records.
 * Works with ROM-resident data generated by JsonRecordEncoder (Python).
 * 
 * Features:
 *   - Zero allocation - operates on const data
 *   - Cursor-based traversal
 *   - Array iteration
 *   - Object key lookup
 *   - Skip functions for nested containers
 * 
 * Usage:
 *   json_reader_t reader;
 *   json_reader_init(&reader, json_records, JSON_RECORDS_COUNT, string_table);
 *   
 *   json_cursor_t c;
 *   json_cursor_init(&c, &reader, &record_controls[0]);
 *   
 *   const char* name = json_object_get_string(&c, "name");
 */

 #ifndef CFL_JSON_RECORD_READER_H
 #define CFL_JSON_RECORD_READER_H
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 #include <stdint.h>
 #include <stdbool.h>
 #include <string.h>
 #include "cfl_exception.h"
 
 typedef enum {
     JSON_TYPE_STRING = 0,
     JSON_TYPE_INT32 = 1,
     JSON_TYPE_FLOAT32 = 2,
     JSON_TYPE_NULL = 3,
     JSON_TYPE_BOOL = 4,
     JSON_TYPE_ARRAY = 5,
     JSON_TYPE_OBJECT = 6
 } json_type_t;
 
 typedef struct {
     json_type_t object_type;
     union {
         uint32_t string_offset;
         int32_t  i32_value;
         float    f32_value;
         uint8_t  bool_value;
         uint32_t container_count;
     } value;
 } json_record_t;
 
 typedef struct {
     uint32_t start_position;
     uint32_t num_records;
 } record_control_t;
 
 // Complete data descriptor - contains everything needed to read JSON
 typedef struct {
     const json_record_t* records;
     const char* strings;
     uint32_t record_count;
     uint32_t string_size;
     uint32_t node_count;    // Number of ChainTree nodes (objects with "type" field)
 } json_data_t;
 
 typedef struct {
     const json_record_t* records;
     const char* string_table;
     uint32_t record_count;
 } json_reader_t;
 
 typedef struct {
     const json_reader_t* reader;
     uint32_t pos;
     uint32_t end;
 } json_cursor_t;
 
 //=============================================================================
 // Core API
 //=============================================================================
 
 static inline void json_reader_init(json_reader_t* r, 
                                     const json_record_t* records,
                                     uint32_t record_count,
                                     const char* string_table) {
     if (!r) { EXCEPTION("json_reader_init: null reader"); return; }
     if (!records) { EXCEPTION("json_reader_init: null records"); return; }
     if (!string_table) { EXCEPTION("json_reader_init: null string_table"); return; }
     
     r->records = records;
     r->string_table = string_table;
     r->record_count = record_count;
 }
 
 // Initialize reader from json_data_t descriptor
 static inline void json_reader_init_from_data(json_reader_t* r, const json_data_t* data) {
     if (!r) { EXCEPTION("json_reader_init_from_data: null reader"); return; }
     if (!data) { EXCEPTION("json_reader_init_from_data: null data"); return; }
     
     r->records = data->records;
     r->string_table = data->strings;
     r->record_count = data->record_count;
 }
 
 static inline void json_cursor_init(json_cursor_t* c, 
                                     const json_reader_t* r,
                                     const record_control_t* ctrl) {
     if (!c) { EXCEPTION("json_cursor_init: null cursor"); return; }
     if (!r) { EXCEPTION("json_cursor_init: null reader"); return; }
     if (!ctrl) { EXCEPTION("json_cursor_init: null control"); return; }
     
     c->reader = r;
     c->pos = ctrl->start_position;
     c->end = ctrl->start_position + ctrl->num_records;
 }
 
 // Initialize cursor from json_data_t (starts at beginning, spans all records)
 static inline void json_cursor_init_from_data(json_cursor_t* c,
                                                json_reader_t* r,
                                                const json_data_t* data) {
     if (!c) { EXCEPTION("json_cursor_init_from_data: null cursor"); return; }
     if (!r) { EXCEPTION("json_cursor_init_from_data: null reader"); return; }
     if (!data) { EXCEPTION("json_cursor_init_from_data: null data"); return; }
     
     json_reader_init_from_data(r, data);
     c->reader = r;
     c->pos = 0;
     c->end = data->record_count;
 }
 
 static inline void json_cursor_from_range(json_cursor_t* c,
                                           const json_reader_t* r,
                                           uint32_t start, uint32_t count) {
     if (!c) { EXCEPTION("json_cursor_from_range: null cursor"); return; }
     if (!r) { EXCEPTION("json_cursor_from_range: null reader"); return; }
     
     c->reader = r;
     c->pos = start;
     c->end = start + count;
 }
 
 static inline bool json_cursor_valid(const json_cursor_t* c) {
     return c && c->pos < c->end;
 }
 
 static inline const json_record_t* json_cursor_get(const json_cursor_t* c) {
     if (!c) { EXCEPTION("json_cursor_get: null cursor"); return NULL; }
     if (c->pos >= c->end) { EXCEPTION("json_cursor_get: cursor past end"); return NULL; }
     
     return &c->reader->records[c->pos];
 }
 
 static inline json_type_t json_cursor_type(const json_cursor_t* c) {
     if (!c) { EXCEPTION("json_cursor_type: null cursor"); return JSON_TYPE_NULL; }
     if (c->pos >= c->end) { EXCEPTION("json_cursor_type: cursor past end"); return JSON_TYPE_NULL; }
     
     return c->reader->records[c->pos].object_type;
 }
 
 static inline const char* json_get_string(const json_cursor_t* c) {
     if (!c) { EXCEPTION("json_get_string: null cursor"); return NULL; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_STRING) {
         EXCEPTION("json_get_string: not a string");
         return NULL;
     }
     return c->reader->string_table + rec->value.string_offset;
 }
 
 static inline int32_t json_get_int(const json_cursor_t* c, int32_t def) {
     if (!c) { EXCEPTION("json_get_int: null cursor"); return def; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_INT32) return def;
     return rec->value.i32_value;
 }
 
 static inline float json_get_float(const json_cursor_t* c, float def) {
     if (!c) { EXCEPTION("json_get_float: null cursor"); return def; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type == JSON_TYPE_FLOAT32) return rec->value.f32_value;
     if (rec->object_type == JSON_TYPE_INT32) return (float)rec->value.i32_value;
     return def;
 }
 
 static inline bool json_get_bool(const json_cursor_t* c, bool def) {
     if (!c) { EXCEPTION("json_get_bool: null cursor"); return def; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_BOOL) return def;
     return rec->value.bool_value != 0;
 }
 
 //=============================================================================
 // Skip functions
 //=============================================================================
 
 static inline uint32_t json_skip_value(const json_reader_t* r, uint32_t pos) {
     if (!r) { EXCEPTION("json_skip_value: null reader"); return pos; }
     if (pos >= r->record_count) { EXCEPTION("json_skip_value: pos out of bounds"); return pos; }
     
     const json_record_t* rec = &r->records[pos];
     
     switch (rec->object_type) {
         case JSON_TYPE_ARRAY: {
             uint32_t count = rec->value.container_count;
             pos++;
             for (uint32_t i = 0; i < count; i++) {
                 pos = json_skip_value(r, pos);
             }
             return pos;
         }
         case JSON_TYPE_OBJECT: {
             uint32_t count = rec->value.container_count;
             pos++;
             for (uint32_t i = 0; i < count; i++) {
                 pos = json_skip_value(r, pos);
             }
             return pos;
         }
         default:
             return pos + 1;
     }
 }
 
 static inline void json_cursor_skip(json_cursor_t* c) {
     if (!c) { EXCEPTION("json_cursor_skip: null cursor"); return; }
     c->pos = json_skip_value(c->reader, c->pos);
 }
 
 //=============================================================================
 // Object navigation
 //=============================================================================
 
 static inline bool json_object_find(json_cursor_t* c, const char* key) {
     if (!c) { EXCEPTION("json_object_find: null cursor"); return false; }
     if (!key) { EXCEPTION("json_object_find: null key"); return false; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_OBJECT) return false;
     
     uint32_t count = rec->value.container_count / 2;
     uint32_t pos = c->pos + 1;
     
     for (uint32_t i = 0; i < count; i++) {
         const char* k = c->reader->string_table + c->reader->records[pos].value.string_offset;
         pos++;
         
         if (strcmp(k, key) == 0) {
             c->pos = pos;
             return true;
         }
         pos = json_skip_value(c->reader, pos);
     }
     return false;
 }
 
 static inline const char* json_object_get_string(json_cursor_t* c, const char* key) {
     json_cursor_t temp = *c;
     if (json_object_find(&temp, key)) {
         return json_get_string(&temp);
     }
     return NULL;
 }
 
 static inline int32_t json_object_get_int(json_cursor_t* c, const char* key, int32_t def) {
     json_cursor_t temp = *c;
     if (json_object_find(&temp, key)) {
         return json_get_int(&temp, def);
     }
     return def;
 }
 
 static inline float json_object_get_float(json_cursor_t* c, const char* key, float def) {
     json_cursor_t temp = *c;
     if (json_object_find(&temp, key)) {
         return json_get_float(&temp, def);
     }
     return def;
 }
 
 static inline bool json_object_get_bool(json_cursor_t* c, const char* key, bool def) {
     json_cursor_t temp = *c;
     if (json_object_find(&temp, key)) {
         return json_get_bool(&temp, def);
     }
     return def;
 }
 
 //=============================================================================
 // Array iteration
 //=============================================================================
 
 typedef struct {
     json_cursor_t cursor;
     uint32_t count;
     uint32_t index;
 } json_array_iter_t;
 
 static inline bool json_array_iter_init(json_array_iter_t* it, json_cursor_t* c) {
     if (!it) { EXCEPTION("json_array_iter_init: null iterator"); return false; }
     if (!c) { EXCEPTION("json_array_iter_init: null cursor"); return false; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_ARRAY) return false;
     
     it->cursor = *c;
     it->cursor.pos++;
     it->count = rec->value.container_count;
     it->index = 0;
     return true;
 }
 
 static inline bool json_array_iter_next(json_array_iter_t* it, json_cursor_t* out) {
     if (!it) { EXCEPTION("json_array_iter_next: null iterator"); return false; }
     if (!out) { EXCEPTION("json_array_iter_next: null output"); return false; }
     
     if (it->index >= it->count) return false;
     
     *out = it->cursor;
     json_cursor_skip(&it->cursor);
     it->index++;
     return true;
 }
 
 static inline uint32_t json_array_count(json_cursor_t* c) {
     if (!c) { EXCEPTION("json_array_count: null cursor"); return 0; }
     
     const json_record_t* rec = &c->reader->records[c->pos];
     if (rec->object_type != JSON_TYPE_ARRAY) return 0;
     return rec->value.container_count;
 }
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif // CFL_JSON_RECORD_READER_H