/**
 * chaintree_from_json.h
 * 
 * Build ChainTree from pre-compiled JSON records.
 * 
 * Usage:
 *   #include "my_tree_data.h"  // Generated by json_record_encoder.py
 *   
 *   json_reader_t reader;
 *   json_reader_init(&reader, json_records, JSON_RECORDS_COUNT, string_table);
 *   
 *   static ct_node_t node_buffer[64];
 *   ct_tree_t tree;
 *   
 *   ct_build_from_records(&tree, node_buffer, 64, &reader, &record_controls[0]);
 *   
 *   // Use tree...
 *   ct_dump_tree(&tree);
 * 
 * Expected JSON format:
 *   {
 *     "type": "sequence",
 *     "name": "root",
 *     "handler_id": 0,
 *     "flags": 0,
 *     "children": [
 *       { "type": "action", "name": "child1", "handler_id": 1 },
 *       { "type": "condition", "name": "child2", "handler_id": 2 }
 *     ]
 *   }
 */

 #ifndef CFL_CHAIN_TREE_FROM_JSON_H
 #define CFL_CHAIN_TREE_FROM_JSON_H
 
 #include "cfl_json_record_reader.h"
 #include "cfl_json_path.h"
 #include "cfl_chain_tree_nodes.h"
 #include "cfl_exception.h"
 #include <stdio.h>
 
 #ifndef CT_EX_MSG_SIZE
 #define CT_EX_MSG_SIZE 96
 #endif
 
 static char ct_ex_msg_buf[CT_EX_MSG_SIZE];
 
 typedef struct {
     ct_node_t* nodes;
     uint16_t capacity;
     uint16_t count;
 } ct_builder_t;
 
 //=============================================================================
 // Node parsing
 //=============================================================================
 
 static uint16_t ct_parse_node(ct_builder_t* b, json_cursor_t* c, 
                                uint16_t parent, uint16_t depth);
 
 static uint16_t ct_parse_node(ct_builder_t* b, json_cursor_t* c, 
                                uint16_t parent, uint16_t depth) {
     if (!b) { EXCEPTION("ct_parse_node: null builder"); return CT_NO_LINK; }
     if (!c) { EXCEPTION("ct_parse_node: null cursor"); return CT_NO_LINK; }
     
     if (depth >= 32) {
         snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, "ct_parse_node: max depth %u exceeded", depth);
         EXCEPTION(ct_ex_msg_buf);
         return CT_NO_LINK;
     }
     
     if (b->count >= b->capacity) {
         snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, "ct_parse_node: buffer full (%u/%u)", 
                  b->count, b->capacity);
         EXCEPTION(ct_ex_msg_buf);
         return CT_NO_LINK;
     }
     
     uint16_t idx = b->count++;
     ct_node_t* n = &b->nodes[idx];
     
     // Store position for attached data access
     n->data_pos = c->pos;
     
     // Required: type
     const char* type_str = json_path_string(c, "type", NULL);
     if (!type_str) {
         const char* node_name = json_path_string(c, "name", "(unnamed)");
         snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, "ct_parse_node: missing 'type' in node '%s'", node_name);
         EXCEPTION(ct_ex_msg_buf);
         return CT_NO_LINK;
     }
     n->type = ct_type_from_string(type_str);
     
     // Optional fields
     n->name       = json_path_string(c, "name", NULL);
     n->handler_id = (uint16_t)json_path_int(c, "handler_id", 0);
     n->flags      = (uint16_t)json_path_int(c, "flags", 0);
     n->parent     = parent;
     n->first_child = CT_NO_LINK;
     n->next_sibling = CT_NO_LINK;
     
     // Process children if present
     json_cursor_t children_c;
     if (json_path_cursor(c, "children", &children_c) == JSON_PATH_OK &&
         json_cursor_type(&children_c) == JSON_TYPE_ARRAY) {
         
         json_array_iter_t it;
         if (json_array_iter_init(&it, &children_c)) {
             json_cursor_t child_c;
             uint16_t prev = CT_NO_LINK;
             uint16_t child_index = 0;
             
             while (json_array_iter_next(&it, &child_c)) {
                 uint16_t child_idx = ct_parse_node(b, &child_c, idx, depth + 1);
                 if (child_idx == CT_NO_LINK) {
                     snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, 
                              "ct_parse_node: failed parsing child[%u] of '%s'",
                              child_index, n->name ? n->name : "(unnamed)");
                     EXCEPTION(ct_ex_msg_buf);
                     break;
                 }
                 
                 if (n->first_child == CT_NO_LINK) {
                     n->first_child = child_idx;
                 } else {
                     b->nodes[prev].next_sibling = child_idx;
                 }
                 prev = child_idx;
                 child_index++;
             }
         }
     }
     
     return idx;
 }
 
 //=============================================================================
 // Main entry points
 //=============================================================================
 
 static inline bool ct_build_from_records(ct_tree_t* tree,
                                          ct_node_t* node_buffer,
                                          uint16_t buffer_capacity,
                                          const json_reader_t* reader,
                                          const record_control_t* ctrl) {
     if (!tree) { EXCEPTION("ct_build: null tree"); return false; }
     if (!node_buffer) { EXCEPTION("ct_build: null buffer"); return false; }
     if (!reader) { EXCEPTION("ct_build: null reader"); return false; }
     if (!ctrl) { EXCEPTION("ct_build: null control"); return false; }
     if (buffer_capacity == 0) { EXCEPTION("ct_build: zero capacity"); return false; }
     
     ct_builder_t builder = {
         .nodes = node_buffer,
         .capacity = buffer_capacity,
         .count = 0
     };
     
     json_cursor_t c;
     json_cursor_init(&c, reader, ctrl);
     
     uint16_t root = ct_parse_node(&builder, &c, CT_NO_LINK, 0);
     
     if (root == CT_NO_LINK || builder.count == 0) {
         snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, 
                  "ct_build: no nodes parsed (ctrl start=%u, num=%u)",
                  ctrl->start_position, ctrl->num_records);
         EXCEPTION(ct_ex_msg_buf);
         return false;
     }
     
     tree->nodes = node_buffer;
     tree->node_count = builder.count;
     tree->root_index = root;
     tree->data = NULL;  // No attached data access with this API
     
     return true;
 }
 
 // Simplified entry point using json_data_t
 static inline bool ct_build_from_data(ct_tree_t* tree,
                                       ct_node_t* node_buffer,
                                       uint16_t buffer_capacity,
                                       const json_data_t* data) {
     if (!tree) { EXCEPTION("ct_build_from_data: null tree"); return false; }
     if (!node_buffer) { EXCEPTION("ct_build_from_data: null buffer"); return false; }
     if (!data) { EXCEPTION("ct_build_from_data: null data"); return false; }
     if (buffer_capacity == 0) { EXCEPTION("ct_build_from_data: zero capacity"); return false; }
     
     ct_builder_t builder = {
         .nodes = node_buffer,
         .capacity = buffer_capacity,
         .count = 0
     };
     
     json_reader_t reader;
     json_cursor_t c;
     json_cursor_init_from_data(&c, &reader, data);
     
     uint16_t root = ct_parse_node(&builder, &c, CT_NO_LINK, 0);
     
     if (root == CT_NO_LINK || builder.count == 0) {
         snprintf(ct_ex_msg_buf, CT_EX_MSG_SIZE, 
                  "ct_build_from_data: no nodes parsed (count=%u)",
                  data->record_count);
         EXCEPTION(ct_ex_msg_buf);
         return false;
     }
     
     tree->nodes = node_buffer;
     tree->node_count = builder.count;
     tree->root_index = root;
     tree->data = data;  // Store for attached data access
     
     return true;
 }
 
 //=============================================================================
 // Attached data access
 //=============================================================================
 
 /**
  * Initialize cursor to access attached data on a node.
  * 
  * Example:
  *   json_reader_t reader;
  *   json_cursor_t c;
  *   if (ct_node_data(&tree, node, &reader, &c)) {
  *       int32_t timeout = json_path_int(&c, "timeout_ms", 1000);
  *       const char* id = json_path_string(&c, "sensor_id", NULL);
  *   }
  * 
  * Returns false if tree has no data pointer or node is NULL.
  */
 static inline bool ct_node_data(const ct_tree_t* tree, 
                                  const ct_node_t* node,
                                  json_reader_t* reader,
                                  json_cursor_t* cursor) {
     if (!tree || !node || !reader || !cursor) return false;
     if (!tree->data) return false;
     
     const json_data_t* data = (const json_data_t*)tree->data;
     
     json_reader_init_from_data(reader, data);
     
     // Create cursor starting at node's data position
     cursor->reader = reader;
     cursor->pos = node->data_pos;
     
     // Calculate end position by skipping this object
     cursor->end = json_skip_value(reader, node->data_pos);
     
     return true;
 }
 
 //=============================================================================
 // Debug helpers
 //=============================================================================
 
 static inline void ct_dump_tree(const ct_tree_t* tree) {
     if (!tree) { EXCEPTION("ct_dump_tree: null tree"); return; }
     
     printf("ChainTree: %u nodes, root=%u\n", tree->node_count, tree->root_index);
     printf("--------------------------------------------------------------------------------\n");
     printf(" Idx  Type       Name             Handler  Parent  Child  Sibling  Flags\n");
     printf("--------------------------------------------------------------------------------\n");
     
     for (uint16_t i = 0; i < tree->node_count; i++) {
         const ct_node_t* n = &tree->nodes[i];
         printf(" %3u  %-9s  %-16s  %5u   %5u  %5u    %5u   0x%04X\n",
                i, 
                ct_type_name(n->type),
                n->name ? n->name : "(null)", 
                n->handler_id, 
                n->parent == CT_NO_LINK ? 9999 : n->parent,
                n->first_child == CT_NO_LINK ? 9999 : n->first_child,
                n->next_sibling == CT_NO_LINK ? 9999 : n->next_sibling,
                n->flags);
     }
     printf("--------------------------------------------------------------------------------\n");
 }
 
 // Recursive tree printer with indentation
 static inline void ct_print_node(const ct_tree_t* tree, uint16_t index, int indent) {
     if (!tree || index >= tree->node_count) return;
     
     const ct_node_t* n = &tree->nodes[index];
     
     for (int i = 0; i < indent; i++) printf("  ");
     printf("%s", ct_type_name(n->type));
     if (n->name) printf(" \"%s\"", n->name);
     if (n->handler_id) printf(" handler=%u", n->handler_id);
     if (n->flags) printf(" flags=0x%X", n->flags);
     printf("\n");
     
     // Print children
     uint16_t child = n->first_child;
     while (child != CT_NO_LINK && child < tree->node_count) {
         ct_print_node(tree, child, indent + 1);
         child = tree->nodes[child].next_sibling;
     }
 }
 
 static inline void ct_print_tree(const ct_tree_t* tree) {
     if (!tree) { EXCEPTION("ct_print_tree: null tree"); return; }
     printf("ChainTree (%u nodes):\n", tree->node_count);
     ct_print_node(tree, tree->root_index, 0);
 }
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif // CFL_CHAIN_TREE_FROM_JSON_H