/* Auto-generated by ChainTree Pipeline (Binary) - Blackboard offsets */
#ifndef ROBOT_HANDLE_BLACKBOARD_H
#define ROBOT_HANDLE_BLACKBOARD_H

#include "cfl_blackboard.h"

/* ===== Blackboard: remote_state ===== */
#define BB_REMOTE_STATE_SIZE 100

#define BB_CONTROLLER_ACTIVE_OFFSET              0
#define BB_CURRENT_PACKET_TYPE_OFFSET            4
#define BB_CURRENT_TEST_ID_OFFSET                8
#define BB_CURRENT_SEQ_OFFSET                    12
#define BB_CURRENT_MAX_TIME_OFFSET               16
#define BB_ACTIVE_WORKER_IDX_OFFSET              20
#define BB_WATCHDOG_TICKS_OFFSET                 24
#define BB_WATCHDOG_EXPIRED_OFFSET               28
#define BB_HEARTBEAT_COUNTER_OFFSET              32
#define BB_HEARTBEAT_INTERVAL_OFFSET             36
#define BB_EXEC_ACTIVE_OFFSET                    40
#define BB_EXEC_START_OFFSET                     42
#define BB_TICKS_REMAINING_OFFSET                44
#define BB_DELTA_X_OFFSET                        48
#define BB_DELTA_Y_OFFSET                        52
#define BB_DELTA_Z_OFFSET                        56
#define BB_DELTA_HEADING_OFFSET                  60
#define BB_DELTA_ARM_ANGLE_OFFSET                64
#define BB_WORKER_DONE_OFFSET                    68
#define BB_WORKER_SUCCESS_OFFSET                 70
#define BB_LOOKAHEAD_PENDING_OFFSET              72
#define BB_LOOKAHEAD_PACKET_TYPE_OFFSET          76
#define BB_LOOKAHEAD_TEST_ID_OFFSET              80
#define BB_LOOKAHEAD_SEQ_OFFSET                  84
#define BB_LOOKAHEAD_MAX_TIME_OFFSET             88
#define BB_SHUTDOWN_REQUESTED_OFFSET             92
#define BB_FAULT_CODE_OFFSET                     96

#endif /* ROBOT_HANDLE_BLACKBOARD_H */
