--[[
  stage6_codegen.lua - Generate all .h and .c files from pipeline data.
  LuaJIT port of stage6_codegen.py
  
  Generates 9 matched pairs:
    - chaintree_support.h/.c    (generic runtime)
    - {name}.h/.c               (instance handle)
    - {name}_nodes.h/.c         (node array)
    - {name}_functions.h/.c     (function tables)
    - {name}_links.h/.c         (link table)
    - {name}_node_data.h/.c     (JSON record data)
    - {name}_events.h/.c        (event string table)
    - {name}_bitmasks.h/.c      (bitmask definitions)
    - {name}_kb_info.h/.c       (knowledge base info)
--]]

local CCodeGenerator = {}
CCodeGenerator.__index = CCodeGenerator

function CCodeGenerator.new(opts)
    local self = setmetatable({}, CCodeGenerator)
    self.output_dir = opts.output_dir
    self.handle_name = opts.handle_name
    self.unique_id = opts.unique_id
    self.handle = opts.handle
    self.node_builder = opts.node_builder
    self.function_builder = opts.function_builder
    self.link_builder = opts.link_builder
    self.data_encoder = opts.data_encoder       -- may be nil
    self.main_function_usage = opts.main_function_usage
    self.generate_support = opts.generate_support
    return self
end

-- =========================================================================
-- Helpers
-- =========================================================================

local function sorted_pairs_by_value(tbl)
    local items = {}
    for k, v in pairs(tbl) do items[#items + 1] = { k, v } end
    table.sort(items, function(a, b) return a[2] < b[2] end)
    local i = 0
    return function()
        i = i + 1
        if items[i] then return items[i][1], items[i][2] end
    end
end

local function sorted_pairs_by_key(tbl)
    local items = {}
    for k, v in pairs(tbl) do items[#items + 1] = { k, v } end
    table.sort(items, function(a, b) return tostring(a[1]) < tostring(b[1]) end)
    local i = 0
    return function()
        i = i + 1
        if items[i] then return items[i][1], items[i][2] end
    end
end

local function safe_name(s)
    return s:upper():gsub(" ", "_"):gsub("-", "_")
end

local function table_len(t)
    local n = 0
    for _ in pairs(t) do n = n + 1 end
    return n
end

function CCodeGenerator:_filter_executable_kbs(all_kb_names)
    local executable = {}
    local filtered = {}
    for _, kb in ipairs(all_kb_names) do
        if kb:match("_test_functions$") or kb == "complete_functions_kb" then
            filtered[#filtered + 1] = kb
        else
            executable[#executable + 1] = kb
        end
    end
    if #filtered > 0 then
        print(string.format("\n  Note: Filtered out %d function mapping KB(s):", #filtered))
        for _, kb in ipairs(filtered) do
            print("    - " .. kb)
        end
    end
    return executable
end

function CCodeGenerator:_write(filename, lines)
    local path = self.output_dir .. "/" .. filename
    local f = io.open(path, "w")
    if not f then error("Cannot open for writing: " .. path) end
    f:write(table.concat(lines, "\n"))
    f:close()
    print("  Generated: " .. path)
end

-- =========================================================================
-- Public Entry Points
-- =========================================================================

function CCodeGenerator:generate_all()
    self:generate_headers()
    self:generate_implementations()
end

function CCodeGenerator:generate_headers()
    if self.generate_support then self:_gen_support_header() end
    self:_gen_instance_header()
    self:_gen_node_struct_header()
    self:_gen_function_headers()
    self:_gen_link_table_header()
    if self.data_encoder then self:_gen_node_data_header() end
    self:_gen_event_table_header()
    self:_gen_bitmask_table_header()
    self:_gen_kb_info_header()
end

function CCodeGenerator:generate_implementations()
    self:_gen_handle_implementation()
    if self.generate_support then self:_gen_support_implementation() end
    self:_gen_function_implementations()
    self:_gen_node_array_implementation()
    self:_gen_link_table_implementation()
    if self.data_encoder then self:_gen_node_data_implementation() end
    self:_gen_event_table_implementation()
    self:_gen_bitmask_table_implementation()
    self:_gen_kb_info_implementation()
end

-- =========================================================================
-- Support Header / Implementation
-- =========================================================================

function CCodeGenerator:_gen_support_header()
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) - Generic Runtime */",
        "#ifndef CHAINTREE_SUPPORT_H",
        "#define CHAINTREE_SUPPORT_H",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "",
        "/* ===== Function Pointer Types ===== */",
        "typedef unsigned (*main_function_t)(void *handle, unsigned bool_function_index,",
        "    unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);",
        "typedef void (*one_shot_function_t)(void *handle, unsigned node_index);",
        "typedef bool (*boolean_function_t)(void *handle, unsigned node_index,",
        "    unsigned event_type, unsigned event_id, void *event_data);",
        "",
        "/* ===== Node Structure ===== */",
        "typedef struct {",
        "    uint16_t node_index;",
        "    uint16_t parent_index;",
        "    uint16_t depth;",
        "    uint16_t link_start;",
        "    uint16_t link_count;          /* Bits 0-14: count, Bit 15: auto_start flag */",
        "    uint16_t main_function_index;",
        "    uint16_t init_function_index;",
        "    uint16_t aux_function_index;",
        "    uint16_t term_function_index;",
        "    uint16_t node_data_id;",
        "} chaintree_node_t;",
        "",
        "/* ===== Link Count Bit Packing Macros ===== */",
        "#define LINK_COUNT_MASK     0x7FFF",
        "#define AUTO_START_BIT      0x8000",
        "",
        "#define GET_LINK_COUNT(node)     ((node)->link_count & LINK_COUNT_MASK)",
        "#define GET_AUTO_START(node)     (((node)->link_count & AUTO_START_BIT) != 0)",
        "#define PACK_LINK_COUNT(count, auto_start) \\",
        "    (((count) & LINK_COUNT_MASK) | ((auto_start) ? AUTO_START_BIT : 0))",
        "",
        "/* ===== Node Alias Structure ===== */",
        "typedef struct {",
        "    const char *alias;",
        "    uint16_t node_index;",
        "} node_alias_t;",
        "",
        "/* ===== Knowledge Base Info ===== */",
        "typedef struct {",
        "    const char *kb_name;",
        "    uint16_t root_node_index;",
        "    uint16_t start_index;",
        "    uint16_t node_count;",
        "    uint16_t max_depth;",
        "    uint16_t memory_factor;",
        "    const node_alias_t *aliases;",
        "    uint16_t alias_count;",
        "} chaintree_kb_info_t;",
        "",
        "/* ===== Node Data Structures ===== */",
        "typedef enum {",
        "    JSON_TYPE_STRING = 0,",
        "    JSON_TYPE_INT32 = 1,",
        "    JSON_TYPE_FLOAT32 = 2,",
        "    JSON_TYPE_NULL = 3,",
        "    JSON_TYPE_BOOL = 4,",
        "    JSON_TYPE_ARRAY = 5,",
        "    JSON_TYPE_OBJECT = 6",
        "} json_type_t;",
        "",
        "typedef struct {",
        "    json_type_t object_type;",
        "    union {",
        "        uint32_t string_offset;",
        "        int32_t i32_value;",
        "        float f32_value;",
        "        uint8_t bool_value;",
        "        uint32_t container_count;",
        "    } value;",
        "} json_record_t;",
        "",
        "typedef struct {",
        "    uint32_t start_position;",
        "    uint32_t num_records;",
        "} record_control_t;",
        "",
        "/* ===== Handle Structure ===== */",
        "typedef struct {",
        "    const char *unique_id;",
        "    const chaintree_node_t *nodes;",
        "    uint16_t node_count;",
        "    const main_function_t *main_functions;",
        "    uint16_t main_function_count;",
        "    const one_shot_function_t *one_shot_functions;",
        "    uint16_t one_shot_function_count;",
        "    const boolean_function_t *boolean_functions;",
        "    uint16_t boolean_function_count;",
        "    const char **main_function_names;",
        "    const char **one_shot_function_names;",
        "    const char **boolean_function_names;",
        "    const uint16_t *main_function_usage_count;",
        "    const uint16_t *link_table;",
        "    uint16_t link_table_size;",
        "    const char **event_strings;",
        "    uint16_t event_count;",
        "    const char **bitmask_names;",
        "    uint16_t bitmask_count;",
        "    const chaintree_kb_info_t *kb_table;",
        "    uint16_t kb_count;",
        "    const json_record_t *node_data_records;",
        "    uint16_t node_data_records_count;",
        "    const char *node_data_strings;",
        "    uint16_t node_data_strings_size;",
        "    const record_control_t *node_data_controls;",
        "    uint16_t node_data_controls_count;",
        "} chaintree_handle_t;",
        "",
        "/* ===== Generic Lookup Functions ===== */",
        "const char* ct_get_main_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
        "int ct_get_main_function_index(const chaintree_handle_t *handle, const char *func_name);",
        "const char* ct_get_one_shot_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
        "int ct_get_one_shot_function_index(const chaintree_handle_t *handle, const char *func_name);",
        "const char* ct_get_boolean_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
        "int ct_get_boolean_function_index(const chaintree_handle_t *handle, const char *func_name);",
        "const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index);",
        "int ct_get_event_index(const chaintree_handle_t *handle, const char *name);",
        "const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index);",
        "int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name);",
        "uint16_t ct_get_kb_count(const chaintree_handle_t *handle);",
        "",
        "#endif /* CHAINTREE_SUPPORT_H */"
    }
    self:_write("chaintree_support.h", lines)
end

function CCodeGenerator:_gen_support_implementation()
    local lines = {
        '/* Auto-generated by ChainTree Pipeline (LuaJIT) - Generic Support Functions */',
        '#include "chaintree_support.h"',
        '#include <string.h>',
        "",
    }

    local func_types = {
        { "main_function",    "main_function_count",    "main_function_names"    },
        { "one_shot_function","one_shot_function_count", "one_shot_function_names" },
        { "boolean_function", "boolean_function_count",  "boolean_function_names"  },
    }

    for _, ft in ipairs(func_types) do
        local label, count_field, names_field = ft[1], ft[2], ft[3]
        -- get name by index
        lines[#lines + 1] = string.format("const char* ct_get_%s_name(const chaintree_handle_t *handle, uint16_t func_index) {", label)
        lines[#lines + 1] = string.format("    if (handle == NULL || handle->%s == NULL) return NULL;", names_field)
        lines[#lines + 1] = string.format("    if (func_index >= handle->%s) return NULL;", count_field)
        lines[#lines + 1] = string.format("    return handle->%s[func_index];", names_field)
        lines[#lines + 1] = "}"
        lines[#lines + 1] = ""
        -- get index by name
        lines[#lines + 1] = string.format("int ct_get_%s_index(const chaintree_handle_t *handle, const char *func_name) {", label)
        lines[#lines + 1] = string.format("    if (handle == NULL || func_name == NULL || handle->%s == NULL) return -1;", names_field)
        lines[#lines + 1] = string.format("    for (uint16_t i = 0; i < handle->%s; i++) {", count_field)
        lines[#lines + 1] = string.format("        if (strcmp(func_name, handle->%s[i]) == 0) return i;", names_field)
        lines[#lines + 1] = "    }"
        lines[#lines + 1] = "    return -1;"
        lines[#lines + 1] = "}"
        lines[#lines + 1] = ""
    end

    -- Event lookups
    for _, line in ipairs({
        "const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index) {",
        "    if (handle == NULL || handle->event_strings == NULL) return NULL;",
        "    if (event_index >= handle->event_count) return NULL;",
        "    return handle->event_strings[event_index];",
        "}",
        "",
        "int ct_get_event_index(const chaintree_handle_t *handle, const char *name) {",
        "    if (handle == NULL || name == NULL || handle->event_strings == NULL) return -1;",
        "    for (uint16_t i = 0; i < handle->event_count; i++) {",
        "        if (strcmp(name, handle->event_strings[i]) == 0) return i;",
        "    }",
        "    return -1;",
        "}",
        "",
        "const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index) {",
        "    if (handle == NULL || handle->bitmask_names == NULL) return NULL;",
        "    if (bit_index >= handle->bitmask_count) return NULL;",
        "    return handle->bitmask_names[bit_index];",
        "}",
        "",
        "int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name) {",
        "    if (handle == NULL || name == NULL || handle->bitmask_names == NULL) return -1;",
        "    for (uint8_t i = 0; i < handle->bitmask_count; i++) {",
        "        if (strcmp(name, handle->bitmask_names[i]) == 0) return i;",
        "    }",
        "    return -1;",
        "}",
        "",
        "uint16_t ct_get_kb_count(const chaintree_handle_t *handle) {",
        "    if (handle == NULL) return 0;",
        "    return handle->kb_count;",
        "}",
        ""
    }) do
        lines[#lines + 1] = line
    end

    self:_write("chaintree_support.c", lines)
end

-- =========================================================================
-- Instance Header / Implementation
-- =========================================================================

function CCodeGenerator:_gen_instance_header()
    local guard = self.handle_name:upper() .. "_H"
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        '#include "chaintree_support.h"',
        string.format('#include "%s_nodes.h"', self.handle_name),
        string.format('#include "%s_links.h"', self.handle_name),
        string.format('#include "%s_events.h"', self.handle_name),
        string.format('#include "%s_bitmasks.h"', self.handle_name),
        string.format('#include "%s_kb_info.h"', self.handle_name),
        string.format('#include "%s_node_data.h"', self.handle_name),
        string.format('#include "%s_functions.h"', self.handle_name),
        "",
        string.format("extern const chaintree_handle_t g_%s;", self.handle_name),
        "",
        "#endif /* " .. guard .. " */"
    }
    self:_write(self.handle_name .. ".h", lines)
end

function CCodeGenerator:_gen_handle_implementation()
    local uid = self.unique_id
    local fb = self.function_builder
    local records_count = self.data_encoder and self.data_encoder:get_records_count() or 0
    local strings_size = self.data_encoder and self.data_encoder:get_strings_size() or 0
    local controls_count = self.data_encoder and self.data_encoder:get_controls_count() or 0

    local kb_names = self:_filter_executable_kbs(self.handle:get_kb_names())
    local event_count = table_len(self.handle:get_event_string_table())
    local bitmask_count = table_len(self.handle:get_bitmask_table())

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "",
        string.format('#include "%s.h"', self.handle_name),
        "",
        string.format("const chaintree_handle_t g_%s = {", self.handle_name),
        string.format('    .unique_id = "%s",', uid),
        "",
        string.format("    .nodes = %s_nodes,", uid),
        string.format("    .node_count = %d,", self.node_builder:get_total_nodes()),
        "",
        string.format("    .main_functions = %s_main_functions,", uid),
        string.format("    .main_function_count = %d,", fb.main_indexer:get_count()),
        string.format("    .one_shot_functions = %s_one_shot_functions,", uid),
        string.format("    .one_shot_function_count = %d,", fb.one_shot_indexer:get_count()),
        string.format("    .boolean_functions = %s_boolean_functions,", uid),
        string.format("    .boolean_function_count = %d,", fb.boolean_indexer:get_count()),
        "",
        string.format("    .main_function_names = %s_main_function_names,", uid),
        string.format("    .one_shot_function_names = %s_one_shot_function_names,", uid),
        string.format("    .boolean_function_names = %s_boolean_function_names,", uid),
        "",
        string.format("    .main_function_usage_count = %s_main_function_usage_count,", uid),
        "",
        string.format("    .link_table = %s_link_table,", uid),
        string.format("    .link_table_size = %d,", self.link_builder:get_link_table_size()),
        "",
        string.format("    .event_strings = (const char **)%s_event_strings,", uid),
        string.format("    .event_count = %d,", event_count),
        "",
        string.format("    .bitmask_names = (const char **)%s_bitmask_names,", uid),
        string.format("    .bitmask_count = %d,", bitmask_count),
        "",
        string.format("    .kb_table = %s_kb_table,", uid),
        string.format("    .kb_count = %d,", #kb_names),
        "",
    }

    if self.data_encoder and records_count > 0 then
        lines[#lines + 1] = string.format("    .node_data_records = %s_node_data_records,", uid)
        lines[#lines + 1] = string.format("    .node_data_records_count = %d,", records_count)
        lines[#lines + 1] = string.format("    .node_data_strings = %s_node_data_strings,", uid)
        lines[#lines + 1] = string.format("    .node_data_strings_size = %d,", strings_size)
        lines[#lines + 1] = string.format("    .node_data_controls = %s_node_data_controls,", uid)
        lines[#lines + 1] = string.format("    .node_data_controls_count = %d", controls_count)
    else
        lines[#lines + 1] = "    .node_data_records = NULL,"
        lines[#lines + 1] = "    .node_data_records_count = 0,"
        lines[#lines + 1] = "    .node_data_strings = NULL,"
        lines[#lines + 1] = "    .node_data_strings_size = 0,"
        lines[#lines + 1] = "    .node_data_controls = NULL,"
        lines[#lines + 1] = "    .node_data_controls_count = 0"
    end

    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""
    self:_write(self.handle_name .. ".c", lines)
end

-- =========================================================================
-- Nodes
-- =========================================================================

function CCodeGenerator:_gen_node_struct_header()
    local guard = self.handle_name:upper() .. "_NODES_H"
    local uid = self.unique_id
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        '#include "chaintree_support.h"',
        "",
        string.format("#define %s_NODE_COUNT %d", uid:upper(), self.node_builder:get_array_size()),
        "",
        string.format("extern const chaintree_node_t %s_nodes[%s_NODE_COUNT];", uid, uid:upper()),
        "",
        "#endif /* " .. guard .. " */"
    }
    self:_write(self.handle_name .. "_nodes.h", lines)
end

function CCodeGenerator:_gen_node_array_implementation()
    local uid = self.unique_id
    local array_size = self.node_builder:get_array_size()

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_nodes.h"', self.handle_name),
        "",
        "/* Node array - preserves original indices; filtered nodes leave gaps */",
        string.format("const chaintree_node_t %s_nodes[%d] = {", uid, array_size),
    }

    for i = 0, array_size - 1 do
        local ltree_name = self.node_builder:get_node_by_index(i)

        if not ltree_name then
            lines[#lines + 1] = string.format("    /* [%d] FILTERED */ {", i)
            lines[#lines + 1] = string.format("        .node_index = %d, .parent_index = 0xFFFF, .depth = 0,", i)
            lines[#lines + 1] = "        .link_start = 0, .link_count = 0,"
            lines[#lines + 1] = "        .main_function_index = 0, .init_function_index = 0,"
            lines[#lines + 1] = "        .aux_function_index = 0, .term_function_index = 0,"
            lines[#lines + 1] = "        .node_data_id = 0xFFFF"
            lines[#lines + 1] = "    },"
        else
            local node_data = self.handle:get_node_data(ltree_name)
            if not node_data then
                lines[#lines + 1] = string.format("    /* [%d] ERROR: not found: %s */", i, ltree_name)
            else
                local functions = self.handle:get_node_functions(ltree_name)
                local main_idx = self.function_builder.main_indexer:get_index(functions.main)
                local init_idx = self.function_builder.one_shot_indexer:get_index(functions.init)
                local aux_idx = self.function_builder.boolean_indexer:get_index(functions.aux)
                local term_idx = self.function_builder.one_shot_indexer:get_index(functions.term)

                local link_info = self.link_builder:get_node_link_info(ltree_name)
                local link_start = link_info.link_start
                local link_count = link_info.link_count

                local node_dict = node_data.node_dict or {}
                local auto_start = false
                if type(node_dict) == "table" then
                    auto_start = node_dict.auto_start and true or false
                end

                local packed = bit.band(link_count, 0x7FFF)
                if auto_start then packed = bit.bor(packed, 0x8000) end

                local parent_ltree = self.handle:get_node_parent(ltree_name)
                local parent_idx = 0xFFFF
                if parent_ltree and self.node_builder.ltree_to_final_index[parent_ltree] then
                    parent_idx = self.node_builder:get_node_final_index(parent_ltree)
                end

                local depth = self.node_builder:get_node_depth(ltree_name)
                local data_id = 0xFFFF
                if self.data_encoder then
                    data_id = self.data_encoder:get_node_data_id(ltree_name)
                end

                local node_name = node_data.node_name or "unknown"
                local auto_tag = auto_start and " [AUTO_START]" or ""

                lines[#lines + 1] = string.format("    /* [%d] %s%s */", i, node_name, auto_tag)
                lines[#lines + 1] = "    {"
                lines[#lines + 1] = string.format("        .node_index = %d,", i)
                lines[#lines + 1] = string.format("        .parent_index = %d,", parent_idx)
                lines[#lines + 1] = string.format("        .depth = %d,", depth)
                lines[#lines + 1] = string.format("        .link_start = %d,", link_start)
                lines[#lines + 1] = string.format("        .link_count = 0x%04X,  /* count=%d, auto_start=%s */", packed, link_count, tostring(auto_start))
                lines[#lines + 1] = string.format("        .main_function_index = %d,", main_idx)
                lines[#lines + 1] = string.format("        .init_function_index = %d,", init_idx)
                lines[#lines + 1] = string.format("        .aux_function_index = %d,", aux_idx)
                lines[#lines + 1] = string.format("        .term_function_index = %d,", term_idx)
                lines[#lines + 1] = string.format("        .node_data_id = %d", data_id)
                lines[#lines + 1] = "    },"
            end
        end
    end

    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""
    self:_write(self.handle_name .. "_nodes.c", lines)
end

-- =========================================================================
-- Functions
-- =========================================================================

function CCodeGenerator:_gen_function_headers()
    local guard = self.handle_name:upper() .. "_FUNCTIONS_H"
    local fb = self.function_builder
    local uid = self.unique_id

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "#include <string.h>",
        '#include "chaintree_support.h"',
        "",
        "/* Main function enum */",
        fb.main_indexer:generate_c_enum("MAIN_FUNC"),
        "",
        "/* One-shot function enum */",
        fb.one_shot_indexer:generate_c_enum("ONE_SHOT_FUNC"),
        "",
        "/* Boolean function enum */",
        fb.boolean_indexer:generate_c_enum("BOOL_FUNC"),
        "",
        string.format("extern const main_function_t %s_main_functions[%d];", uid, fb.main_indexer:get_count()),
        string.format("extern const one_shot_function_t %s_one_shot_functions[%d];", uid, fb.one_shot_indexer:get_count()),
        string.format("extern const boolean_function_t %s_boolean_functions[%d];", uid, fb.boolean_indexer:get_count()),
        "",
        string.format("extern const uint16_t %s_main_function_usage_count[%d];", uid, fb.main_indexer:get_count()),
        "",
        string.format("extern const char *%s_main_function_names[%d];", uid, fb.main_indexer:get_count()),
        string.format("extern const char *%s_one_shot_function_names[%d];", uid, fb.one_shot_indexer:get_count()),
        string.format("extern const char *%s_boolean_function_names[%d];", uid, fb.boolean_indexer:get_count()),
        "",
        "#endif /* " .. guard .. " */"
    }
    self:_write(self.handle_name .. "_functions.h", lines)
end

function CCodeGenerator:_gen_function_implementations()
    local fb = self.function_builder
    local uid = self.unique_id

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_functions.h"', self.handle_name),
        "",
        "/* Forward declarations - user must provide these functions */",
    }

    for _, orig in ipairs(fb.main_indexer:get_all_functions()) do
        local fn = fb:get_typed_main_name(orig) .. "_fn"
        lines[#lines + 1] = string.format("extern unsigned %s(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);", fn)
    end
    lines[#lines + 1] = ""

    for _, orig in ipairs(fb.one_shot_indexer:get_all_functions()) do
        local fn = fb:get_typed_one_shot_name(orig) .. "_fn"
        lines[#lines + 1] = string.format("extern void %s(void *handle, unsigned node_index);", fn)
    end
    lines[#lines + 1] = ""

    for _, orig in ipairs(fb.boolean_indexer:get_all_functions()) do
        local fn = fb:get_typed_boolean_name(orig) .. "_fn"
        lines[#lines + 1] = string.format("extern bool %s(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);", fn)
    end
    lines[#lines + 1] = ""

    -- Function pointer arrays
    lines[#lines + 1] = string.format("const main_function_t %s_main_functions[] = {", uid)
    for _, orig in ipairs(fb.main_indexer:get_all_functions()) do
        lines[#lines + 1] = "    " .. fb:get_typed_main_name(orig) .. "_fn,"
    end
    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""

    lines[#lines + 1] = string.format("const one_shot_function_t %s_one_shot_functions[] = {", uid)
    for _, orig in ipairs(fb.one_shot_indexer:get_all_functions()) do
        lines[#lines + 1] = "    " .. fb:get_typed_one_shot_name(orig) .. "_fn,"
    end
    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""

    lines[#lines + 1] = string.format("const boolean_function_t %s_boolean_functions[] = {", uid)
    for _, orig in ipairs(fb.boolean_indexer:get_all_functions()) do
        lines[#lines + 1] = "    " .. fb:get_typed_boolean_name(orig) .. "_fn,"
    end
    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""

    -- Usage count
    lines[#lines + 1] = string.format("const uint16_t %s_main_function_usage_count[%d] = {", uid, fb.main_indexer:get_count())
    for i, orig in ipairs(fb.main_indexer:get_all_functions()) do
        local usage = self.main_function_usage[i - 1] or 0  -- 0-based key
        lines[#lines + 1] = string.format("    %d,  /* %s */", usage, orig)
    end
    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""

    -- Name arrays
    lines[#lines + 1] = fb.main_indexer:generate_c_string_array(uid .. "_main_function_names")
    lines[#lines + 1] = ""
    lines[#lines + 1] = fb.one_shot_indexer:generate_c_string_array(uid .. "_one_shot_function_names")
    lines[#lines + 1] = ""
    lines[#lines + 1] = fb.boolean_indexer:generate_c_string_array(uid .. "_boolean_function_names")
    lines[#lines + 1] = ""

    self:_write(self.handle_name .. "_functions.c", lines)
end

-- =========================================================================
-- Link Table
-- =========================================================================

function CCodeGenerator:_gen_link_table_header()
    local guard = self.handle_name:upper() .. "_LINKS_H"
    local uid = self.unique_id
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        "#include <stdint.h>",
        "",
        string.format("#define %s_LINK_TABLE_SIZE %d", uid:upper(), self.link_builder:get_link_table_size()),
        "",
        string.format("extern const uint16_t %s_link_table[%s_LINK_TABLE_SIZE];", uid, uid:upper()),
        "",
        "#endif /* " .. guard .. " */"
    }
    self:_write(self.handle_name .. "_links.h", lines)
end

function CCodeGenerator:_gen_link_table_implementation()
    local uid = self.unique_id
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_links.h"', self.handle_name),
        "",
        string.format("const uint16_t %s_link_table[%d] = {", uid, self.link_builder:get_link_table_size()),
    }

    local lt = self.link_builder.link_table
    if #lt > 0 then
        local line = "    "
        for i, child_index in ipairs(lt) do
            local pos = i - 1  -- 0-based for grouping
            if pos % 10 == 0 and pos > 0 then
                lines[#lines + 1] = line .. ","
                line = "    "
            end
            if pos % 10 == 0 then
                line = line .. tostring(child_index)
            else
                line = line .. ", " .. tostring(child_index)
            end
        end
        lines[#lines + 1] = line
    end

    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""
    self:_write(self.handle_name .. "_links.c", lines)
end

-- =========================================================================
-- Node Data
-- =========================================================================

function CCodeGenerator:_gen_node_data_header()
    local guard = self.handle_name:upper() .. "_NODE_DATA_H"
    local uid = self.unique_id
    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        '#include "chaintree_support.h"',
        "",
    }

    if self.data_encoder then
        local rc = self.data_encoder:get_records_count()
        local ss = self.data_encoder:get_strings_size()
        local cc = self.data_encoder:get_controls_count()
        if rc > 0 then
            lines[#lines + 1] = string.format("extern const json_record_t %s_node_data_records[%d];", uid, rc)
            lines[#lines + 1] = string.format("extern const char %s_node_data_strings[%d];", uid, ss)
            lines[#lines + 1] = string.format("extern const record_control_t %s_node_data_controls[%d];", uid, cc)
            lines[#lines + 1] = ""
        end
    end

    lines[#lines + 1] = "#endif /* " .. guard .. " */"
    lines[#lines + 1] = ""
    self:_write(self.handle_name .. "_node_data.h", lines)
end

function CCodeGenerator:_gen_node_data_implementation()
    if not self.data_encoder or self.data_encoder:get_records_count() == 0 then
        local lines = {
            "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
            string.format('#include "%s_node_data.h"', self.handle_name),
            "", "/* No node data */", ""
        }
        self:_write(self.handle_name .. "_node_data.c", lines)
        return
    end

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_node_data.h"', self.handle_name),
        "",
    }
    self.data_encoder:generate_c_arrays(lines, self.unique_id)
    self:_write(self.handle_name .. "_node_data.c", lines)
end

-- =========================================================================
-- Events
-- =========================================================================

function CCodeGenerator:_gen_event_table_header()
    local guard = self.handle_name:upper() .. "_EVENTS_H"
    local events = self.handle:get_event_string_table()
    local uid = self.unique_id
    local event_count = table_len(events)

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "#include <string.h>",
        "",
    }

    if event_count > 0 then
        lines[#lines + 1] = string.format("#define %s_EVENT_STRING_COUNT %d", uid:upper(), event_count)
        lines[#lines + 1] = ""
        lines[#lines + 1] = "typedef enum {"
        for event_id, index in sorted_pairs_by_value(events) do
            lines[#lines + 1] = string.format("    EVENT_%s = %d,", safe_name(event_id), index)
        end
        lines[#lines + 1] = string.format("    EVENT_COUNT = %d", event_count)
        lines[#lines + 1] = "} event_index_t;"
        lines[#lines + 1] = ""
        lines[#lines + 1] = string.format("extern const char *%s_event_strings[%d];", uid, event_count)
        lines[#lines + 1] = ""
    else
        lines[#lines + 1] = string.format("#define %s_EVENT_STRING_COUNT 0", uid:upper())
        lines[#lines + 1] = "#define EVENT_COUNT 0"
        lines[#lines + 1] = ""
        lines[#lines + 1] = string.format("extern const char *%s_event_strings[1];", uid)
        lines[#lines + 1] = ""
    end

    lines[#lines + 1] = "#endif /* " .. guard .. " */"
    self:_write(self.handle_name .. "_events.h", lines)
end

function CCodeGenerator:_gen_event_table_implementation()
    local events = self.handle:get_event_string_table()
    local uid = self.unique_id
    local event_count = table_len(events)

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_events.h"', self.handle_name),
        "",
    }

    if event_count > 0 then
        lines[#lines + 1] = string.format("const char *%s_event_strings[%d] = {", uid, event_count)
        for event_id in sorted_pairs_by_value(events) do
            lines[#lines + 1] = string.format('    "%s",', event_id)
        end
        lines[#lines + 1] = "};"
        lines[#lines + 1] = ""
    else
        lines[#lines + 1] = string.format('const char *%s_event_strings[1] = { NULL };', uid)
        lines[#lines + 1] = ""
    end

    self:_write(self.handle_name .. "_events.c", lines)
end

-- =========================================================================
-- Bitmasks
-- =========================================================================

function CCodeGenerator:_gen_bitmask_table_header()
    local guard = self.handle_name:upper() .. "_BITMASKS_H"
    local bitmasks = self.handle:get_bitmask_table()
    local uid = self.unique_id
    local bm_count = table_len(bitmasks)

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "#include <string.h>",
        "",
    }

    if bm_count > 0 then
        lines[#lines + 1] = "/* Bitmask bit positions */"
        for name, bit_val in sorted_pairs_by_value(bitmasks) do
            local sn = safe_name(name)
            lines[#lines + 1] = string.format("#define BIT_%-30s %2d  /* 0x%08X */", sn, bit_val, bit.lshift(1, bit_val))
        end

        lines[#lines + 1] = ""
        lines[#lines + 1] = "/* Bitmask values */"
        for name in sorted_pairs_by_value(bitmasks) do
            local sn = safe_name(name)
            lines[#lines + 1] = string.format("#define MASK_%-29s (1U << BIT_%s)", sn, sn)
        end

        lines[#lines + 1] = ""
        lines[#lines + 1] = string.format("#define %s_BITMASK_COUNT %d", uid:upper(), bm_count)
        lines[#lines + 1] = ""
        lines[#lines + 1] = string.format("extern const char *%s_bitmask_names[%d];", uid, bm_count)
        lines[#lines + 1] = ""
    else
        lines[#lines + 1] = string.format("#define %s_BITMASK_COUNT 0", uid:upper())
        lines[#lines + 1] = ""
        lines[#lines + 1] = string.format("extern const char *%s_bitmask_names[1];", uid)
        lines[#lines + 1] = ""
    end

    lines[#lines + 1] = "#endif /* " .. guard .. " */"
    self:_write(self.handle_name .. "_bitmasks.h", lines)
end

function CCodeGenerator:_gen_bitmask_table_implementation()
    local bitmasks = self.handle:get_bitmask_table()
    local uid = self.unique_id
    local bm_count = table_len(bitmasks)

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_bitmasks.h"', self.handle_name),
        "",
    }

    if bm_count > 0 then
        lines[#lines + 1] = string.format("const char *%s_bitmask_names[%d] = {", uid, bm_count)
        for name in sorted_pairs_by_value(bitmasks) do
            lines[#lines + 1] = string.format('    "%s",', name)
        end
        lines[#lines + 1] = "};"
        lines[#lines + 1] = ""
    else
        lines[#lines + 1] = string.format('const char *%s_bitmask_names[1] = { NULL };', uid)
        lines[#lines + 1] = ""
    end

    self:_write(self.handle_name .. "_bitmasks.c", lines)
end

-- =========================================================================
-- KB Info
-- =========================================================================

function CCodeGenerator:_gen_kb_info_header()
    local guard = self.handle_name:upper() .. "_KB_INFO_H"
    local kb_names = self:_filter_executable_kbs(self.handle:get_kb_names())
    local uid = self.unique_id

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
        '#include "chaintree_support.h"',
        "",
        string.format("#define %s_KB_COUNT %d", uid:upper(), #kb_names),
        "",
    }

    for i, kb_name in ipairs(kb_names) do
        local aliases = self.handle:get_kb_node_aliases(kb_name)
        if next(aliases) then
            lines[#lines + 1] = string.format("extern const node_alias_t %s_kb_%d_aliases[%d];", uid, i - 1, table_len(aliases))
        end
    end

    lines[#lines + 1] = ""
    lines[#lines + 1] = string.format("extern const chaintree_kb_info_t %s_kb_table[%d];", uid, #kb_names)
    lines[#lines + 1] = ""
    lines[#lines + 1] = "#endif /* " .. guard .. " */"
    self:_write(self.handle_name .. "_kb_info.h", lines)
end

function CCodeGenerator:_gen_kb_info_implementation()
    local kb_names = self:_filter_executable_kbs(self.handle:get_kb_names())
    local uid = self.unique_id

    local lines = {
        "/* Auto-generated by ChainTree Pipeline (LuaJIT) */",
        string.format('#include "%s_kb_info.h"', self.handle_name),
        "",
    }

    -- Alias arrays
    local kb_alias_info = {}
    for i, kb_name in ipairs(kb_names) do
        local idx = i - 1
        local aliases = self.handle:get_kb_node_aliases(kb_name)
        local alias_count = table_len(aliases)
        if alias_count > 0 then
            lines[#lines + 1] = string.format("const node_alias_t %s_kb_%d_aliases[%d] = {", uid, idx, alias_count)
            for alias_name, node_index in sorted_pairs_by_key(aliases) do
                lines[#lines + 1] = string.format('    {"%s", %d},', alias_name, node_index)
            end
            lines[#lines + 1] = "};"
            lines[#lines + 1] = ""
            kb_alias_info[idx] = { true, alias_count }
        else
            kb_alias_info[idx] = { false, 0 }
        end
    end

    -- KB table
    lines[#lines + 1] = string.format("const chaintree_kb_info_t %s_kb_table[%d] = {", uid, #kb_names)

    for i, kb_name in ipairs(kb_names) do
        local idx = i - 1
        local start_idx, end_idx = self.node_builder:get_kb_range(kb_name)
        local node_count = end_idx - start_idx
        local root_node_index = start_idx

        local max_depth = 0
        for j = start_idx, end_idx - 1 do
            local ltree_name = self.node_builder:get_node_by_index(j)
            if ltree_name then
                local d = self.node_builder:get_node_depth(ltree_name)
                if d > max_depth then max_depth = d end
            end
        end

        local memory_factor = self.handle:get_kb_metadata_value(kb_name, "node_memory_factor", 10)

        local info = kb_alias_info[idx]
        local alias_ptr = info[1] and string.format("%s_kb_%d_aliases", uid, idx) or "NULL"
        local alias_count = info[2]

        lines[#lines + 1] = "    {"
        lines[#lines + 1] = string.format('        .kb_name = "%s",', kb_name)
        lines[#lines + 1] = string.format("        .root_node_index = %d,", root_node_index)
        lines[#lines + 1] = string.format("        .start_index = %d,", start_idx)
        lines[#lines + 1] = string.format("        .node_count = %d,", node_count)
        lines[#lines + 1] = string.format("        .max_depth = %d,", max_depth)
        lines[#lines + 1] = string.format("        .memory_factor = %d,", memory_factor)
        lines[#lines + 1] = string.format("        .aliases = %s,", alias_ptr)
        lines[#lines + 1] = string.format("        .alias_count = %d", alias_count)
        lines[#lines + 1] = "    },"
    end

    lines[#lines + 1] = "};"
    lines[#lines + 1] = ""
    self:_write(self.handle_name .. "_kb_info.c", lines)
end

return CCodeGenerator