/* Auto-generated by ChainTree Pipeline */
#include "test_header_kb_info.h"

/* Node aliases for KB: twenty_seventh_test */
const node_alias_t ct_u38t90rd_kb_23_aliases[4] = {
    {"drone_control_fly_straight", 1220},
    {"drone_control_fly_arc", 1226},
    {"drone_control_fly_up", 1232},
    {"drone_control_fly_down", 1238},
};

/* Node aliases for KB: twenty_eighth_test */
const node_alias_t ct_u38t90rd_kb_24_aliases[4] = {
    {"drone_control_fly_straight", 1265},
    {"drone_control_fly_arc", 1272},
    {"drone_control_fly_up", 1278},
    {"drone_control_fly_down", 1284},
};

/* Knowledge base information table */
const chaintree_kb_info_t ct_u38t90rd_kb_table[29] = {
    {
        .kb_name = "first_test",
        .root_node_index = 0,
        .start_index = 0,
        .node_count = 32,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "second_test",
        .root_node_index = 32,
        .start_index = 32,
        .node_count = 34,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "fourth_test",
        .root_node_index = 66,
        .start_index = 66,
        .node_count = 15,
        .max_depth = 3,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "fifth_test",
        .root_node_index = 81,
        .start_index = 81,
        .node_count = 61,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "sixth_test",
        .root_node_index = 142,
        .start_index = 142,
        .node_count = 35,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "seventh_test",
        .root_node_index = 177,
        .start_index = 177,
        .node_count = 40,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "eighth_test",
        .root_node_index = 217,
        .start_index = 217,
        .node_count = 28,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "ninth_test",
        .root_node_index = 245,
        .start_index = 245,
        .node_count = 30,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "tenth_test",
        .root_node_index = 275,
        .start_index = 275,
        .node_count = 97,
        .max_depth = 5,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "eleventh_test",
        .root_node_index = 372,
        .start_index = 372,
        .node_count = 11,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twelfth_test",
        .root_node_index = 383,
        .start_index = 383,
        .node_count = 7,
        .max_depth = 3,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "thirteenth_test",
        .root_node_index = 390,
        .start_index = 390,
        .node_count = 22,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "fourteenth_test",
        .root_node_index = 412,
        .start_index = 412,
        .node_count = 26,
        .max_depth = 3,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "seventeenth_test",
        .root_node_index = 438,
        .start_index = 438,
        .node_count = 221,
        .max_depth = 6,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "eighteenth_test",
        .root_node_index = 659,
        .start_index = 659,
        .node_count = 187,
        .max_depth = 6,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "ninteenth_test",
        .root_node_index = 846,
        .start_index = 846,
        .node_count = 234,
        .max_depth = 10,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twentieth_test",
        .root_node_index = 1080,
        .start_index = 1080,
        .node_count = 19,
        .max_depth = 3,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_first_test",
        .root_node_index = 1099,
        .start_index = 1099,
        .node_count = 17,
        .max_depth = 2,
        .memory_factor = 40,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_second_test",
        .root_node_index = 1116,
        .start_index = 1116,
        .node_count = 29,
        .max_depth = 5,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_third_test",
        .root_node_index = 1145,
        .start_index = 1145,
        .node_count = 6,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_fourth_test",
        .root_node_index = 1151,
        .start_index = 1151,
        .node_count = 20,
        .max_depth = 3,
        .memory_factor = 50,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_fifth_test",
        .root_node_index = 1171,
        .start_index = 1171,
        .node_count = 28,
        .max_depth = 3,
        .memory_factor = 50,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_sixth_test",
        .root_node_index = 1199,
        .start_index = 1199,
        .node_count = 19,
        .max_depth = 3,
        .memory_factor = 50,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "twenty_seventh_test",
        .root_node_index = 1218,
        .start_index = 1218,
        .node_count = 45,
        .max_depth = 3,
        .memory_factor = 50,
        .aliases = ct_u38t90rd_kb_23_aliases,
        .alias_count = 4
    },
    {
        .kb_name = "twenty_eighth_test",
        .root_node_index = 1263,
        .start_index = 1263,
        .node_count = 46,
        .max_depth = 3,
        .memory_factor = 50,
        .aliases = ct_u38t90rd_kb_24_aliases,
        .alias_count = 4
    },
    {
        .kb_name = "twenty_ninth_test",
        .root_node_index = 1309,
        .start_index = 1309,
        .node_count = 22,
        .max_depth = 3,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "thirty_test",
        .root_node_index = 1331,
        .start_index = 1331,
        .node_count = 26,
        .max_depth = 4,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "thirty_one_test",
        .root_node_index = 1357,
        .start_index = 1357,
        .node_count = 17,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
    {
        .kb_name = "thirty_two_test",
        .root_node_index = 1374,
        .start_index = 1374,
        .node_count = 23,
        .max_depth = 2,
        .memory_factor = 10,
        .aliases = NULL,
        .alias_count = 0
    },
};
