// ============================================================================
// dispatch_test_lua_registration.h
// Lua trampoline registration header for dispatch_test
// DO NOT EDIT - Generated by s_expr_dsl v5.4
// ============================================================================

#ifndef DISPATCH_TEST_LUA_REGISTRATION_H
#define DISPATCH_TEST_LUA_REGISTRATION_H

#include "s_engine_types.h"

// Register all Lua trampoline functions with module
void dispatch_test_register_lua(s_expr_module_t* module);

#endif // DISPATCH_TEST_LUA_REGISTRATION_H
