# ==========================================================================
# s_engine_test_module_mpy.py
# Auto-generated by ChainTree Pipeline (LuaJIT) - MicroPython backend
#
# Node tuple: (func_name, func_index, node_index, guard_index, node_data, children)
# ==========================================================================

from micropython import const

main_funcs = (
    "CFL_NULL",  # 0
    "CFL_COLUMN_MAIN",  # 1
    "CFL_DISABLE",  # 2
    "CFL_GATE_NODE_MAIN",  # 3
    "CFL_SE_MODULE_LOAD_MAIN",  # 4
    "CFL_SE_TICK_MAIN",  # 5
    "CFL_SE_TREE_LOAD_MAIN",  # 6
    "CFL_TERMINATE_SYSTEM",  # 7
    "CFL_WAIT_TIME",  # 8
)

pred_funcs = (
    "CFL_NULL",  # 0
    "CFL_COLUMN_NULL",  # 1
    "CFL_GATE_NODE_NULL",  # 2
    "SE_CUSTOM_BB_LOAD",  # 3
    "USER_REGISTER_S_FUNCTIONS",  # 4
)

records = (
    (
        "se_test_state",
        (
            ("se_tree_ptr", "uint64", 0),
            ("se_tree_a_ptr", "uint64", 0),
            ("se_tree_b_ptr", "uint64", 0),
            ("tick_count", "int32", 0),
            ("test_result", "int32", 0),
            ("state", "int32", 0),
            ("custom_loaded", "int32", 0),
        ),
    ),
)

tree_order = (
    "se_basic_load_test",
    "se_multi_tree_test",
    "se_custom_bb_test",
)

trees = (
    (
        "se_basic_load_test",  # T_NAME
        0xC26296C6,  # T_NAME_HASH
        8,  # T_NODE_COUNT
        "se_test_state",  # T_RECORD
        # T_ROOT
        ("CFL_GATE_NODE_MAIN", 3, 0, 2, ("version", "1.0.0"),
            (
                ("CFL_COLUMN_MAIN", 1, 1, 1, (),
                    (
                        ("CFL_SE_MODULE_LOAD_MAIN", 4, 2, 4, ("module_name", "state_machine_test"), ()),
                        ("CFL_SE_TREE_LOAD_MAIN", 6, 3, -1, ("bb_field_name", "se_tree_ptr", "module_name", "state_machine_test", "tree_name", "state_machine_test"), ()),
                        ("CFL_SE_TICK_MAIN", 5, 4, -1, ("tree_bb_field", "se_tree_ptr"), ()),
                        ("CFL_COLUMN_MAIN", 1, 5, 1, (),
                            (
                                ("CFL_DISABLE", 2, 6, -1, ("message", "s-engine tree complete, shutting down"), ()),
                                ("CFL_TERMINATE_SYSTEM", 7, 7, -1, (), ()),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    (
        "se_multi_tree_test",  # T_NAME
        0xA7FA406D,  # T_NAME_HASH
        10,  # T_NODE_COUNT
        "se_test_state",  # T_RECORD
        # T_ROOT
        ("CFL_GATE_NODE_MAIN", 3, 8, 2, ("version", "1.0.0"),
            (
                ("CFL_COLUMN_MAIN", 1, 9, 1, (),
                    (
                        ("CFL_SE_MODULE_LOAD_MAIN", 4, 10, -1, ("module_name", "se_multi_module"), ()),
                        ("CFL_SE_TREE_LOAD_MAIN", 6, 11, -1, ("bb_field_name", "se_tree_a_ptr", "module_name", "se_multi_module", "tree_name", "tree_alpha"), ()),
                        ("CFL_SE_TREE_LOAD_MAIN", 6, 12, -1, ("bb_field_name", "se_tree_b_ptr", "module_name", "se_multi_module", "tree_name", "tree_beta"), ()),
                        ("CFL_COLUMN_MAIN", 1, 13, 1, (),
                            (
                                ("CFL_DISABLE", 2, 14, -1, ("message", "two s-engine trees loaded"), ()),
                                ("CFL_WAIT_TIME", 8, 15, -1, ("time_delay", 2), ()),
                                ("CFL_DISABLE", 2, 16, -1, ("message", "s-engine multi-tree test complete"), ()),
                                ("CFL_TERMINATE_SYSTEM", 7, 17, -1, (), ()),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    (
        "se_custom_bb_test",  # T_NAME
        0x4820D723,  # T_NAME_HASH
        9,  # T_NODE_COUNT
        "se_test_state",  # T_RECORD
        # T_ROOT
        ("CFL_GATE_NODE_MAIN", 3, 18, 2, ("version", "1.0.0"),
            (
                ("CFL_COLUMN_MAIN", 1, 19, 1, (),
                    (
                        ("CFL_SE_MODULE_LOAD_MAIN", 4, 20, 4, ("module_name", "se_custom_module"), ()),
                        ("CFL_SE_TREE_LOAD_MAIN", 6, 21, 3, ("bb_field_name", "se_tree_ptr", "module_name", "se_custom_module", "tree_name", "se_custom_tree"), ()),
                        ("CFL_COLUMN_MAIN", 1, 22, 1, (),
                            (
                                ("CFL_DISABLE", 2, 23, -1, ("message", "custom blackboard loaded"), ()),
                                ("CFL_WAIT_TIME", 8, 24, -1, ("time_delay", 1), ()),
                                ("CFL_DISABLE", 2, 25, -1, ("message", "s-engine custom bb test complete"), ()),
                                ("CFL_TERMINATE_SYSTEM", 7, 26, -1, (), ()),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
)

string_table = (
    "CFL_INIT_EVENT",  # 0
    "CFL_TERMINATE_EVENT",  # 1
    "CFL_START_TESTS",  # 2
    "CFL_TERMINATE_TESTS",  # 3
    "CFL_TIMER_EVENT",  # 4
    "CFL_SECOND_EVENT",  # 5
    "CFL_MINUTE_EVENT",  # 6
    "CFL_HOUR_EVENT",  # 7
    "CFL_DAY_EVENT",  # 8
    "CFL_WEEK_EVENT",  # 9
    "CFL_MONTH_EVENT",  # 10
    "CFL_YEAR_EVENT",  # 11
    "CFL_RAISE_EXCEPTION_EVENT",  # 12
    "CFL_TURN_HEARTBEAT_ON_EVENT",  # 13
    "CFL_TURN_HEARTBEAT_OFF_EVENT",  # 14
    "CFL_HEARTBEAT_EVENT",  # 15
    "CFL_SET_EXCEPTION_STEP_EVENT",  # 16
    "CFL_CHANGE_STATE_EVENT",  # 17
    "CFL_RESET_STATE_MACHINE_EVENT",  # 18
    "CFL_TERMINATE_STATE_MACHINE_EVENT",  # 19
)

string_index = (
    ("CFL_CHANGE_STATE_EVENT", 17),
    ("CFL_DAY_EVENT", 8),
    ("CFL_HEARTBEAT_EVENT", 15),
    ("CFL_HOUR_EVENT", 7),
    ("CFL_INIT_EVENT", 0),
    ("CFL_MINUTE_EVENT", 6),
    ("CFL_MONTH_EVENT", 10),
    ("CFL_RAISE_EXCEPTION_EVENT", 12),
    ("CFL_RESET_STATE_MACHINE_EVENT", 18),
    ("CFL_SECOND_EVENT", 5),
    ("CFL_SET_EXCEPTION_STEP_EVENT", 16),
    ("CFL_START_TESTS", 2),
    ("CFL_TERMINATE_EVENT", 1),
    ("CFL_TERMINATE_STATE_MACHINE_EVENT", 19),
    ("CFL_TERMINATE_TESTS", 3),
    ("CFL_TIMER_EVENT", 4),
    ("CFL_TURN_HEARTBEAT_OFF_EVENT", 14),
    ("CFL_TURN_HEARTBEAT_ON_EVENT", 13),
    ("CFL_WEEK_EVENT", 9),
    ("CFL_YEAR_EVENT", 11),
)

events = (
    ("CFL_INIT_EVENT", 0),
    ("CFL_TERMINATE_EVENT", 1),
    ("CFL_START_TESTS", 2),
    ("CFL_TERMINATE_TESTS", 3),
    ("CFL_TIMER_EVENT", 4),
    ("CFL_SECOND_EVENT", 5),
    ("CFL_MINUTE_EVENT", 6),
    ("CFL_HOUR_EVENT", 7),
    ("CFL_DAY_EVENT", 8),
    ("CFL_WEEK_EVENT", 9),
    ("CFL_MONTH_EVENT", 10),
    ("CFL_YEAR_EVENT", 11),
    ("CFL_RAISE_EXCEPTION_EVENT", 12),
    ("CFL_TURN_HEARTBEAT_ON_EVENT", 13),
    ("CFL_TURN_HEARTBEAT_OFF_EVENT", 14),
    ("CFL_HEARTBEAT_EVENT", 15),
    ("CFL_SET_EXCEPTION_STEP_EVENT", 16),
    ("CFL_CHANGE_STATE_EVENT", 17),
    ("CFL_RESET_STATE_MACHINE_EVENT", 18),
    ("CFL_TERMINATE_STATE_MACHINE_EVENT", 19),
)

