// sensor_data.h
// Generated by avro_dsl.lua - DO NOT EDIT
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============ FILE METADATA ============
#define SENSOR_DATA_SCHEMA_HASH   0x57ACFBB2U
#define SENSOR_DATA_RECORD_COUNT  4
#define SENSOR_DATA_SCHEMA_FILE   "sensor_data.h"

// ============ ENUMS ============
typedef enum {
    SENSOR_TYPE_TEMPERATURE = 0,
    SENSOR_TYPE_HUMIDITY = 1,
    SENSOR_TYPE_PRESSURE = 2,
    SENSOR_TYPE_FLOW = 3
} sensor_type_t;

typedef enum {
    ALARM_LEVEL_NONE = 0,
    ALARM_LEVEL_WARNING = 1,
    ALARM_LEVEL_CRITICAL = 2
} alarm_level_t;

// ============ FIXED ARRAYS ============
typedef uint8_t mac_addr_t[6];
typedef uint8_t uuid_t[16];

// ============ FIXED STRINGS ============
typedef struct {
    char buffer[32];
    uint16_t length;
    uint16_t max_length;
} sensor_name_t;

// ============ RECORDS ============
// Note: For cross-platform wire safety, use the _wire_t variants

typedef struct {
    uint16_t sensor_id;
    sensor_type_t sensor_type;
    float value;
    uint32_t timestamp;
} sensor_reading_t;

typedef struct {
    uint16_t sensor_id;
    alarm_level_t level;
    float value;
    float threshold;
    uint32_t timestamp;
} alarm_event_t;

typedef struct {
    uint16_t sensor_id;
    uint16_t sample_rate_ms;
    float threshold_low;
    float threshold_high;
    bool enabled;
} config_update_t;

typedef struct {
    uint32_t uptime_sec;
    uint32_t free_heap;
    uint8_t sensor_count;
    uint8_t alarm_count;
} heartbeat_t;

// ============ WIRE-SAFE RECORDS ============
// Packed structs with fixed-size enums for cross-platform compatibility
// Use these for 32-bit <-> 64-bit communication

#pragma pack(push, 1)
typedef struct {
    uint16_t sensor_id;
    int32_t sensor_type;  // enum sensor_type
    float value;
    uint32_t timestamp;
} sensor_reading_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    uint16_t sensor_id;
    int32_t level;  // enum alarm_level
    float value;
    float threshold;
    uint32_t timestamp;
} alarm_event_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    uint16_t sensor_id;
    uint16_t sample_rate_ms;
    float threshold_low;
    float threshold_high;
    bool enabled;
} config_update_wire_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    uint32_t uptime_sec;
    uint32_t free_heap;
    uint8_t sensor_count;
    uint8_t alarm_count;
} heartbeat_wire_t;
#pragma pack(pop)

// ============ WIRE CONVERSION HELPERS ============

static inline void sensor_reading_to_wire(const sensor_reading_t* src, sensor_reading_wire_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->sensor_type = (int32_t)src->sensor_type;
    dst->value = src->value;
    dst->timestamp = src->timestamp;
}

static inline void sensor_reading_from_wire(const sensor_reading_wire_t* src, sensor_reading_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->sensor_type = (sensor_type_t)src->sensor_type;
    dst->value = src->value;
    dst->timestamp = src->timestamp;
}

static inline void alarm_event_to_wire(const alarm_event_t* src, alarm_event_wire_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->level = (int32_t)src->level;
    dst->value = src->value;
    dst->threshold = src->threshold;
    dst->timestamp = src->timestamp;
}

static inline void alarm_event_from_wire(const alarm_event_wire_t* src, alarm_event_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->level = (alarm_level_t)src->level;
    dst->value = src->value;
    dst->threshold = src->threshold;
    dst->timestamp = src->timestamp;
}

static inline void config_update_to_wire(const config_update_t* src, config_update_wire_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->sample_rate_ms = src->sample_rate_ms;
    dst->threshold_low = src->threshold_low;
    dst->threshold_high = src->threshold_high;
    dst->enabled = src->enabled;
}

static inline void config_update_from_wire(const config_update_wire_t* src, config_update_t* dst) {
    dst->sensor_id = src->sensor_id;
    dst->sample_rate_ms = src->sample_rate_ms;
    dst->threshold_low = src->threshold_low;
    dst->threshold_high = src->threshold_high;
    dst->enabled = src->enabled;
}

static inline void heartbeat_to_wire(const heartbeat_t* src, heartbeat_wire_t* dst) {
    dst->uptime_sec = src->uptime_sec;
    dst->free_heap = src->free_heap;
    dst->sensor_count = src->sensor_count;
    dst->alarm_count = src->alarm_count;
}

static inline void heartbeat_from_wire(const heartbeat_wire_t* src, heartbeat_t* dst) {
    dst->uptime_sec = src->uptime_sec;
    dst->free_heap = src->free_heap;
    dst->sensor_count = src->sensor_count;
    dst->alarm_count = src->alarm_count;
}

// ============ WIRE HEADER ============
// Common header for all wire packets (16 bytes, packed)
// schema_hash replaces string pointer for socket-safe transmission

#pragma pack(push, 1)
typedef struct {
    double      timestamp;     // 8: message timestamp (set by transport)
    uint32_t    schema_hash;   // 4: FNV-1a hash of schema .h filename
    uint16_t    seq;           // 2: sequence number (set by transport)
    uint8_t     source_node;   // 1: originating node ID
    uint8_t     index;         // 1: record type index
} sensor_data_wire_header_t;
#pragma pack(pop)

_Static_assert(sizeof(sensor_data_wire_header_t) == 16, "Wire header must be 16 bytes");

static inline bool sensor_data_verify_header(const sensor_data_wire_header_t* hdr) {
    return hdr->schema_hash == SENSOR_DATA_SCHEMA_HASH;
}

// ============ WIRE PACKETS ============
// Per-record packet types with unified header
// Socket-safe: no pointers, fixed size, hash-based identification
// Uses packed _wire_t records for cross-platform compatibility

#pragma pack(push, 1)
typedef struct {
    sensor_data_wire_header_t header;
    sensor_reading_wire_t        data;
} sensor_reading_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    sensor_data_wire_header_t header;
    alarm_event_wire_t        data;
} alarm_event_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    sensor_data_wire_header_t header;
    config_update_wire_t        data;
} config_update_packet_t;
#pragma pack(pop)

#pragma pack(push, 1)
typedef struct {
    sensor_data_wire_header_t header;
    heartbeat_wire_t        data;
} heartbeat_packet_t;
#pragma pack(pop)

// Static assertions for wire format sizes
_Static_assert(sizeof(sensor_reading_wire_t) == 14, "sensor_reading_wire_t size mismatch");
_Static_assert(sizeof(alarm_event_wire_t) == 18, "alarm_event_wire_t size mismatch");
_Static_assert(sizeof(config_update_wire_t) == 13, "config_update_wire_t size mismatch");
_Static_assert(sizeof(heartbeat_wire_t) == 10, "heartbeat_wire_t size mismatch");

// Packet encode helpers - populate header and return pointer to wire data
// Note: seq and timestamp are zeroed; set by transport layer before sending

static inline sensor_reading_wire_t* sensor_reading_packet_init(
        sensor_reading_packet_t* pkt,
        uint8_t source_node)
{
    pkt->header.schema_hash = SENSOR_DATA_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    pkt->header.index = 0;
    return &pkt->data;
}

static inline alarm_event_wire_t* alarm_event_packet_init(
        alarm_event_packet_t* pkt,
        uint8_t source_node)
{
    pkt->header.schema_hash = SENSOR_DATA_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    pkt->header.index = 1;
    return &pkt->data;
}

static inline config_update_wire_t* config_update_packet_init(
        config_update_packet_t* pkt,
        uint8_t source_node)
{
    pkt->header.schema_hash = SENSOR_DATA_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    pkt->header.index = 2;
    return &pkt->data;
}

static inline heartbeat_wire_t* heartbeat_packet_init(
        heartbeat_packet_t* pkt,
        uint8_t source_node)
{
    pkt->header.schema_hash = SENSOR_DATA_SCHEMA_HASH;
    pkt->header.timestamp = 0.0;
    pkt->header.seq = 0;
    pkt->header.source_node = source_node;
    pkt->header.index = 3;
    return &pkt->data;
}

// Packet verify helpers - validate schema hash and index, return wire data pointer

static inline const sensor_reading_wire_t* sensor_reading_packet_verify(
        const sensor_reading_packet_t* pkt)
{
    if (pkt->header.schema_hash != SENSOR_DATA_SCHEMA_HASH) return NULL;
    if (pkt->header.index != 0) return NULL;
    return &pkt->data;
}

static inline const alarm_event_wire_t* alarm_event_packet_verify(
        const alarm_event_packet_t* pkt)
{
    if (pkt->header.schema_hash != SENSOR_DATA_SCHEMA_HASH) return NULL;
    if (pkt->header.index != 1) return NULL;
    return &pkt->data;
}

static inline const config_update_wire_t* config_update_packet_verify(
        const config_update_packet_t* pkt)
{
    if (pkt->header.schema_hash != SENSOR_DATA_SCHEMA_HASH) return NULL;
    if (pkt->header.index != 2) return NULL;
    return &pkt->data;
}

static inline const heartbeat_wire_t* heartbeat_packet_verify(
        const heartbeat_packet_t* pkt)
{
    if (pkt->header.schema_hash != SENSOR_DATA_SCHEMA_HASH) return NULL;
    if (pkt->header.index != 3) return NULL;
    return &pkt->data;
}

// Generic packet dispatch - returns record index or -1 on error
static inline int sensor_data_packet_dispatch(
        const void* packet_buffer,
        uint8_t* source_node_out,
        const void** data_out)
{
    const sensor_data_wire_header_t* hdr = (const sensor_data_wire_header_t*)packet_buffer;
    if (hdr->schema_hash != SENSOR_DATA_SCHEMA_HASH) return -1;
    if (hdr->index >= SENSOR_DATA_RECORD_COUNT) return -1;
    if (source_node_out) *source_node_out = hdr->source_node;
    if (data_out) *data_out = ((const uint8_t*)packet_buffer) + sizeof(sensor_data_wire_header_t);
    return hdr->index;
}

// Wire record payload sizes (for buffer allocation)
static const uint16_t sensor_data_wire_sizes[SENSOR_DATA_RECORD_COUNT] = {
    sizeof(sensor_reading_wire_t),  // sensor_reading
    sizeof(alarm_event_wire_t),  // alarm_event
    sizeof(config_update_wire_t),  // config_update
    sizeof(heartbeat_wire_t),  // heartbeat
};

// Full packet sizes including header (for socket send/recv)
static const uint16_t sensor_data_packet_sizes[SENSOR_DATA_RECORD_COUNT] = {
    sizeof(sensor_reading_packet_t),  // sensor_reading
    sizeof(alarm_event_packet_t),  // alarm_event
    sizeof(config_update_packet_t),  // config_update
    sizeof(heartbeat_packet_t),  // heartbeat
};

#ifdef __cplusplus
}
#endif
