// ============================================================================
// chain_flow_dsl_tests.h
// Generated by ChainTree S-Expression DSL v3.0
// DO NOT EDIT - regenerate from DSL
// ============================================================================

#ifndef CHAIN_FLOW_DSL_TESTS_H
#define CHAIN_FLOW_DSL_TESTS_H

#include <stdint.h>
#include <stdbool.h>
#include "s_engine_types.h"
#include "chain_flow_dsl_tests_records.h"

// ============================================================================
// FUNCTION HASH TABLES
// ============================================================================

static const uint32_t chain_flow_dsl_tests_oneshot_hashes[] = {
    0x5839B05BU,  // CFL_DISABLE_CHILDREN
    0x2B71A3C4U,  // CFL_ENABLE_CHILDREN
    0xD04E313CU,  // TEST_30_SET_STATE
    0xD42E3453U,  // CFL_ENABLE_CHILD
    0x4D385D9BU,  // TEST_31_SET_STATE
    0x64E47BB9U,  // CFL_LOG
    0xCA568877U,  // TEST_31_SET_MOTOR
    0x8ACEDC6EU,  // TEST_32_TOGGLE_LED
    0x81B642F2U,  // TEST_32_ENABLE_BUZZER
    0x8B9E28B2U,  // TEST_32_SET_LED
    0x1593B0BBU,  // TEST_32_NOTIFY_SYSTEM
    0x66EC2A1FU,  // CFL_INTERNAL_EVENT
    0x9BEEA78DU,  // TEST_32_DISABLE_ALL_OUTPUTS
    0x9B59F0CBU,  // TEST_32_SAVE_STATE
    0x4A7CE19FU,  // TEST_33_SET_VECTOR
    0xD58736DDU,  // TEST_33_SET_PID
    0x25590D31U,  // TEST_33_SET_SYSTEM
    0x88F549D9U,  // TEST_33_READ_VECTOR
    0xC12BB41BU,  // TEST_33_READ_PID
    0xCC1D9E5BU,  // TEST_33_READ_SYSTEM
    0x3C4C5B4AU,  // TEST_34_SET_UINT32
    0xF88A0240U,  // TEST_34_ALLOC_NODE
    0x5A022D1AU,  // TEST_34_ALLOC_SENSOR
    0xA851827CU,  // TEST_34_SET_UINT16
    0xA29AE36FU,  // TEST_34_READ_NODE
    0x5334E5D1U,  // TEST_34_READ_SENSOR
    0xA446E0E2U,  // TEST_34_READ_UINT32
    0x304C3A74U,  // TEST_34_READ_UINT16
    0x3311CA8AU,  // TEST_34_CHECK_NULL
    0xD354D8E9U,  // TEST_34_FREE_PTR
    0xEE44D556U,  // TEST_35_BUILD_LIST
    0xABB0C6FEU,  // TEST_35_TRAVERSE_LIST
    0x05F01006U,  // TEST_35_FREE_LIST
    0x1E3246ECU,  // TEST_36_COPY_PTR
    0x285D86ADU,  // TEST_36_VERIFY_SAME_PTR
    0x09440419U,  // TEST_36_MODIFY_NODE_VALUE
    0x689DAB3CU  // TEST_36_CLEAR_PTR
};

static const uint32_t chain_flow_dsl_tests_main_hashes[] = {
    0x6F1A656AU,  // CFL_TRIGGER_ON_CHANGE
    0x668F2290U,  // CFL_STATE_MACHINE
    0x1EBEF556U,  // CFL_STATE_ACTIONS
    0x818498FCU,  // CFL_TICK_DELAY
    0x9BC26392U,  // CFL_FIELD_DISPATCH
    0x2B7A339AU,  // CFL_EVENT_DISPATCH
    0x6C8FC67BU,  // CFL_PIPELINE
    0xE8D34100U,  // TEST_32_PROCESS_SCHEDULED_TASKS
    0x375B6A8FU,  // CFL_WAIT_EVENT
    0x86573308U,  // TEST_32_CHECK_THRESHOLD
    0x18DDD46FU,  // TEST_32_GENERATE_INTERNAL_EVENTS
    0x7E0874DBU  // TEST_32_RUN_BACKGROUND_TASKS
};

static const uint32_t chain_flow_dsl_tests_pred_hashes[] = {
    0x0A9FAC36U,  // CFL_S_BIT_OR
    0x0BBECBB8U  // CFL_S_BIT_AND
};

// ============================================================================
// RECORD DESCRIPTORS
// ============================================================================

static const s_expr_field_desc_t chain_flow_dsl_tests_test2_blackboard_fields[] = {
    { .name_hash = 0x7D0B279AU, .offset = 0, .size = 4 }  // placeholder
};

static const s_expr_field_desc_t chain_flow_dsl_tests_state_machine_blackboard_fields[] = {
    { .name_hash = 0x783132F6U, .offset = 0, .size = 4 },  // state
    { .name_hash = 0x97A4E54BU, .offset = 4, .size = 4 }  // state_b
};

static const s_expr_field_desc_t chain_flow_dsl_tests_robot_blackboard_fields[] = {
    { .name_hash = 0x93594AB2U, .offset = 0, .size = 4 }  // command
};

static const s_expr_field_desc_t chain_flow_dsl_tests_event_blackboard_fields[] = {
    { .name_hash = 0x77B5277EU, .offset = 0, .size = 4 },  // timer_count
    { .name_hash = 0xC4056E05U, .offset = 4, .size = 4 },  // sensor_value
    { .name_hash = 0xA08B063DU, .offset = 8, .size = 4 }  // event_id
};

static const s_expr_field_desc_t chain_flow_dsl_tests_vector3d_fields[] = {
    { .name_hash = 0xFD0C5087U, .offset = 0, .size = 4 },  // x
    { .name_hash = 0xFC0C4EF4U, .offset = 4, .size = 4 },  // y
    { .name_hash = 0xFF0C53ADU, .offset = 8, .size = 4 }  // z
};

static const s_expr_field_desc_t chain_flow_dsl_tests_pid_gains_fields[] = {
    { .name_hash = 0x573D1A6EU, .offset = 0, .size = 4 },  // kp
    { .name_hash = 0x403CF639U, .offset = 4, .size = 4 },  // ki
    { .name_hash = 0x4B3D078AU, .offset = 8, .size = 4 }  // kd
};

static const s_expr_field_desc_t chain_flow_dsl_tests_motor_state_fields[] = {
    { .name_hash = 0x934F4E0AU, .offset = 0, .size = 12 },  // position
    { .name_hash = 0x32741C32U, .offset = 12, .size = 12 },  // velocity
    { .name_hash = 0x473F6463U, .offset = 24, .size = 4 },  // torque
    { .name_hash = 0x02F3B39EU, .offset = 28, .size = 1 }  // enabled
};

static const s_expr_field_desc_t chain_flow_dsl_tests_system_state_fields[] = {
    { .name_hash = 0xCAF08472U, .offset = 0, .size = 32 },  // motor
    { .name_hash = 0x6940FD22U, .offset = 32, .size = 12 },  // pid
    { .name_hash = 0x967B9630U, .offset = 44, .size = 4 },  // system_time
    { .name_hash = 0x14FC1187U, .offset = 48, .size = 2 }  // error_code
};

static const s_expr_field_desc_t chain_flow_dsl_tests_node_data_fields[] = {
    { .name_hash = 0x37386AE0U, .offset = 0, .size = 4 },  // id
    { .name_hash = 0x425ED3CAU, .offset = 4, .size = 4 },  // value
    { .name_hash = 0x9C677A2CU, .offset = 8, .size = 1 }  // flags
};

static const s_expr_field_desc_t chain_flow_dsl_tests_list_node_fields[] = {
    { .name_hash = 0xD872E2A5U, .offset = 0, .size = 4 },  // data
    { .name_hash = 0x5CB68DE8U, .offset = 8, .size = 8 }  // next
};

static const s_expr_field_desc_t chain_flow_dsl_tests_sensor_reading_fields[] = {
    { .name_hash = 0xB283D523U, .offset = 0, .size = 4 },  // timestamp
    { .name_hash = 0xE9F2A935U, .offset = 4, .size = 4 },  // temperature
    { .name_hash = 0xCFA8A3A2U, .offset = 8, .size = 4 },  // pressure
    { .name_hash = 0x25C5B9A0U, .offset = 12, .size = 4 }  // humidity
};

static const s_expr_field_desc_t chain_flow_dsl_tests_system_context_fields[] = {
    { .name_hash = 0xDF8183BCU, .offset = 0, .size = 4 },  // system_id
    { .name_hash = 0x9589A68EU, .offset = 8, .size = 8 },  // primary_node
    { .name_hash = 0xD1B58A8CU, .offset = 16, .size = 8 },  // backup_node
    { .name_hash = 0x83B6367BU, .offset = 24, .size = 8 },  // sensor
    { .name_hash = 0x4A035315U, .offset = 32, .size = 8 },  // task_list
    { .name_hash = 0xF6DA5425U, .offset = 40, .size = 2 }  // node_count
};

static const s_expr_record_desc_t chain_flow_dsl_tests_records[] = {
    {
        .name_hash = 0x1703AE37U,  // "test2_blackboard"
        .total_size = 4,
        .field_count = 1,
        .fields = chain_flow_dsl_tests_test2_blackboard_fields
    },
    {
        .name_hash = 0xC89D038CU,  // "state_machine_blackboard"
        .total_size = 8,
        .field_count = 2,
        .fields = chain_flow_dsl_tests_state_machine_blackboard_fields
    },
    {
        .name_hash = 0xA6A4A169U,  // "robot_blackboard"
        .total_size = 4,
        .field_count = 1,
        .fields = chain_flow_dsl_tests_robot_blackboard_fields
    },
    {
        .name_hash = 0xBC450029U,  // "event_blackboard"
        .total_size = 12,
        .field_count = 3,
        .fields = chain_flow_dsl_tests_event_blackboard_fields
    },
    {
        .name_hash = 0xD299CEC5U,  // "vector3d"
        .total_size = 12,
        .field_count = 3,
        .fields = chain_flow_dsl_tests_vector3d_fields
    },
    {
        .name_hash = 0x76017CA9U,  // "pid_gains"
        .total_size = 12,
        .field_count = 3,
        .fields = chain_flow_dsl_tests_pid_gains_fields
    },
    {
        .name_hash = 0x7EFCE2D8U,  // "motor_state"
        .total_size = 32,
        .field_count = 4,
        .fields = chain_flow_dsl_tests_motor_state_fields
    },
    {
        .name_hash = 0x941691FAU,  // "system_state"
        .total_size = 52,
        .field_count = 4,
        .fields = chain_flow_dsl_tests_system_state_fields
    },
    {
        .name_hash = 0xA5DD10B6U,  // "node_data"
        .total_size = 12,
        .field_count = 3,
        .fields = chain_flow_dsl_tests_node_data_fields
    },
    {
        .name_hash = 0x79C6FBD6U,  // "list_node"
        .total_size = 16,
        .field_count = 2,
        .fields = chain_flow_dsl_tests_list_node_fields
    },
    {
        .name_hash = 0x296647E8U,  // "sensor_reading"
        .total_size = 16,
        .field_count = 4,
        .fields = chain_flow_dsl_tests_sensor_reading_fields
    },
    {
        .name_hash = 0xDB109A00U,  // "system_context"
        .total_size = 48,
        .field_count = 6,
        .fields = chain_flow_dsl_tests_system_context_fields
    }
};

// ============================================================================
// STRING TABLE
// ============================================================================

static const char* const chain_flow_dsl_tests_strings[] = {
    "Moving forward",  // index 0
    "Moving backward",  // index 1
    "Turning left",  // index 2
    "Turning right",  // index 3
    "Stopping",  // index 4
    "Idle - SHOULD NOT HAPPEN",  // index 5
    "Timer expired",  // index 6
    "Button pressed",  // index 7
    "Sensor reading",  // index 8
    "ALARM TRIGGERED",  // index 9
    "ALARM SETTING",  // index 10
    "Shutdown requested",  // index 11
    "Setting motor position",  // index 12
    "Reading motor position",  // index 13
    "Test 34: Pointer field test starting",  // index 14
    "Verifying pointer fields...",  // index 15
    "Testing NULL pointer handling...",  // index 16
    "Freeing allocated nodes...",  // index 17
    "Test 34: PASSED",  // index 18
    "Test 35: Linked list test starting",  // index 19
    "Test 35: PASSED",  // index 20
    "Test 36: Pointer sharing test starting",  // index 21
    "Test 36: PASSED"  // index 22
};

// ============================================================================
// TREE DEFINITIONS
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_2_params[] = {
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 0, .func_index = 0 },  // CFL_DISABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 22 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 1, .func_index = 0 },  // CFL_TRIGGER_ON_CHANGE
    { .type = 0x00, .int_val = 0 },
    { .type = 0x07, .brace_idx = 12 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 2, .func_index = 0 },  // CFL_S_BIT_OR
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 3, .func_index = 1 },  // CFL_S_BIT_AND
    { .type = 0x01, .uint_val = 0U },
    { .type = 0x01, .uint_val = 1U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x0A, .index_to_pointer = 0, .node_index = 4, .func_index = 1 },  // CFL_S_BIT_AND
    { .type = 0x01, .uint_val = 2U },
    { .type = 0x01, .uint_val = 3U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x06, .brace_idx = 12 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 1 },  // CFL_ENABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 0 },  // CFL_DISABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x06, .brace_idx = 22 },
    { .type = 0x0C, .int_val = 0 }  // SE_CONTINUE
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_4_params[] = {
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 0, .func_index = 2 },  // TEST_30_SET_STATE
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // state_b
    { .type = 0x00, .int_val = 0 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 62 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 1, .func_index = 1 },  // CFL_STATE_MACHINE
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // state_b
    { .type = 0x07, .brace_idx = 19 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 2, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 0 },  // CFL_DISABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 3 },  // CFL_ENABLE_CHILD
    { .type = 0x00, .int_val = 0 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 5, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 100 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 2 },  // TEST_30_SET_STATE
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // state_b
    { .type = 0x00, .int_val = 1 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 19 },
    { .type = 0x07, .brace_idx = 19 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 7, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 0 },  // CFL_DISABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 3 },  // CFL_ENABLE_CHILD
    { .type = 0x00, .int_val = 1 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 10, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 100 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 11, .func_index = 2 },  // TEST_30_SET_STATE
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // state_b
    { .type = 0x00, .int_val = 2 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 19 },
    { .type = 0x07, .brace_idx = 18 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 12, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 0 },  // CFL_DISABLE_CHILDREN
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 3 },  // CFL_ENABLE_CHILD
    { .type = 0x00, .int_val = 2 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 15, .func_index = 3 },  // CFL_ENABLE_CHILD
    { .type = 0x00, .int_val = 3 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 2, .node_index = 16, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 100 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 18 },
    { .type = 0x06, .brace_idx = 62 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_7_params[] = {
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x48, .index_to_pointer = 0, .node_index = 0, .func_index = 4 },  // TEST_31_SET_STATE
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x00, .int_val = 1 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 155 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 1, .func_index = 4 },  // CFL_FIELD_DISPATCH
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x05, .brace_idx = 29 },
    { .type = 0x00, .int_val = 1 },
    { .type = 0x07, .brace_idx = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 2, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 0, .str_len = 14 },  // "Moving forward"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 0 },
    { .type = 0x00, .int_val = 100 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = 100 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 6, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 50 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 4 },  // TEST_31_SET_STATE
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x00, .int_val = 2 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 26 },
    { .type = 0x06, .brace_idx = 29 },
    { .type = 0x05, .brace_idx = 29 },
    { .type = 0x00, .int_val = 2 },
    { .type = 0x07, .brace_idx = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 8, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 1, .str_len = 15 },  // "Moving backward"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 10, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 0 },
    { .type = 0x00, .int_val = -100 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 11, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = -100 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 12, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 50 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 4 },  // TEST_31_SET_STATE
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x00, .int_val = 3 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 26 },
    { .type = 0x06, .brace_idx = 29 },
    { .type = 0x05, .brace_idx = 29 },
    { .type = 0x00, .int_val = 3 },
    { .type = 0x07, .brace_idx = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 14, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 15, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 2, .str_len = 12 },  // "Turning left"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 0 },
    { .type = 0x00, .int_val = -50 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = 50 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 2, .node_index = 18, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 25 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 4 },  // TEST_31_SET_STATE
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x00, .int_val = 4 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 26 },
    { .type = 0x06, .brace_idx = 29 },
    { .type = 0x05, .brace_idx = 29 },
    { .type = 0x00, .int_val = 4 },
    { .type = 0x07, .brace_idx = 26 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 20, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 21, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 3, .str_len = 13 },  // "Turning right"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 22, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 0 },
    { .type = 0x00, .int_val = 50 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 23, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = -50 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x89, .index_to_pointer = 3, .node_index = 24, .func_index = 3 },  // CFL_TICK_DELAY
    { .type = 0x00, .int_val = 25 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 25, .func_index = 4 },  // TEST_31_SET_STATE
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // command
    { .type = 0x00, .int_val = 5 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 26 },
    { .type = 0x06, .brace_idx = 29 },
    { .type = 0x05, .brace_idx = 20 },
    { .type = 0x00, .int_val = 5 },
    { .type = 0x07, .brace_idx = 17 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 26, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 27, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 4, .str_len = 8 },  // "Stopping"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 28, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 0 },
    { .type = 0x00, .int_val = 0 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 29, .func_index = 6 },  // TEST_31_SET_MOTOR
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = 0 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 17 },
    { .type = 0x06, .brace_idx = 20 },
    { .type = 0x05, .brace_idx = 10 },
    { .type = 0x00, .int_val = 0 },
    { .type = 0x07, .brace_idx = 7 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 30, .func_index = 2 },  // CFL_STATE_ACTIONS
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 31, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 5, .str_len = 24 },  // "Idle - SHOULD NOT HAPPEN"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 7 },
    { .type = 0x06, .brace_idx = 10 },
    { .type = 0x06, .brace_idx = 155 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_8_params[] = {
    { .type = 0x07, .brace_idx = 114 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 5 },  // CFL_EVENT_DISPATCH
    { .type = 0x05, .brace_idx = 13 },
    { .type = 0x00, .int_val = 60929 },
    { .type = 0x07, .brace_idx = 10 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 1, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 6, .str_len = 13 },  // "Timer expired"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 3, .func_index = 7 },  // TEST_32_PROCESS_SCHEDULED_TASKS
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 10 },
    { .type = 0x06, .brace_idx = 13 },
    { .type = 0x05, .brace_idx = 19 },
    { .type = 0x00, .int_val = 60930 },
    { .type = 0x07, .brace_idx = 16 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 4, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 7, .str_len = 14 },  // "Button pressed"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x89, .index_to_pointer = 0, .node_index = 6, .func_index = 8 },  // CFL_WAIT_EVENT
    { .type = 0x00, .int_val = 60930 },
    { .type = 0x00, .int_val = 10 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 7 },  // TEST_32_TOGGLE_LED
    { .type = 0x00, .int_val = 0 },
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 16 },
    { .type = 0x06, .brace_idx = 19 },
    { .type = 0x05, .brace_idx = 15 },
    { .type = 0x00, .int_val = 60931 },
    { .type = 0x07, .brace_idx = 12 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 8, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 8, .str_len = 14 },  // "Sensor reading"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 10, .func_index = 9 },  // TEST_32_CHECK_THRESHOLD
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // sensor_value
    { .type = 0x00, .int_val = 50 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 12 },
    { .type = 0x06, .brace_idx = 15 },
    { .type = 0x05, .brace_idx = 31 },
    { .type = 0x00, .int_val = 60932 },
    { .type = 0x07, .brace_idx = 28 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 11, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 12, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 9, .str_len = 15 },  // "ALARM TRIGGERED"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 8 },  // TEST_32_ENABLE_BUZZER
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 9 },  // TEST_32_SET_LED
    { .type = 0x00, .int_val = 1 },
    { .type = 0x00, .int_val = 1 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 15, .func_index = 10 },  // TEST_32_NOTIFY_SYSTEM
    { .type = 0x03, .str_hash = 0x6B3DA4FAU },  // "ALARM"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 11 },  // CFL_INTERNAL_EVENT
    { .type = 0x00, .int_val = 60933 },
    { .type = 0x00, .int_val = 1 },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 10, .str_len = 13 },  // "ALARM SETTING"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 1 },  // SE_HALT
    { .type = 0x06, .brace_idx = 28 },
    { .type = 0x06, .brace_idx = 31 },
    { .type = 0x05, .brace_idx = 16 },
    { .type = 0x00, .int_val = 60933 },
    { .type = 0x07, .brace_idx = 13 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 18, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 11, .str_len = 18 },  // "Shutdown requested"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 20, .func_index = 12 },  // TEST_32_DISABLE_ALL_OUTPUTS
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 21, .func_index = 13 },  // TEST_32_SAVE_STATE
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 13 },
    { .type = 0x06, .brace_idx = 16 },
    { .type = 0x05, .brace_idx = 12 },
    { .type = 0x00, .int_val = 4 },
    { .type = 0x07, .brace_idx = 9 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 22, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x89, .index_to_pointer = 1, .node_index = 23, .func_index = 10 },  // TEST_32_GENERATE_INTERNAL_EVENTS
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x07, .brace_idx = 2 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 24, .func_index = 11 },  // TEST_32_RUN_BACKGROUND_TASKS
    { .type = 0x06, .brace_idx = 2 },
    { .type = 0x0C, .int_val = 0 },  // SE_CONTINUE
    { .type = 0x06, .brace_idx = 9 },
    { .type = 0x06, .brace_idx = 12 },
    { .type = 0x06, .brace_idx = 114 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_10_params[] = {
    { .type = 0x07, .brace_idx = 79 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 12, .str_len = 22 },  // "Setting motor position"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 14 },  // TEST_33_SET_VECTOR
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // motor.position.x
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // motor.position.y
    { .type = 0x0B, .field_offset = 8, .field_size = 4 },  // motor.position.z
    { .type = 0x02, .float_val = 100.000000f },
    { .type = 0x02, .float_val = 200.000000f },
    { .type = 0x02, .float_val = 300.000000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 14 },  // TEST_33_SET_VECTOR
    { .type = 0x0B, .field_offset = 12, .field_size = 4 },  // motor.velocity.x
    { .type = 0x0B, .field_offset = 16, .field_size = 4 },  // motor.velocity.y
    { .type = 0x0B, .field_offset = 20, .field_size = 4 },  // motor.velocity.z
    { .type = 0x02, .float_val = 1.500000f },
    { .type = 0x02, .float_val = 2.500000f },
    { .type = 0x02, .float_val = 3.500000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 15 },  // TEST_33_SET_PID
    { .type = 0x0B, .field_offset = 32, .field_size = 4 },  // pid.kp
    { .type = 0x0B, .field_offset = 36, .field_size = 4 },  // pid.ki
    { .type = 0x0B, .field_offset = 40, .field_size = 4 },  // pid.kd
    { .type = 0x02, .float_val = 1.000000f },
    { .type = 0x02, .float_val = 0.100000f },
    { .type = 0x02, .float_val = 0.010000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 16 },  // TEST_33_SET_SYSTEM
    { .type = 0x0B, .field_offset = 44, .field_size = 4 },  // system_time
    { .type = 0x0B, .field_offset = 48, .field_size = 2 },  // error_code
    { .type = 0x01, .uint_val = 12345678U },
    { .type = 0x01, .uint_val = 0U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 13, .str_len = 22 },  // "Reading motor position"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 17 },  // TEST_33_READ_VECTOR
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // motor.position.x
    { .type = 0x0B, .field_offset = 4, .field_size = 4 },  // motor.position.y
    { .type = 0x0B, .field_offset = 8, .field_size = 4 },  // motor.position.z
    { .type = 0x02, .float_val = 100.000000f },
    { .type = 0x02, .float_val = 200.000000f },
    { .type = 0x02, .float_val = 300.000000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 17 },  // TEST_33_READ_VECTOR
    { .type = 0x0B, .field_offset = 12, .field_size = 4 },  // motor.velocity.x
    { .type = 0x0B, .field_offset = 16, .field_size = 4 },  // motor.velocity.y
    { .type = 0x0B, .field_offset = 20, .field_size = 4 },  // motor.velocity.z
    { .type = 0x02, .float_val = 1.500000f },
    { .type = 0x02, .float_val = 2.500000f },
    { .type = 0x02, .float_val = 3.500000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 8 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 18 },  // TEST_33_READ_PID
    { .type = 0x0B, .field_offset = 32, .field_size = 4 },  // pid.kp
    { .type = 0x0B, .field_offset = 36, .field_size = 4 },  // pid.ki
    { .type = 0x0B, .field_offset = 40, .field_size = 4 },  // pid.kd
    { .type = 0x02, .float_val = 1.000000f },
    { .type = 0x02, .float_val = 0.100000f },
    { .type = 0x02, .float_val = 0.010000f },
    { .type = 0x06, .brace_idx = 8 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 10, .func_index = 19 },  // TEST_33_READ_SYSTEM
    { .type = 0x0B, .field_offset = 44, .field_size = 4 },  // system_time
    { .type = 0x0B, .field_offset = 48, .field_size = 2 },  // error_code
    { .type = 0x01, .uint_val = 12345678U },
    { .type = 0x01, .uint_val = 0U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 79 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_11_params[] = {
    { .type = 0x07, .brace_idx = 109 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 14, .str_len = 36 },  // "Test 34: Pointer field test starting"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 20 },  // TEST_34_SET_UINT32
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // system_id
    { .type = 0x01, .uint_val = 305419896U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 21 },  // TEST_34_ALLOC_NODE
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x01, .uint_val = 100U },
    { .type = 0x02, .float_val = 3.141590f },
    { .type = 0x01, .uint_val = 15U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 21 },  // TEST_34_ALLOC_NODE
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x01, .uint_val = 200U },
    { .type = 0x02, .float_val = 2.718280f },
    { .type = 0x01, .uint_val = 240U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 7 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 22 },  // TEST_34_ALLOC_SENSOR
    { .type = 0x0B, .field_offset = 24, .field_size = 8 },  // sensor
    { .type = 0x01, .uint_val = 1000000U },
    { .type = 0x02, .float_val = 25.500000f },
    { .type = 0x02, .float_val = 1013.250000f },
    { .type = 0x02, .float_val = 65.000000f },
    { .type = 0x06, .brace_idx = 7 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 23 },  // TEST_34_SET_UINT16
    { .type = 0x0B, .field_offset = 40, .field_size = 2 },  // node_count
    { .type = 0x01, .uint_val = 2U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 15, .str_len = 27 },  // "Verifying pointer fields..."
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 24 },  // TEST_34_READ_NODE
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x01, .uint_val = 100U },
    { .type = 0x02, .float_val = 3.141590f },
    { .type = 0x01, .uint_val = 15U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 24 },  // TEST_34_READ_NODE
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x01, .uint_val = 200U },
    { .type = 0x02, .float_val = 2.718280f },
    { .type = 0x01, .uint_val = 240U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 7 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 10, .func_index = 25 },  // TEST_34_READ_SENSOR
    { .type = 0x0B, .field_offset = 24, .field_size = 8 },  // sensor
    { .type = 0x01, .uint_val = 1000000U },
    { .type = 0x02, .float_val = 25.500000f },
    { .type = 0x02, .float_val = 1013.250000f },
    { .type = 0x02, .float_val = 65.000000f },
    { .type = 0x06, .brace_idx = 7 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 11, .func_index = 26 },  // TEST_34_READ_UINT32
    { .type = 0x0B, .field_offset = 0, .field_size = 4 },  // system_id
    { .type = 0x01, .uint_val = 305419896U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 12, .func_index = 27 },  // TEST_34_READ_UINT16
    { .type = 0x0B, .field_offset = 40, .field_size = 2 },  // node_count
    { .type = 0x01, .uint_val = 2U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 13, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 16, .str_len = 32 },  // "Testing NULL pointer handling..."
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 14, .func_index = 28 },  // TEST_34_CHECK_NULL
    { .type = 0x0B, .field_offset = 32, .field_size = 8 },  // task_list
    { .type = 0x01, .uint_val = 1U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 15, .func_index = 28 },  // TEST_34_CHECK_NULL
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x01, .uint_val = 0U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 16, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 17, .str_len = 26 },  // "Freeing allocated nodes..."
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 17, .func_index = 29 },  // TEST_34_FREE_PTR
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 18, .func_index = 29 },  // TEST_34_FREE_PTR
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 19, .func_index = 29 },  // TEST_34_FREE_PTR
    { .type = 0x0B, .field_offset = 24, .field_size = 8 },  // sensor
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 20, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 18, .str_len = 15 },  // "Test 34: PASSED"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 109 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_12_params[] = {
    { .type = 0x07, .brace_idx = 30 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 19, .str_len = 34 },  // "Test 35: Linked list test starting"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 30 },  // TEST_35_BUILD_LIST
    { .type = 0x0B, .field_offset = 32, .field_size = 8 },  // task_list
    { .type = 0x01, .uint_val = 3U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 31 },  // TEST_35_TRAVERSE_LIST
    { .type = 0x0B, .field_offset = 32, .field_size = 8 },  // task_list
    { .type = 0x01, .uint_val = 3U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 32 },  // TEST_35_FREE_LIST
    { .type = 0x0B, .field_offset = 32, .field_size = 8 },  // task_list
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 28 },  // TEST_34_CHECK_NULL
    { .type = 0x0B, .field_offset = 32, .field_size = 8 },  // task_list
    { .type = 0x01, .uint_val = 1U },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 20, .str_len = 15 },  // "Test 35: PASSED"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 30 }
};

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_13_params[] = {
    { .type = 0x07, .brace_idx = 48 },
    { .type = 0x09, .index_to_pointer = 0, .node_index = 0, .func_index = 6 },  // CFL_PIPELINE
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 1, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 21, .str_len = 38 },  // "Test 36: Pointer sharing test starting"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 2, .func_index = 21 },  // TEST_34_ALLOC_NODE
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x01, .uint_val = 999U },
    { .type = 0x02, .float_val = 42.000000f },
    { .type = 0x01, .uint_val = 171U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 3, .func_index = 33 },  // TEST_36_COPY_PTR
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 4, .func_index = 34 },  // TEST_36_VERIFY_SAME_PTR
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 4 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 5, .func_index = 35 },  // TEST_36_MODIFY_NODE_VALUE
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x02, .float_val = 99.990000f },
    { .type = 0x06, .brace_idx = 4 },
    { .type = 0x07, .brace_idx = 6 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 6, .func_index = 24 },  // TEST_34_READ_NODE
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x01, .uint_val = 999U },
    { .type = 0x02, .float_val = 99.990000f },
    { .type = 0x01, .uint_val = 171U },
    { .type = 0x06, .brace_idx = 6 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 7, .func_index = 29 },  // TEST_34_FREE_PTR
    { .type = 0x0B, .field_offset = 8, .field_size = 8 },  // primary_node
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 8, .func_index = 36 },  // TEST_36_CLEAR_PTR
    { .type = 0x0B, .field_offset = 16, .field_size = 8 },  // backup_node
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x07, .brace_idx = 3 },
    { .type = 0x08, .index_to_pointer = 0, .node_index = 9, .func_index = 5 },  // CFL_LOG
    { .type = 0x0D, .str_index = 22, .str_len = 15 },  // "Test 36: PASSED"
    { .type = 0x06, .brace_idx = 3 },
    { .type = 0x0C, .int_val = 5 },  // SE_FUNCTION_TERMINATE
    { .type = 0x06, .brace_idx = 48 }
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_2_def = {
    .name_hash = 0x1BE41A2FU,  // "s_expression_test_2"
    .record_hash = 0x00000000U,
    .params = chain_flow_dsl_tests_s_expression_test_2_params,
    .param_count = 27,
    .func_node_count = 7,
    .pointer_count = 0,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_4_def = {
    .name_hash = 0x19E41709U,  // "s_expression_test_4"
    .record_hash = 0xC89D038CU,
    .params = chain_flow_dsl_tests_s_expression_test_4_params,
    .param_count = 68,
    .func_node_count = 17,
    .pointer_count = 3,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_7_def = {
    .name_hash = 0x16E41250U,  // "s_expression_test_7"
    .record_hash = 0xA6A4A169U,
    .params = chain_flow_dsl_tests_s_expression_test_7_params,
    .param_count = 161,
    .func_node_count = 32,
    .pointer_count = 4,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_8_def = {
    .name_hash = 0x25E429EDU,  // "s_expression_test_8"
    .record_hash = 0xBC450029U,
    .params = chain_flow_dsl_tests_s_expression_test_8_params,
    .param_count = 115,
    .func_node_count = 25,
    .pointer_count = 2,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_10_def = {
    .name_hash = 0x6D17FDF6U,  // "s_expression_test_10"
    .record_hash = 0x941691FAU,
    .params = chain_flow_dsl_tests_s_expression_test_10_params,
    .param_count = 80,
    .func_node_count = 11,
    .pointer_count = 0,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_11_def = {
    .name_hash = 0x6E17FF89U,  // "s_expression_test_11"
    .record_hash = 0xDB109A00U,
    .params = chain_flow_dsl_tests_s_expression_test_11_params,
    .param_count = 110,
    .func_node_count = 21,
    .pointer_count = 0,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_12_def = {
    .name_hash = 0x6B17FAD0U,  // "s_expression_test_12"
    .record_hash = 0xDB109A00U,
    .params = chain_flow_dsl_tests_s_expression_test_12_params,
    .param_count = 31,
    .func_node_count = 7,
    .pointer_count = 0,
};

static const s_expr_tree_def_t chain_flow_dsl_tests_s_expression_test_13_def = {
    .name_hash = 0x6C17FC63U,  // "s_expression_test_13"
    .record_hash = 0xDB109A00U,
    .params = chain_flow_dsl_tests_s_expression_test_13_params,
    .param_count = 49,
    .func_node_count = 10,
    .pointer_count = 0,
};

// ============================================================================
// MODULE DEFINITION
// ============================================================================

static const s_expr_tree_def_t chain_flow_dsl_tests_trees[] = {
    chain_flow_dsl_tests_s_expression_test_2_def,
    chain_flow_dsl_tests_s_expression_test_4_def,
    chain_flow_dsl_tests_s_expression_test_7_def,
    chain_flow_dsl_tests_s_expression_test_8_def,
    chain_flow_dsl_tests_s_expression_test_10_def,
    chain_flow_dsl_tests_s_expression_test_11_def,
    chain_flow_dsl_tests_s_expression_test_12_def,
    chain_flow_dsl_tests_s_expression_test_13_def
};

static const s_expr_module_def_t chain_flow_dsl_tests_module = {
    .name_hash = 0xE6318EC1U,  // "chain_flow_dsl_tests"
    .trees = chain_flow_dsl_tests_trees,
    .tree_count = 8,
    .is_64bit = false,
    .oneshot_hashes = chain_flow_dsl_tests_oneshot_hashes,
    .oneshot_count = 37,
    .main_hashes = chain_flow_dsl_tests_main_hashes,
    .main_count = 12,
    .pred_hashes = chain_flow_dsl_tests_pred_hashes,
    .pred_count = 2,
    .max_func_node_count = 32,
    .max_pointer_count = 4,
    .max_param_count = 161,
    .records = chain_flow_dsl_tests_records,
    .record_count = 12,
    .string_table = chain_flow_dsl_tests_strings,
    .string_count = 23,
};

#endif // CHAIN_FLOW_DSL_TESTS_H
