// ============================================================================
// chain_flow_dsl_tests_module.h
// Generated by ChainTree S-Expression DSL v2.5
// DO NOT EDIT
// ============================================================================

#ifndef CHAIN_FLOW_DSL_TESTS_MODULE_H
#define CHAIN_FLOW_DSL_TESTS_MODULE_H

#include <stdint.h>
#include <stdbool.h>

// Size configuration
#define MODULE_IS_64BIT 0
#define CHAIN_FLOW_DSL_TESTS_IS_64BIT 0

// Type aliases (based on 64-bit flag)
typedef int32_t ct_int_t;
typedef uint32_t ct_uint_t;
typedef float ct_float_t;
#define CT_TYPES_DEFINED 1

#include "s_engine_types.h"

// ============================================================================
// FUNCTION NAME TABLES (shared by all trees)
// ============================================================================

// Oneshot (@) function names
static const char* const chain_flow_dsl_tests_oneshot_names[] = {
    "CFL_LOG",
    "CFL_ENABLE_CHILDREN",
    "CFL_DISABLE_CHILDREN",
};
#define CHAIN_FLOW_DSL_TESTS_ONESHOT_NAMES_COUNT 3

// Boolean (?) function names
static const char* const chain_flow_dsl_tests_boolean_names[] = {
    "CFL_READ_BIT",
};
#define CHAIN_FLOW_DSL_TESTS_BOOLEAN_NAMES_COUNT 1

// Main (!) function names
static const char* const chain_flow_dsl_tests_main_names[] = { NULL };
#define CHAIN_FLOW_DSL_TESTS_MAIN_NAMES_COUNT 0

// Data strings
static const char* const chain_flow_dsl_tests_strings[] = {
    "complex condition met",
    "complex condition not met",
};
#define CHAIN_FLOW_DSL_TESTS_STRINGS_COUNT 2

// ============================================================================
// TREE: s_expression_test_1_2
// ============================================================================

static const s_expr_param_t chain_flow_dsl_tests_s_expression_test_1_2_params[] = {
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 0 },  // [0]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 1 },  // [1]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 2 },  // [2]
    { .type = S_EXPR_PARAM_INT, .reserved = {0}, .i = 3 },  // [3]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 0 },  // [4]
    { .type = S_EXPR_PARAM_STRING, .reserved = {0}, .str_index = 1 },  // [5]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_1_2_PARAM_COUNT 6

static const s_expr_node_t chain_flow_dsl_tests_s_expression_test_1_2_nodes[] = {
    { .type = 0x01, .child_count = 2, .node_index = 0, .first_child = 0x0001, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [0]
    { .type = 0x03, .child_count = 3, .node_index = 1, .first_child = 0x0002, .next_sibling = 0x0011, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [1]
    { .type = 0x07, .child_count = 2, .node_index = 2, .first_child = 0x0003, .next_sibling = 0x0009, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [2]
    { .type = 0x06, .child_count = 2, .node_index = 3, .first_child = 0x0004, .next_sibling = 0x0006, .fn_index = 0, .param_offset = 0, .param_count = 0, .reserved = 0 }, // [3]
    { .type = 0x80, .child_count = 0, .node_index = 4, .first_child = 0xFFFF, .next_sibling = 0x0005, .fn_index = 0, .param_offset = 0, .param_count = 1, .reserved = 0 }, // [4]
    { .type = 0x80, .child_count = 0, .node_index = 5, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 1, .param_count = 1, .reserved = 0 }, // [5]
    { .type = 0x06, .child_count = 2, .node_index = 6, .first_child = 0x0007, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 2, .param_count = 0, .reserved = 0 }, // [6]
    { .type = 0x80, .child_count = 0, .node_index = 7, .first_child = 0xFFFF, .next_sibling = 0x0008, .fn_index = 0, .param_offset = 2, .param_count = 1, .reserved = 0 }, // [7]
    { .type = 0x80, .child_count = 0, .node_index = 8, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 3, .param_count = 1, .reserved = 0 }, // [8]
    { .type = 0x01, .child_count = 3, .node_index = 9, .first_child = 0x000A, .next_sibling = 0x000D, .fn_index = 0, .param_offset = 4, .param_count = 0, .reserved = 0 }, // [9]
    { .type = 0x40, .child_count = 0, .node_index = 10, .first_child = 0xFFFF, .next_sibling = 0x000B, .fn_index = 0, .param_offset = 4, .param_count = 1, .reserved = 0 }, // [10]
    { .type = 0x40, .child_count = 0, .node_index = 11, .first_child = 0xFFFF, .next_sibling = 0x000C, .fn_index = 1, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [11]
    { .type = 0x09, .child_count = 0, .node_index = 12, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [12]
    { .type = 0x01, .child_count = 3, .node_index = 13, .first_child = 0x000E, .next_sibling = 0xFFFF, .fn_index = 0, .param_offset = 5, .param_count = 0, .reserved = 0 }, // [13]
    { .type = 0x40, .child_count = 0, .node_index = 14, .first_child = 0xFFFF, .next_sibling = 0x000F, .fn_index = 0, .param_offset = 5, .param_count = 1, .reserved = 0 }, // [14]
    { .type = 0x40, .child_count = 0, .node_index = 15, .first_child = 0xFFFF, .next_sibling = 0x0010, .fn_index = 2, .param_offset = 6, .param_count = 0, .reserved = 0 }, // [15]
    { .type = 0x09, .child_count = 0, .node_index = 16, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 6, .param_count = 0, .reserved = 0 }, // [16]
    { .type = 0x09, .child_count = 0, .node_index = 17, .first_child = 0xFFFF, .next_sibling = 0xFFFF, .fn_index = 1, .param_offset = 6, .param_count = 0, .reserved = 0 }, // [17]
};
#define CHAIN_FLOW_DSL_TESTS_S_EXPRESSION_TEST_1_2_NODE_COUNT 18

// ============================================================================
// TREE DEFINITIONS
// ============================================================================

static const s_expr_tree_def_t chain_flow_dsl_tests_trees[] = {
    {
        .name = "s_expression_test_1_2",
        .nodes = chain_flow_dsl_tests_s_expression_test_1_2_nodes,
        .node_count = 18,
        .root_index = 0,
        .params = chain_flow_dsl_tests_s_expression_test_1_2_params,
        .param_count = 6,
    },
};
#define CHAIN_FLOW_DSL_TESTS_TREE_COUNT 1

// ============================================================================
// MODULE DEFINITION
// ============================================================================

static const s_expr_module_def_t chain_flow_dsl_tests_module = {
    .name = "chain_flow_dsl_tests_1",
    .trees = chain_flow_dsl_tests_trees,
    .tree_count = 1,
    .is_64bit = false,

    .oneshot_names = chain_flow_dsl_tests_oneshot_names,
    .boolean_names = chain_flow_dsl_tests_boolean_names,
    .main_names = chain_flow_dsl_tests_main_names,
    .strings = chain_flow_dsl_tests_strings,

    .oneshot_count = 3,
    .boolean_count = 1,
    .main_count = 0,
    .string_count = 2,

    .max_node_count = 18,
};

#endif // CHAIN_FLOW_DSL_TESTS_MODULE_H
