// ============================================================================
// chain_flow_dsl_tests_user_registration.c
// Generated by ChainTree S-Expression DSL v3.0
// DO NOT EDIT - regenerate from DSL
// ============================================================================

#include "chain_flow_dsl_tests_user_functions.h"
#include "s_engine_module.h"
#include <stdio.h>

// ============================================================================
// REGISTRATION TABLES
// ============================================================================

#define ARRAY_COUNT(arr) (sizeof(arr) / sizeof((arr)[0]))

static const s_expr_fn_entry_named_t user_oneshot_entries_named[] = {
    { "TEST_30_SET_STATE", (void*)test_30_set_state_oneshot },
    { "TEST_31_SET_STATE", (void*)test_31_set_state_oneshot },
    { "TEST_31_SET_MOTOR", (void*)test_31_set_motor_oneshot },
    { "TEST_32_TOGGLE_LED", (void*)test_32_toggle_led_oneshot },
    { "TEST_32_ENABLE_BUZZER", (void*)test_32_enable_buzzer_oneshot },
    { "TEST_32_SET_LED", (void*)test_32_set_led_oneshot },
    { "TEST_32_NOTIFY_SYSTEM", (void*)test_32_notify_system_oneshot },
    { "TEST_32_DISABLE_ALL_OUTPUTS", (void*)test_32_disable_all_outputs_oneshot },
    { "TEST_32_SAVE_STATE", (void*)test_32_save_state_oneshot },
    { "TEST_33_SET_VECTOR", (void*)test_33_set_vector_oneshot },
    { "TEST_33_SET_PID", (void*)test_33_set_pid_oneshot },
    { "TEST_33_SET_SYSTEM", (void*)test_33_set_system_oneshot },
    { "TEST_33_READ_VECTOR", (void*)test_33_read_vector_oneshot },
    { "TEST_33_READ_PID", (void*)test_33_read_pid_oneshot },
    { "TEST_33_READ_SYSTEM", (void*)test_33_read_system_oneshot },
    { "TEST_34_SET_UINT32", (void*)test_34_set_uint32_oneshot },
    { "TEST_34_ALLOC_NODE", (void*)test_34_alloc_node_oneshot },
    { "TEST_34_ALLOC_SENSOR", (void*)test_34_alloc_sensor_oneshot },
    { "TEST_34_SET_UINT16", (void*)test_34_set_uint16_oneshot },
    { "TEST_34_READ_NODE", (void*)test_34_read_node_oneshot },
    { "TEST_34_READ_SENSOR", (void*)test_34_read_sensor_oneshot },
    { "TEST_34_READ_UINT32", (void*)test_34_read_uint32_oneshot },
    { "TEST_34_READ_UINT16", (void*)test_34_read_uint16_oneshot },
    { "TEST_34_CHECK_NULL", (void*)test_34_check_null_oneshot },
    { "TEST_34_FREE_PTR", (void*)test_34_free_ptr_oneshot },
    { "TEST_35_BUILD_LIST", (void*)test_35_build_list_oneshot },
    { "TEST_35_TRAVERSE_LIST", (void*)test_35_traverse_list_oneshot },
    { "TEST_35_FREE_LIST", (void*)test_35_free_list_oneshot },
    { "TEST_36_COPY_PTR", (void*)test_36_copy_ptr_oneshot },
    { "TEST_36_VERIFY_SAME_PTR", (void*)test_36_verify_same_ptr_oneshot },
    { "TEST_36_MODIFY_NODE_VALUE", (void*)test_36_modify_node_value_oneshot },
    { "TEST_36_CLEAR_PTR", (void*)test_36_clear_ptr_oneshot },
    { "TEST_37_COPY_STATIC_NETWORK", (void*)test_37_copy_static_network_oneshot },
    { "TEST_37_VERIFY_NETWORK", (void*)test_37_verify_network_oneshot },
    { "TEST_37_VERIFY_SENSORS", (void*)test_37_verify_sensors_oneshot },
    { "TEST_37_VERIFY_DEVICE_NAME", (void*)test_37_verify_device_name_oneshot },
    { "TEST_37_VERIFY_DEVICE_SERIAL", (void*)test_37_verify_device_serial_oneshot },
    { "TEST_37_VERIFY_DEVICE_INFO", (void*)test_37_verify_device_info_oneshot },
    { "TEST_37_VERIFY_TOP_LEVEL", (void*)test_37_verify_top_level_oneshot },
    { "TEST_37_DUMP_STATE", (void*)test_37_dump_state_oneshot },
    { "TEST_37_VERIFY_STRING_PTR", (void*)test_37_verify_string_ptr_oneshot },
};
static s_expr_fn_entry_t user_oneshot_entries[ARRAY_COUNT(user_oneshot_entries_named)];

static const s_expr_fn_entry_named_t user_main_entries_named[] = {
    { "TEST_32_PROCESS_SCHEDULED_TASKS", (void*)test_32_process_scheduled_tasks_main },
    { "TEST_32_CHECK_THRESHOLD", (void*)test_32_check_threshold_main },
    { "TEST_32_GENERATE_INTERNAL_EVENTS", (void*)test_32_generate_internal_events_main },
    { "TEST_32_RUN_BACKGROUND_TASKS", (void*)test_32_run_background_tasks_main },
};
static s_expr_fn_entry_t user_main_entries[ARRAY_COUNT(user_main_entries_named)];

static s_expr_fn_table_t user_oneshot_table;
static s_expr_fn_table_t user_main_table;

// ============================================================================
// INITIALIZATION
// ============================================================================

static void init_user_function_tables(void) {
    s_expr_build_fn_table(
        user_oneshot_entries_named,
        user_oneshot_entries,
        ARRAY_COUNT(user_oneshot_entries_named)
    );
    user_oneshot_table.entries = user_oneshot_entries;
    user_oneshot_table.count = ARRAY_COUNT(user_oneshot_entries);

    s_expr_build_fn_table(
        user_main_entries_named,
        user_main_entries,
        ARRAY_COUNT(user_main_entries_named)
    );
    user_main_table.entries = user_main_entries;
    user_main_table.count = ARRAY_COUNT(user_main_entries);

}

// ============================================================================
// LOAD FUNCTION
// ============================================================================

void load_user_s_functions(cfl_runtime_handle_t* handle) {
    if (!handle || !handle->s_expr_modules) {
        printf("ERROR: load_user_s_functions: invalid handle\n");
        return;
    }
    if (handle->s_expr_module_count <= 0) {
        printf("ERROR: load_user_s_functions: no modules\n");
        return;
    }

    static bool initialized = false;
    if (!initialized) {
        init_user_function_tables();
        initialized = true;
    }

    s_expr_module_t** modules = (s_expr_module_t**)handle->s_expr_modules;
    for (int i = 0; i < handle->s_expr_module_count; i++) {
        if (!modules[i]) continue;
        s_expr_module_register_oneshot(modules[i], &user_oneshot_table);
        s_expr_module_register_main(modules[i], &user_main_table);
    }
}

