// ============================================================================
// state_machine_test_user_functions.h
// User function prototypes for state_machine_test
// DO NOT EDIT - Generated by s_expr_dsl v5.4
// NOTE: Builtin functions (SE_*) are in s_engine_builtins.h
// NOTE: Lua functions are in state_machine_test_lua_registration.c
// ============================================================================

#ifndef STATE_MACHINE_TEST_USER_FUNCTIONS_H
#define STATE_MACHINE_TEST_USER_FUNCTIONS_H

#include "s_engine_types.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif // STATE_MACHINE_TEST_USER_FUNCTIONS_H
