// ============================================================================
// function_dictionary_debug.h
// Debug hash reference for function_dictionary
// DO NOT EDIT - Generated by s_expr_dsl v5.2
// ============================================================================

#ifndef FUNCTION_DICTIONARY_DEBUG_H
#define FUNCTION_DICTIONARY_DEBUG_H

// Oneshot functions
#define H_C0225974 0xC0225974  // SE_LOAD_FUNCTION_DICT
#define H_08E351ED 0x08E351ED  // SE_PUSH_STACK
#define H_CEBBEFA4 0xCEBBEFA4  // SE_LOG
#define H_596C457D 0x596C457D  // SE_QUAD
#define H_FFF84A15 0xFFF84A15  // SE_SET_FIELD

// Main functions
#define H_C7FEA7F6 0xC7FEA7F6  // SE_FUNCTION_INTERFACE
#define H_4F4BB2E1 0x4F4BB2E1  // SE_SEQUENCE_ONCE
#define H_753D7572 0x753D7572  // SE_STACK_FRAME_INSTANCE
#define H_2D91A4AC 0x2D91A4AC  // SE_EXEC_DICT_INTERNAL
#define H_1E860193 0x1E860193  // SE_IF_THEN_ELSE
#define H_5391CC89 0x5391CC89  // SE_EXEC_DICT_FN
#define H_0933AC9B 0x0933AC9B  // SE_RETURN_PIPELINE_TERMINATE

// Predicate functions
#define H_F5E4BFD2 0xF5E4BFD2  // SE_FIELD_NE

#endif // FUNCTION_DICTIONARY_DEBUG_H
