/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODE_DATA_H
#define CHAINTREE_HANDLE_NODE_DATA_H

#include "chaintree_support.h"

extern const json_record_t ct_6ctchrak_node_data_records[63];
extern const char ct_6ctchrak_node_data_strings[481];
extern const record_control_t ct_6ctchrak_node_data_controls[5];

#endif /* CHAINTREE_HANDLE_NODE_DATA_H */
