/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_LINKS_H
#define CHAINTREE_HANDLE_LINKS_H

#include <stdint.h>

#define CT_BQ6M6OZB_LINK_TABLE_SIZE 15

extern const uint16_t ct_bq6m6ozb_link_table[CT_BQ6M6OZB_LINK_TABLE_SIZE];

#endif /* CHAINTREE_HANDLE_LINKS_H */