/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_NODES_H
#define CHAINTREE_HANDLE_NODES_H

#include "chaintree_support.h"

#define CT_6SDU632B_NODE_COUNT 24

extern const chaintree_node_t ct_6sdu632b_nodes[CT_6SDU632B_NODE_COUNT];

#endif /* CHAINTREE_HANDLE_NODES_H */