/* Auto-generated by ChainTree Pipeline (LuaJIT) */
#ifndef CHAINTREE_HANDLE_LINKS_H
#define CHAINTREE_HANDLE_LINKS_H

#include <stdint.h>

#define CT_26RJKJFO_LINK_TABLE_SIZE 19

extern const uint16_t ct_26rjkjfo_link_table[CT_26RJKJFO_LINK_TABLE_SIZE];

#endif /* CHAINTREE_HANDLE_LINKS_H */