/* Auto-generated by ChainTree Pipeline (LuaJIT) */

#include "chaintree_handle.h"

const chaintree_handle_t g_chaintree_handle = {
    .unique_id = "ct_6ctchrak",

    .nodes = ct_6ctchrak_nodes,
    .node_count = 8,

    .main_functions = ct_6ctchrak_main_functions,
    .main_function_count = 5,
    .one_shot_functions = ct_6ctchrak_one_shot_functions,
    .one_shot_function_count = 7,
    .boolean_functions = ct_6ctchrak_boolean_functions,
    .boolean_function_count = 3,

    .main_function_names = ct_6ctchrak_main_function_names,
    .one_shot_function_names = ct_6ctchrak_one_shot_function_names,
    .boolean_function_names = ct_6ctchrak_boolean_function_names,

    .main_function_usage_count = ct_6ctchrak_main_function_usage_count,

    .link_table = ct_6ctchrak_link_table,
    .link_table_size = 5,

    .event_strings = (const char **)ct_6ctchrak_event_strings,
    .event_count = 20,

    .bitmask_names = (const char **)ct_6ctchrak_bitmask_names,
    .bitmask_count = 0,

    .kb_table = ct_6ctchrak_kb_table,
    .kb_count = 2,

    .node_data_records = ct_6ctchrak_node_data_records,
    .node_data_records_count = 63,
    .node_data_strings = ct_6ctchrak_node_data_strings,
    .node_data_strings_size = 481,
    .node_data_controls = ct_6ctchrak_node_data_controls,
    .node_data_controls_count = 5,
    .bb_table = NULL
};
