"""
Stage 6: C Code Generator

Generates all .h and .c files from the built pipeline data:
  - chaintree_support.h/.c    (generic runtime)
  - {name}.h/.c               (instance handle)
  - {name}_nodes.h/.c         (node array)
  - {name}_functions.h/.c     (function tables)
  - {name}_links.h/.c         (link table)
  - {name}_node_data.h/.c     (JSON record data)
  - {name}_events.h/.c        (event string table)
  - {name}_bitmasks.h/.c      (bitmask definitions)
  - {name}_kb_info.h/.c       (knowledge base info)
"""

import struct
from pathlib import Path
from typing import Dict, List, Optional

from .stage1_handle import ChainTreeHandle
from .stage2_node_index import NodeIndexBuilder
from .stage3_function_index import FunctionIndexBuilder
from .stage4_link_table import LinkTableBuilder
from .stage5_node_data import NodeDataEncoder


class CCodeGenerator:
    """
    Generate all C header and implementation files from pipeline data.
    """
    
    def __init__(
        self,
        output_dir: Path,
        handle_name: str,
        unique_id: str,
        handle: ChainTreeHandle,
        node_builder: NodeIndexBuilder,
        function_builder: FunctionIndexBuilder,
        link_builder: LinkTableBuilder,
        data_encoder: Optional[NodeDataEncoder],
        main_function_usage: Dict[int, int],
        generate_support: bool = True,
    ):
        self.output_dir = output_dir
        self.handle_name = handle_name
        self.unique_id = unique_id
        self.handle = handle
        self.node_builder = node_builder
        self.function_builder = function_builder
        self.link_builder = link_builder
        self.data_encoder = data_encoder
        self.main_function_usage = main_function_usage
        self.generate_support = generate_support
    
    def _filter_executable_kbs(self, all_kb_names: List[str]) -> List[str]:
        """Filter out function mapping KBs that are not executable."""
        executable = []
        filtered = []
        for kb in all_kb_names:
            if kb.endswith('_test_functions') or kb == 'complete_functions_kb':
                filtered.append(kb)
            else:
                executable.append(kb)
        if filtered:
            print(f"\n  Note: Filtered out {len(filtered)} function mapping KB(s):")
            for kb in filtered:
                print(f"    - {kb}")
        return executable
    
    def _write(self, filename: str, lines: List[str]) -> None:
        """Write lines to a file in the output directory."""
        output_file = self.output_dir / filename
        with open(output_file, 'w') as f:
            f.write("\n".join(lines))
        print(f"  Generated: {output_file}")
    
    # =========================================================================
    # Public Entry Points
    # =========================================================================
    
    def generate_all(self) -> None:
        """Generate all header and implementation files."""
        self.generate_headers()
        self.generate_implementations()
    
    def generate_headers(self) -> None:
        if self.generate_support:
            self._gen_support_header()
        self._gen_instance_header()
        self._gen_node_struct_header()
        self._gen_function_headers()
        self._gen_link_table_header()
        if self.data_encoder:
            self._gen_node_data_header()
        self._gen_event_table_header()
        self._gen_bitmask_table_header()
        self._gen_kb_info_header()
    
    def generate_implementations(self) -> None:
        self._gen_handle_implementation()
        if self.generate_support:
            self._gen_support_implementation()
        self._gen_function_implementations()
        self._gen_node_array_implementation()
        self._gen_link_table_implementation()
        if self.data_encoder:
            self._gen_node_data_implementation()
        self._gen_event_table_implementation()
        self._gen_bitmask_table_implementation()
        self._gen_kb_info_implementation()
    
    # =========================================================================
    # Support Header / Implementation
    # =========================================================================
    
    def _gen_support_header(self) -> None:
        lines = [
            "/* Auto-generated by ChainTree Pipeline - Generic Runtime */",
            "#ifndef CHAINTREE_SUPPORT_H",
            "#define CHAINTREE_SUPPORT_H",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "#include <stddef.h>",
            "",
            "/* ===== Function Pointer Types ===== */",
            "typedef unsigned (*main_function_t)(void *handle, unsigned bool_function_index,",
            "    unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);",
            "typedef void (*one_shot_function_t)(void *handle, unsigned node_index);",
            "typedef bool (*boolean_function_t)(void *handle, unsigned node_index,",
            "    unsigned event_type, unsigned event_id, void *event_data);",
            "",
            "/* ===== Node Structure ===== */",
            "typedef struct {",
            "    uint16_t node_index;",
            "    uint16_t parent_index;",
            "    uint16_t depth;",
            "    uint16_t link_start;",
            "    uint16_t link_count;          /* Bits 0-14: count, Bit 15: auto_start flag */",
            "    uint16_t main_function_index;",
            "    uint16_t init_function_index;",
            "    uint16_t aux_function_index;",
            "    uint16_t term_function_index;",
            "    uint16_t node_data_id;",
            "} chaintree_node_t;",
            "",
            "/* ===== Link Count Bit Packing Macros ===== */",
            "#define LINK_COUNT_MASK     0x7FFF",
            "#define AUTO_START_BIT      0x8000",
            "",
            "#define GET_LINK_COUNT(node)     ((node)->link_count & LINK_COUNT_MASK)",
            "#define GET_AUTO_START(node)     (((node)->link_count & AUTO_START_BIT) != 0)",
            "#define PACK_LINK_COUNT(count, auto_start) \\",
            "    (((count) & LINK_COUNT_MASK) | ((auto_start) ? AUTO_START_BIT : 0))",
            "",
            "/* ===== Node Alias Structure ===== */",
            "typedef struct {",
            "    const char *alias;",
            "    uint16_t node_index;",
            "} node_alias_t;",
            "",
            "/* ===== Knowledge Base Info ===== */",
            "typedef struct {",
            "    const char *kb_name;",
            "    uint16_t root_node_index;",
            "    uint16_t start_index;",
            "    uint16_t node_count;",
            "    uint16_t max_depth;",
            "    uint16_t memory_factor;",
            "    const node_alias_t *aliases;",
            "    uint16_t alias_count;",
            "} chaintree_kb_info_t;",
            "",
            "/* ===== Node Data Structures ===== */",
            "typedef enum {",
            "    JSON_TYPE_STRING = 0,",
            "    JSON_TYPE_INT32 = 1,",
            "    JSON_TYPE_FLOAT32 = 2,",
            "    JSON_TYPE_NULL = 3,",
            "    JSON_TYPE_BOOL = 4,",
            "    JSON_TYPE_ARRAY = 5,",
            "    JSON_TYPE_OBJECT = 6",
            "} json_type_t;",
            "",
            "typedef struct {",
            "    json_type_t object_type;",
            "    union {",
            "        uint32_t string_offset;",
            "        int32_t i32_value;",
            "        float f32_value;",
            "        uint8_t bool_value;",
            "        uint32_t container_count;",
            "    } value;",
            "} json_record_t;",
            "",
            "typedef struct {",
            "    uint32_t start_position;",
            "    uint32_t num_records;",
            "} record_control_t;",
            "",
            "/* ===== Handle Structure ===== */",
            "typedef struct {",
            "    const char *unique_id;",
            "    const chaintree_node_t *nodes;",
            "    uint16_t node_count;",
            "    const main_function_t *main_functions;",
            "    uint16_t main_function_count;",
            "    const one_shot_function_t *one_shot_functions;",
            "    uint16_t one_shot_function_count;",
            "    const boolean_function_t *boolean_functions;",
            "    uint16_t boolean_function_count;",
            "    const char **main_function_names;",
            "    const char **one_shot_function_names;",
            "    const char **boolean_function_names;",
            "    const uint16_t *main_function_usage_count;",
            "    const uint16_t *link_table;",
            "    uint16_t link_table_size;",
            "    const char **event_strings;",
            "    uint16_t event_count;",
            "    const char **bitmask_names;",
            "    uint16_t bitmask_count;",
            "    const chaintree_kb_info_t *kb_table;",
            "    uint16_t kb_count;",
            "    const json_record_t *node_data_records;",
            "    uint16_t node_data_records_count;",
            "    const char *node_data_strings;",
            "    uint16_t node_data_strings_size;",
            "    const record_control_t *node_data_controls;",
            "    uint16_t node_data_controls_count;",
            "} chaintree_handle_t;",
            "",
            "/* ===== Generic Lookup Functions ===== */",
            "const char* ct_get_main_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
            "int ct_get_main_function_index(const chaintree_handle_t *handle, const char *func_name);",
            "const char* ct_get_one_shot_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
            "int ct_get_one_shot_function_index(const chaintree_handle_t *handle, const char *func_name);",
            "const char* ct_get_boolean_function_name(const chaintree_handle_t *handle, uint16_t func_index);",
            "int ct_get_boolean_function_index(const chaintree_handle_t *handle, const char *func_name);",
            "const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index);",
            "int ct_get_event_index(const chaintree_handle_t *handle, const char *name);",
            "const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index);",
            "int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name);",
            "uint16_t ct_get_kb_count(const chaintree_handle_t *handle);",
            "",
            "#endif /* CHAINTREE_SUPPORT_H */"
        ]
        self._write("chaintree_support.h", lines)
    
    def _gen_support_implementation(self) -> None:
        lines = [
            "/* Auto-generated by ChainTree Pipeline - Generic Support Functions */",
            '#include "chaintree_support.h"',
            "#include <string.h>",
            "",
        ]
        
        # Helper to generate name-by-index and index-by-name lookup pairs
        func_types = [
            ("main_function", "main_function_count", "main_function_names"),
            ("one_shot_function", "one_shot_function_count", "one_shot_function_names"),
            ("boolean_function", "boolean_function_count", "boolean_function_names"),
        ]
        
        for label, count_field, names_field in func_types:
            # get name by index
            lines.extend([
                f"const char* ct_get_{label}_name(const chaintree_handle_t *handle, uint16_t func_index) {{",
                f"    if (handle == NULL || handle->{names_field} == NULL) return NULL;",
                f"    if (func_index >= handle->{count_field}) return NULL;",
                f"    return handle->{names_field}[func_index];",
                "}",
                "",
            ])
            # get index by name
            lines.extend([
                f"int ct_get_{label}_index(const chaintree_handle_t *handle, const char *func_name) {{",
                f"    if (handle == NULL || func_name == NULL || handle->{names_field} == NULL) return -1;",
                f"    for (uint16_t i = 0; i < handle->{count_field}; i++) {{",
                f"        if (strcmp(func_name, handle->{names_field}[i]) == 0) return i;",
                "    }",
                "    return -1;",
                "}",
                "",
            ])
        
        # Event lookups
        lines.extend([
            "const char* ct_get_event_name(const chaintree_handle_t *handle, uint16_t event_index) {",
            "    if (handle == NULL || handle->event_strings == NULL) return NULL;",
            "    if (event_index >= handle->event_count) return NULL;",
            "    return handle->event_strings[event_index];",
            "}",
            "",
            "int ct_get_event_index(const chaintree_handle_t *handle, const char *name) {",
            "    if (handle == NULL || name == NULL || handle->event_strings == NULL) return -1;",
            "    for (uint16_t i = 0; i < handle->event_count; i++) {",
            "        if (strcmp(name, handle->event_strings[i]) == 0) return i;",
            "    }",
            "    return -1;",
            "}",
            "",
        ])
        
        # Bitmask lookups
        lines.extend([
            "const char* ct_get_bitmask_name(const chaintree_handle_t *handle, uint8_t bit_index) {",
            "    if (handle == NULL || handle->bitmask_names == NULL) return NULL;",
            "    if (bit_index >= handle->bitmask_count) return NULL;",
            "    return handle->bitmask_names[bit_index];",
            "}",
            "",
            "int ct_get_bitmask_index(const chaintree_handle_t *handle, const char *name) {",
            "    if (handle == NULL || name == NULL || handle->bitmask_names == NULL) return -1;",
            "    for (uint8_t i = 0; i < handle->bitmask_count; i++) {",
            "        if (strcmp(name, handle->bitmask_names[i]) == 0) return i;",
            "    }",
            "    return -1;",
            "}",
            "",
            "uint16_t ct_get_kb_count(const chaintree_handle_t *handle) {",
            "    if (handle == NULL) return 0;",
            "    return handle->kb_count;",
            "}",
            ""
        ])
        
        self._write("chaintree_support.c", lines)
    
    # =========================================================================
    # Instance Header / Implementation
    # =========================================================================
    
    def _gen_instance_header(self) -> None:
        guard = f"{self.handle_name.upper()}_H"
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "chaintree_support.h"',
            f'#include "{self.handle_name}_nodes.h"',
            f'#include "{self.handle_name}_links.h"',
            f'#include "{self.handle_name}_events.h"',
            f'#include "{self.handle_name}_bitmasks.h"',
            f'#include "{self.handle_name}_kb_info.h"',
            f'#include "{self.handle_name}_node_data.h"',
            f'#include "{self.handle_name}_functions.h"',
            "",
            f"extern const chaintree_handle_t g_{self.handle_name};",
            "",
            f"#endif /* {guard} */"
        ]
        self._write(f"{self.handle_name}.h", lines)
    
    def _gen_handle_implementation(self) -> None:
        records_count = self.data_encoder.get_records_count() if self.data_encoder else 0
        strings_size = self.data_encoder.get_strings_size() if self.data_encoder else 0
        controls_count = self.data_encoder.get_controls_count() if self.data_encoder else 0
        
        kb_names = self._filter_executable_kbs(self.handle.get_kb_names())
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            "",
            f'#include "{self.handle_name}.h"',
            "",
            f"const chaintree_handle_t g_{self.handle_name} = {{",
            f'    .unique_id = "{self.unique_id}",',
            "",
            f"    .nodes = {self.unique_id}_nodes,",
            f"    .node_count = {self.node_builder.get_total_nodes()},",
            "",
            f"    .main_functions = {self.unique_id}_main_functions,",
            f"    .main_function_count = {self.function_builder.main_indexer.get_count()},",
            f"    .one_shot_functions = {self.unique_id}_one_shot_functions,",
            f"    .one_shot_function_count = {self.function_builder.one_shot_indexer.get_count()},",
            f"    .boolean_functions = {self.unique_id}_boolean_functions,",
            f"    .boolean_function_count = {self.function_builder.boolean_indexer.get_count()},",
            "",
            f"    .main_function_names = {self.unique_id}_main_function_names,",
            f"    .one_shot_function_names = {self.unique_id}_one_shot_function_names,",
            f"    .boolean_function_names = {self.unique_id}_boolean_function_names,",
            "",
            f"    .main_function_usage_count = {self.unique_id}_main_function_usage_count,",
            "",
            f"    .link_table = {self.unique_id}_link_table,",
            f"    .link_table_size = {self.link_builder.get_link_table_size()},",
            "",
            f"    .event_strings = (const char **){self.unique_id}_event_strings,",
            f"    .event_count = {len(self.handle.get_event_string_table())},",
            "",
            f"    .bitmask_names = (const char **){self.unique_id}_bitmask_names,",
            f"    .bitmask_count = {len(self.handle.get_bitmask_table())},",
            "",
            f"    .kb_table = {self.unique_id}_kb_table,",
            f"    .kb_count = {len(kb_names)},",
            "",
        ]
        
        if self.data_encoder and records_count > 0:
            lines.extend([
                f"    .node_data_records = {self.unique_id}_node_data_records,",
                f"    .node_data_records_count = {records_count},",
                f"    .node_data_strings = {self.unique_id}_node_data_strings,",
                f"    .node_data_strings_size = {strings_size},",
                f"    .node_data_controls = {self.unique_id}_node_data_controls,",
                f"    .node_data_controls_count = {controls_count}",
            ])
        else:
            lines.extend([
                "    .node_data_records = NULL,",
                "    .node_data_records_count = 0,",
                "    .node_data_strings = NULL,",
                "    .node_data_strings_size = 0,",
                "    .node_data_controls = NULL,",
                "    .node_data_controls_count = 0",
            ])
        
        lines.extend(["};", ""])
        self._write(f"{self.handle_name}.c", lines)
    
    # =========================================================================
    # Nodes
    # =========================================================================
    
    def _gen_node_struct_header(self) -> None:
        guard = f"{self.handle_name.upper()}_NODES_H"
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "chaintree_support.h"',
            "",
            f"#define {self.unique_id.upper()}_NODE_COUNT {self.node_builder.get_array_size()}",
            "",
            f"extern const chaintree_node_t {self.unique_id}_nodes[{self.unique_id.upper()}_NODE_COUNT];",
            "",
            f"#endif /* {guard} */"
        ]
        self._write(f"{self.handle_name}_nodes.h", lines)
    
    def _gen_node_array_implementation(self) -> None:
        array_size = self.node_builder.get_array_size()
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_nodes.h"',
            "",
            "/* Node array - preserves original YAML indices; filtered nodes leave gaps */",
            f"const chaintree_node_t {self.unique_id}_nodes[{array_size}] = {{"
        ]
        
        for i in range(array_size):
            ltree_name = self.node_builder.get_node_by_index(i)
            
            if ltree_name is None:
                # Gap / filtered node
                lines.append(f"    /* [{i}] FILTERED */ {{")
                lines.append(f"        .node_index = {i}, .parent_index = 0xFFFF, .depth = 0,")
                lines.append(f"        .link_start = 0, .link_count = 0,")
                lines.append(f"        .main_function_index = 0, .init_function_index = 0,")
                lines.append(f"        .aux_function_index = 0, .term_function_index = 0,")
                lines.append(f"        .node_data_id = 0xFFFF")
                lines.append(f"    }},")
                continue
            
            node_data = self.handle.get_node_data(ltree_name)
            if not node_data:
                lines.append(f"    /* [{i}] ERROR: not found: {ltree_name} */")
                continue
            
            functions = self.handle.get_node_functions(ltree_name)
            main_idx = self.function_builder.main_indexer.get_index(functions['main'])
            init_idx = self.function_builder.one_shot_indexer.get_index(functions['init'])
            aux_idx = self.function_builder.boolean_indexer.get_index(functions['aux'])
            term_idx = self.function_builder.one_shot_indexer.get_index(functions['term'])
            
            link_info = self.link_builder.get_node_link_info(ltree_name)
            link_start = link_info['link_start']
            link_count = link_info['link_count']
            
            node_dict = node_data.get('node_dict', {})
            auto_start = node_dict.get('auto_start', False) if isinstance(node_dict, dict) else False
            
            packed_link_count = link_count & 0x7FFF
            if auto_start:
                packed_link_count |= 0x8000
            
            parent_ltree = self.handle.get_node_parent(ltree_name)
            if parent_ltree and parent_ltree in self.node_builder.ltree_to_final_index:
                parent_idx = self.node_builder.get_node_final_index(parent_ltree)
            else:
                parent_idx = 0xFFFF
            
            depth = self.node_builder.get_node_depth(ltree_name)
            data_id = self.data_encoder.get_node_data_id(ltree_name) if self.data_encoder else 0xFFFF
            
            node_name = node_data.get('node_name', 'unknown')
            auto_tag = " [AUTO_START]" if auto_start else ""
            lines.append(f"    /* [{i}] {node_name}{auto_tag} */")
            lines.append(f"    {{")
            lines.append(f"        .node_index = {i},")
            lines.append(f"        .parent_index = {parent_idx},")
            lines.append(f"        .depth = {depth},")
            lines.append(f"        .link_start = {link_start},")
            lines.append(f"        .link_count = 0x{packed_link_count:04X},  /* count={link_count}, auto_start={auto_start} */")
            lines.append(f"        .main_function_index = {main_idx},")
            lines.append(f"        .init_function_index = {init_idx},")
            lines.append(f"        .aux_function_index = {aux_idx},")
            lines.append(f"        .term_function_index = {term_idx},")
            lines.append(f"        .node_data_id = {data_id}")
            lines.append(f"    }},")
        
        lines.append("};")
        lines.append("")
        self._write(f"{self.handle_name}_nodes.c", lines)
    
    # =========================================================================
    # Functions
    # =========================================================================
    
    def _gen_function_headers(self) -> None:
        guard = f"{self.handle_name.upper()}_FUNCTIONS_H"
        fb = self.function_builder
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "#include <string.h>",
            '#include "chaintree_support.h"',
            "",
            "/* Main function enum */",
            fb.main_indexer.generate_c_enum("MAIN_FUNC"),
            "",
            "/* One-shot function enum */",
            fb.one_shot_indexer.generate_c_enum("ONE_SHOT_FUNC"),
            "",
            "/* Boolean function enum */",
            fb.boolean_indexer.generate_c_enum("BOOL_FUNC"),
            "",
            f"extern const main_function_t {uid}_main_functions[{fb.main_indexer.get_count()}];",
            f"extern const one_shot_function_t {uid}_one_shot_functions[{fb.one_shot_indexer.get_count()}];",
            f"extern const boolean_function_t {uid}_boolean_functions[{fb.boolean_indexer.get_count()}];",
            "",
            f"extern const uint16_t {uid}_main_function_usage_count[{fb.main_indexer.get_count()}];",
            "",
            f"extern const char *{uid}_main_function_names[{fb.main_indexer.get_count()}];",
            f"extern const char *{uid}_one_shot_function_names[{fb.one_shot_indexer.get_count()}];",
            f"extern const char *{uid}_boolean_function_names[{fb.boolean_indexer.get_count()}];",
            "",
            f"#endif /* {guard} */"
        ]
        self._write(f"{self.handle_name}_functions.h", lines)
    
    def _gen_function_implementations(self) -> None:
        fb = self.function_builder
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_functions.h"',
            "",
            "/* Forward declarations - user must provide these functions */",
        ]
        
        for orig in fb.main_indexer.get_all_functions():
            fn = fb.get_typed_main_name(orig) + "_fn"
            lines.append(f"extern unsigned {fn}(void *handle, unsigned bool_function_index, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);")
        lines.append("")
        
        for orig in fb.one_shot_indexer.get_all_functions():
            fn = fb.get_typed_one_shot_name(orig) + "_fn"
            lines.append(f"extern void {fn}(void *handle, unsigned node_index);")
        lines.append("")
        
        for orig in fb.boolean_indexer.get_all_functions():
            fn = fb.get_typed_boolean_name(orig) + "_fn"
            lines.append(f"extern bool {fn}(void *handle, unsigned node_index, unsigned event_type, unsigned event_id, void *event_data);")
        lines.append("")
        
        # Function pointer arrays
        lines.append(f"const main_function_t {uid}_main_functions[] = {{")
        for orig in fb.main_indexer.get_all_functions():
            lines.append(f"    {fb.get_typed_main_name(orig)}_fn,")
        lines.extend(["};", ""])
        
        lines.append(f"const one_shot_function_t {uid}_one_shot_functions[] = {{")
        for orig in fb.one_shot_indexer.get_all_functions():
            lines.append(f"    {fb.get_typed_one_shot_name(orig)}_fn,")
        lines.extend(["};", ""])
        
        lines.append(f"const boolean_function_t {uid}_boolean_functions[] = {{")
        for orig in fb.boolean_indexer.get_all_functions():
            lines.append(f"    {fb.get_typed_boolean_name(orig)}_fn,")
        lines.extend(["};", ""])
        
        # Usage count
        lines.append(f"const uint16_t {uid}_main_function_usage_count[{fb.main_indexer.get_count()}] = {{")
        for i, orig in enumerate(fb.main_indexer.get_all_functions()):
            usage = self.main_function_usage.get(i, 0)
            lines.append(f"    {usage},  /* {orig} */")
        lines.extend(["};", ""])
        
        # Name arrays
        lines.append(fb.main_indexer.generate_c_string_array(f"{uid}_main_function_names"))
        lines.append("")
        lines.append(fb.one_shot_indexer.generate_c_string_array(f"{uid}_one_shot_function_names"))
        lines.append("")
        lines.append(fb.boolean_indexer.generate_c_string_array(f"{uid}_boolean_function_names"))
        lines.append("")
        
        self._write(f"{self.handle_name}_functions.c", lines)
    
    # =========================================================================
    # Link Table
    # =========================================================================
    
    def _gen_link_table_header(self) -> None:
        guard = f"{self.handle_name.upper()}_LINKS_H"
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "",
            f"#define {self.unique_id.upper()}_LINK_TABLE_SIZE {self.link_builder.get_link_table_size()}",
            "",
            f"extern const uint16_t {self.unique_id}_link_table[{self.unique_id.upper()}_LINK_TABLE_SIZE];",
            "",
            f"#endif /* {guard} */"
        ]
        self._write(f"{self.handle_name}_links.h", lines)
    
    def _gen_link_table_implementation(self) -> None:
        uid = self.unique_id
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_links.h"',
            "",
            f"const uint16_t {uid}_link_table[{self.link_builder.get_link_table_size()}] = {{"
        ]
        
        if self.link_builder.link_table:
            line = "    "
            for i, child_index in enumerate(self.link_builder.link_table):
                if i % 10 == 0 and i > 0:
                    lines.append(line + ",")
                    line = "    "
                if i % 10 == 0:
                    line += f"{child_index}"
                else:
                    line += f", {child_index}"
            lines.append(line)
        
        lines.extend(["};", ""])
        self._write(f"{self.handle_name}_links.c", lines)
    
    # =========================================================================
    # Node Data
    # =========================================================================
    
    def _gen_node_data_header(self) -> None:
        guard = f"{self.handle_name.upper()}_NODE_DATA_H"
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "chaintree_support.h"',
            "",
        ]
        
        if self.data_encoder:
            rc = self.data_encoder.get_records_count()
            ss = self.data_encoder.get_strings_size()
            cc = self.data_encoder.get_controls_count()
            if rc > 0:
                lines.extend([
                    f"extern const json_record_t {uid}_node_data_records[{rc}];",
                    f"extern const char {uid}_node_data_strings[{ss}];",
                    f"extern const record_control_t {uid}_node_data_controls[{cc}];",
                    ""
                ])
        
        lines.extend([f"#endif /* {guard} */", ""])
        self._write(f"{self.handle_name}_node_data.h", lines)
    
    def _gen_node_data_implementation(self) -> None:
        if not self.data_encoder or self.data_encoder.get_records_count() == 0:
            lines = [
                "/* Auto-generated by ChainTree Pipeline */",
                f'#include "{self.handle_name}_node_data.h"',
                "", "/* No node data */", ""
            ]
            self._write(f"{self.handle_name}_node_data.c", lines)
            return
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_node_data.h"',
            "",
        ]
        self.data_encoder.generate_c_arrays(lines, self.unique_id)
        self._write(f"{self.handle_name}_node_data.c", lines)
    
    # =========================================================================
    # Events
    # =========================================================================
    
    def _gen_event_table_header(self) -> None:
        guard = f"{self.handle_name.upper()}_EVENTS_H"
        events = self.handle.get_event_string_table()
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "#include <string.h>",
            "",
        ]
        
        if events:
            lines.append(f"#define {uid.upper()}_EVENT_STRING_COUNT {len(events)}")
            lines.extend(["", "typedef enum {"])
            for event_id, index in sorted(events.items(), key=lambda x: x[1]):
                safe = event_id.upper().replace(" ", "_").replace("-", "_")
                lines.append(f"    EVENT_{safe} = {index},")
            lines.extend([
                f"    EVENT_COUNT = {len(events)}",
                "} event_index_t;",
                "",
                f"extern const char *{uid}_event_strings[{len(events)}];",
                ""
            ])
        else:
            lines.extend([
                f"#define {uid.upper()}_EVENT_STRING_COUNT 0",
                "#define EVENT_COUNT 0",
                "",
                f"extern const char *{uid}_event_strings[1];",
                ""
            ])
        
        lines.append(f"#endif /* {guard} */")
        self._write(f"{self.handle_name}_events.h", lines)
    
    def _gen_event_table_implementation(self) -> None:
        events = self.handle.get_event_string_table()
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_events.h"',
            "",
        ]
        
        if events:
            lines.append(f"const char *{uid}_event_strings[{len(events)}] = {{")
            for event_id, _ in sorted(events.items(), key=lambda x: x[1]):
                lines.append(f'    "{event_id}",')
            lines.extend(["};", ""])
        else:
            lines.append(f'const char *{uid}_event_strings[1] = {{ NULL }};')
            lines.append("")
        
        self._write(f"{self.handle_name}_events.c", lines)
    
    # =========================================================================
    # Bitmasks
    # =========================================================================
    
    def _gen_bitmask_table_header(self) -> None:
        guard = f"{self.handle_name.upper()}_BITMASKS_H"
        bitmasks = self.handle.get_bitmask_table()
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            "#include <string.h>",
            "",
        ]
        
        if bitmasks:
            lines.append("/* Bitmask bit positions */")
            for name, bit in sorted(bitmasks.items(), key=lambda x: x[1]):
                safe = name.upper().replace(" ", "_").replace("-", "_")
                lines.append(f"#define BIT_{safe:30s} {bit:2d}  /* 0x{1 << bit:08X} */")
            
            lines.extend(["", "/* Bitmask values */"])
            for name, bit in sorted(bitmasks.items(), key=lambda x: x[1]):
                safe = name.upper().replace(" ", "_").replace("-", "_")
                lines.append(f"#define MASK_{safe:29s} (1U << BIT_{safe})")
            
            lines.extend([
                "",
                f"#define {uid.upper()}_BITMASK_COUNT {len(bitmasks)}",
                "",
                f"extern const char *{uid}_bitmask_names[{len(bitmasks)}];",
                ""
            ])
        else:
            lines.extend([
                f"#define {uid.upper()}_BITMASK_COUNT 0",
                "",
                f"extern const char *{uid}_bitmask_names[1];",
                ""
            ])
        
        lines.append(f"#endif /* {guard} */")
        self._write(f"{self.handle_name}_bitmasks.h", lines)
    
    def _gen_bitmask_table_implementation(self) -> None:
        bitmasks = self.handle.get_bitmask_table()
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_bitmasks.h"',
            "",
        ]
        
        if bitmasks:
            lines.append(f"const char *{uid}_bitmask_names[{len(bitmasks)}] = {{")
            for name, _ in sorted(bitmasks.items(), key=lambda x: x[1]):
                lines.append(f'    "{name}",')
            lines.extend(["};", ""])
        else:
            lines.append(f'const char *{uid}_bitmask_names[1] = {{ NULL }};')
            lines.append("")
        
        self._write(f"{self.handle_name}_bitmasks.c", lines)
    
    # =========================================================================
    # KB Info
    # =========================================================================
    
    def _gen_kb_info_header(self) -> None:
        guard = f"{self.handle_name.upper()}_KB_INFO_H"
        kb_names = self._filter_executable_kbs(self.handle.get_kb_names())
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "chaintree_support.h"',
            "",
            f"#define {uid.upper()}_KB_COUNT {len(kb_names)}",
            "",
        ]
        
        for i, kb_name in enumerate(kb_names):
            aliases = self.handle.get_kb_node_aliases(kb_name)
            if aliases:
                lines.append(f"extern const node_alias_t {uid}_kb_{i}_aliases[{len(aliases)}];")
        
        lines.extend([
            "",
            f"extern const chaintree_kb_info_t {uid}_kb_table[{len(kb_names)}];",
            "",
            f"#endif /* {guard} */"
        ])
        self._write(f"{self.handle_name}_kb_info.h", lines)
    
    def _gen_kb_info_implementation(self) -> None:
        kb_names = self._filter_executable_kbs(self.handle.get_kb_names())
        uid = self.unique_id
        
        lines = [
            "/* Auto-generated by ChainTree Pipeline */",
            f'#include "{self.handle_name}_kb_info.h"',
            "",
        ]
        
        # Alias arrays
        kb_alias_info = {}
        for i, kb_name in enumerate(kb_names):
            aliases = self.handle.get_kb_node_aliases(kb_name)
            if aliases:
                lines.append(f"const node_alias_t {uid}_kb_{i}_aliases[{len(aliases)}] = {{")
                for alias_name, node_index in aliases.items():
                    lines.append(f'    {{"{alias_name}", {node_index}}},')
                lines.extend(["};", ""])
                kb_alias_info[i] = (True, len(aliases))
            else:
                kb_alias_info[i] = (False, 0)
        
        # KB table
        lines.append(f"const chaintree_kb_info_t {uid}_kb_table[{len(kb_names)}] = {{")
        
        for i, kb_name in enumerate(kb_names):
            start_idx, end_idx = self.node_builder.get_kb_range(kb_name)
            node_count = end_idx - start_idx
            root_node_index = start_idx
            
            max_depth = 0
            for idx in range(start_idx, end_idx):
                ltree_name = self.node_builder.final_index_to_ltree.get(idx)
                if ltree_name:
                    max_depth = max(max_depth, self.node_builder.get_node_depth(ltree_name))
            
            memory_factor = self.handle.get_kb_metadata(kb_name, "node_memory_factor", 10)
            
            has_aliases, alias_count = kb_alias_info[i]
            alias_ptr = f"{uid}_kb_{i}_aliases" if has_aliases else "NULL"
            
            lines.extend([
                "    {",
                f'        .kb_name = "{kb_name}",',
                f"        .root_node_index = {root_node_index},",
                f"        .start_index = {start_idx},",
                f"        .node_count = {node_count},",
                f"        .max_depth = {max_depth},",
                f"        .memory_factor = {memory_factor},",
                f"        .aliases = {alias_ptr},",
                f"        .alias_count = {alias_count}",
                "    },"
            ])
        
        lines.extend(["};", ""])
        self._write(f"{self.handle_name}_kb_info.c", lines)